quran/quran.com-frontend-next

src/components/verses/Verse.tsx
src/styles/GlobalStyles.ts

Verse (ayah) overlapping with each other makes it unreadable for a long ayah
- Git clone repo
- Go to Surah Az-Zumar or `http://localhost/39`
- See the overlapping text
Before:
After changes in this PR: 
cc: @mmahalwy

Re-define spacing to prevent overlapping verse

---

.eslintrc.yml
src/components/dls/Tabs/Tabs.tsx

These were initially added in #25 but seem to have gotten lost on master. The commit (https://github.com/quran/quran.com-frontend-next/commit/1c00ebd13a5fa0ae598f50ff6ed1dd1d7a98d13d) no longer exists so this adds back the same functionality.

Re-add prettier rules

---

src/redux/store.ts

TSIA 
Ran a dev and production run, Confirmed that the devtools configuration returns `true` for development and `false` for production

Disable the redux devtools in production 

---

package.json
src/pages_/_app.tsx
src/redux/Provider.tsx
src/redux/store.ts
yarn.lock

Added [redux-persist](https://github.com/rt2zz/redux-persist) to persist parts of our redux store in localstorage across sessions. This will be useful for adding features such as showing the last read position.
Followed the set-up guide here: https://redux-toolkit.js.org/usage/usage-guide#use-with-redux-persist.
Will create a follow-up PR insha'Allah to demo the values being saved in localstorage and persisting across sessions. 
Confirmed that a `persist:root` object is being created in localstorage (see screenshot). No observable changes in the app behavior. Tested the usage and confirmed that the whitelisted values persist in #71.

Add redux-persist

---

src/components/QuranReader/MushafView.tsx
src/components/QuranReader/TranslationView.tsx
src/components/Verse/VerseText.tsx
src/pages_/[chapterId].tsx
src/redux/slices/QuranReader/styles.ts
src/redux/store.ts

Moved the Quran reader styles to redux and persisted it using redux-persist. We might split the translation text and the Quran text into two separate slices in the future. 
Tested that the styles are loaded in the redux, that they persist across sessions, and that the styles are passed to the styled-components correctly. 
The styles are maintained in the store:

Move the Quran Reader styles to redux

---

src/components/QuranReader/QuranPageView.tsx
src/components/QuranReader/TranslationView.tsx
src/components/QuranReader/types.ts
src/components/Verse/VerseText.tsx
src/components/dls/QuranWord/QuranWord.stories.tsx
src/components/dls/QuranWord/QuranWord.tsx
src/redux/slices/QuranReader/styles.ts

Migrated the QuranFont property to redux, it now persists across sessions and is read directly from the `VerseText` component.
Renamed the `QuranFonts` enum to `QuranFont` to follow the recommended enum naming conventions. 
Changed the initial state after clearing localstorage. Confirmed that the fonts load and persist across sessions

Migrate the QuranFont to Redux

---

package.json
src/components/QuranReader/index.tsx
src/pages_/[chapterId].tsx
yarn.lock

This is part 1 of 2 PRs to build infinite scrolling. `useSWR`'s pages feature is going to be deprecated and replaced with useSWRInfinite in `0.3.0`: https://github.com/vercel/swr/pull/435
`useSWRInfinite` allows us to paginate requests and get all the benefits of using `swr`. This feature is currently in beta, I've tested it and will move us back to the stable `swr` once it goes into the stable release (hopefully in a couple of weeks). 
I've refactored the data fetching logic from `[chapterId]` to `QuranReader` as this is where we'll be managing fetching more data as users scroll. 
The initial data is fetched and rendered as expected. I've created a setTimeout to fetch more pages every 3 seconds, the data is fetched correctly.

Add useSWRInfinite for paginating requests

---

package.json
yarn.lock

Upgraded to next.js 9.5: https://nextjs.org/blog/next-9-5
It's fully backward compatible.
Tested the home page and the reading experience. No errors, 1 new warning observed:
`viewport meta tags should not be used in _document.js's <Head>. https://err.sh/next.js/no-document-viewport-meta`

Upgrade to Next.js 9.5

---

.eslintrc.yml
src/api.ts
src/pages_/_document.tsx
src/redux/slices/QuranReader/readingView.ts
types/ChapterType.ts

- Redux toolkit uses [immer](https://github.com/immerjs/immer/) to allow mutating the state inside the reducers, that conflicts with the `no-param-reassign` eslint rule, instead of turning it off, I added an ignore rule for the `draft` object that is usually passed to the reducer to mutate its property, which later becomes the new state.
- Fixed a few other minor warnings.

Fixes for eslint property re-assign error, and other warnings

---

src/components/QuranReader/PageView/Line.tsx
src/components/QuranReader/PageView/groupVersesByLine.ts
src/components/QuranReader/TranslationView/index.tsx
src/components/Verse/VerseText.tsx
src/components/dls/QuranWord/QuranWord.tsx

Added a `highlight` prop to the word component to the `QuranWord` component and the `VerseTextContainer` component. This prop will be used to highlight a word/verse during audio playback, tooltip, etc.
Styles are placeholders.
| Normal Word | Highlighted Word |
|![image](https://user-images.githubusercontent.com/11590314/94989115-3e9bc400-056a-11eb-8a9a-540fcd893ae8.png) | ![image](https://user-images.githubusercontent.com/11590314/94989130-507d6700-056a-11eb-860a-fdfe631beda2.png)|
| Normal Translation | Highlighted Translation |
|![image](https://user-images.githubusercontent.com/11590314/94989103-2a57c700-056a-11eb-8f89-fcc67e0c0720.png)| ![image](https://user-images.githubusercontent.com/11590314/94989099-1dd36e80-056a-11eb-86a4-15550de6adf3.png) …

Add word and verse highlighting

---

src/utils/api.ts

The previous URL got broken after the beta migration. We now use the dedicated API subdomain.

Update API url to api.quran.com

---

src/pages_/_app.tsx
src/pages_/_document.tsx

See https://github.com/vercel/next.js/blob/master/errors/no-document-viewport-meta.md
Confirmed that the viewport meta tags are still produced in the document

Fix viewport meta tag warning

---

.github/workflows/build-storybook.yml
package.json
yarn.lock

Chromatic used to fail frequently and has been a hindrance with little value add. Storybook deployments are still accessible through the CI. This should speed up the CI build times.

Remove Chromatic integration

---

src/components/DeveloperUtility/TranslationsAdjustment.tsx
src/components/QuranReader/index.tsx
src/redux/slices/QuranReader/translations.ts
src/redux/store.ts
src/utils/apiPaths.ts

This PR improves UX by showing a loading indicator instead of falling back to `initialData` which contains the default translations (The Clear Quran and Sahih International) of the `QuranReader` while the user is waiting for the new translations he had selected to show.
1. Make sure you remove `persist:root` from the local storage first if it has been set.
2. Go to a chapter's page e.g. `{url}/5`.
3. Change the reading view to `translation` from the Developer Utility.
4. Usually the API is pretty quick, so to slow it down, open Google Chrome's Dev Tools, go to `Network` tab then change from `No throttling` to `Slow 3G` for example.
5. Open the Developer Utility again and change the pre-selected translations, maybe select an additional one.
6. A loading indicator should show until the …

Don't use initialData when the default translations change

---

src/components/Verse/VerseText.tsx

When there is a long verse e.g. verse 75 of chapter 3, the Quran Reader doesn't wrap the Quranic text so it goes out of the viewport. This PR fixes this by wrapping the text on a new line when it exceeds the width of its container.
1. Go to `{url}/3/75`.
2. The Quranic text should be wrapped across 2 lines.
| ![Before](https://user-images.githubusercontent.com/15169499/126479350-ad15fa11-251e-41df-b69c-340ac09f34dd.png) |![After](https://user-images.githubusercontent.com/15169499/126479330-951d60a6-3f6f-4fec-90e1-ece7ec87dff3.png)|

Fix Quran reader not wrapping on long verses

---

src/components/Verse/VerseActionsMenu.tsx
src/utils/url.ts

This PR adds the ability to share the verse's url.
1. Click on the verse's actions menu.
2. Click on share. The current url should be copied to the clipboard and a message indicating that should appear.
3. The message should return to default after 3 seconds.
| <img width="182" alt="Screen Shot 2021-08-12 at 03 43 34" src="https://user-images.githubusercontent.com/15169499/129100885-c6e12420-b663-47c9-bf79-414e6bfdbd79.png"> | <img width="180" alt="Screen Shot 2021-08-12 at 03 41 55" src="https://user-images.githubusercontent.com/15169499/129100875-b22a963c-45b8-4cea-aa50-369247093db6.png"> |
|  | <img width="184" alt="Screen Shot 2021-08-12 at 03 41 59" src="https://user-images.githubusercontent.com/15169499/129100882-1762174e-5eec-46ea-8973-90802383 …

Add share verse action

---

src/redux/slices/AudioPlayer/persistConfig.ts
src/redux/store.ts

- persist the audio player state, all of it, except `isPlaying`
- try to play the audio, then reload the browser
- all-state should be preserved. But the audio player is paused

persist AudioPlayer state, except isPlaying

---

src/components/QuranReader/index.tsx
src/components/Verse/PlayVerseAudioButton.tsx
src/components/Verse/VerseActions.tsx
src/redux/slices/AudioPlayer/state.ts
types/Verse.ts

- previously we call api to get timestamp api everytime we click "play" verse.
- now we don't call the API anymore
- refactored `getRequestKey` a little bit.
- click the "play" button on the left side of each verse, in translation reading view. See the network request. there should be no new API call.

play verse timestamp with new API

---

next.config.js

This PR adds caching strategy for fonts using [custom Next.js headers](https://nextjs.org/docs/api-reference/next.config.js/headers#wildcard-path-matching). Caching is needed since Next.js and Vercel sets `max-age` to 0 and `must-revalidate` by default for fonts but since they take some time to be downloaded on every browse while they rarely/never change, adding caching would make the user experience faster, save the data usage for the data used to download the fonts and will reduce the load on the server since the fonts will be served from the local cache once they are cached.
|<img width="948" alt="Screen Shot 2021-08-17 at 14 08 47" src="https://user-images.githubusercontent.com/15169499/129681309-b278d336-0026-4a8a-910e-24ca1edf5c0e.png">|<img …

Add caching headers config for fonts

---

src/components/QuranReader/ReadingView/Line.module.scss
src/components/QuranReader/ReadingView/Line.tsx
src/components/QuranReader/ReadingView/Page.module.scss
src/components/QuranReader/ReadingView/Page.tsx
src/components/Verse/VerseText.module.scss
src/components/Verse/VerseText.tsx

This PR adds better line wrapping for mobile when the font scale is above 3. 
| <img width="275" alt="Screen Shot 2021-08-19 at 16 11 13" src="https://user-images.githubusercontent.com/15169499/130042441-90a62c50-c4d0-43ba-b153-a26fe623d501.png"> | <img width="275" alt="Screen Shot 2021-08-19 at 16 11 24" src="https://user-images.githubusercontent.com/15169499/130042453-f204be49-bb2d-49cf-8a1e-b77d807d8a17.png"> |

Better line wrapping on Mobile

---

.eslintrc.json
package.json
src/components/QuranReader/ReadingView/PageFooter.tsx
yarn.lock

Extended the linting configuration recommended by Next.js: https://nextjs.org/docs/basic-features/eslint.
Got a warning about `passHref` not being passed. Fixed that warning. Confirms that the preset works :)

Add the recommended Next linting preset 

---

src/components/Verse/VerseActionsMenu.tsx
src/components/dls/ModalNew/Modal.tsx

This PR solves a minor UI issue with the verse's advanced copy item. 
| <img width="216" alt="Screen Shot 2021-08-28 at 16 28 43" src="https://user-images.githubusercontent.com/15169499/131213362-e21c6e07-9e6d-4ed1-9f7d-3d32363e3bb0.png"> | <img width="216" alt="Screen Shot 2021-08-28 at 16 28 25" src="https://user-images.githubusercontent.com/15169499/131213360-b182f1e0-75de-4a0e-9a29-a3eb6fe4a6dc.png"> |
|<img width="218" alt="Screen Shot 2021-08-28 at 16 28 20" src="https://user-images.githubusercontent.com/15169499/131213359-90797e72-0977-41ec-95b7-99fe7f661cb1.png">|<img width="216" alt="Screen Shot 2021-08-28 at 16 28 08" src="https://user-images.githubusercontent.com/15169499/131213354-b9b46200-7e8c-4b6f-b771-bf4a5d74a9c7.png">|

Fix advanced copy item styling

---

src/components/dls/Popover/index.tsx
src/components/dls/Tooltip/index.tsx
src/styles/ThemeProvider.module.scss
src/styles/ThemeProvider.tsx

This PR attempts to solve the portalling issue that happens when using Radix UI's `Tooltip`, `Popover` and `Dialog` components. The issue is that the content of those components gets portalled by default to underneath `document.body` which causes it to exist higher in the DOM tree than the `div` element where we set the current theme inside of Redux storage by adding it to `data-theme` property.

Fix Portalling issue

---

src/styles/theme.scss

After
Before
it was because the width and the height of `spacing-xsmall` is `9.54` in px. This PR makes the spacing-xsmall `10px`

fix: radio button check is not centered

---

src/components/Navbar/SearchDrawer/SearchDrawer.tsx
src/components/Search/SearchResults/SearchResultItem.tsx
src/components/Search/SearchResults/index.tsx
src/components/dls/Forms/Combobox/index.tsx
src/components/dls/QuranWord/QuranWord.tsx
src/utils/navigation.ts

This PR adds auto-focusing to the input field once the search drawer is opened. Also disallows showing word-by-word translation/transliteration for the search results even if one of them or both are allowed globally.
|<img width="369" alt="Screen Shot 2021-08-31 at 06 05 38" src="https://user-images.githubusercontent.com/15169499/131416943-bf444473-6f8b-4ae3-9b48-ff94a8ae0dbd.png">|<img width="370" alt="Screen Shot 2021-08-31 at 06 02 18" src="https://user-images.githubusercontent.com/15169499/131416932-bfdcf33f-f179-4d89-ab8c-07201ce21cce.png">|

Auto-focus once search drawer opens

---

src/components/HomePage/HomePageWelcomeMessage.module.scss
src/components/dls/Button/Button.module.scss
src/components/dls/Button/Button.tsx
src/components/dls/Tooltip/Tooltip.module.scss
src/styles/ThemeProvider.module.scss
src/styles/theme.scss
src/styles/themes/_dark.scss
src/styles/themes/_light.scss
src/styles/themes/_sepia.scss

* Convert our token rem values to match a full pixel. Thank you @muhajirdev for the bug discovery.
* Add the complete theme token set for the light mode. 
* Apply the tokens to dark and sepia modes (need another follow-up PR) 
* Update the usage of links to the `color-text-link` token
* Remove the alert token 
* Replace the alert color usage with the error color
* Add a selection highlight color
New selection color:

Update tokens + Selection highlighting 

---

src/components/dls/Tooltip/Tooltip.stories.tsx
src/components/dls/Tooltip/index.tsx

This PR adds mobile support for `Tooltip` component since [Radix UI's `Tooltip`](https://www.radix-ui.com/docs/primitives/components/tooltip) doesn't support that out of the box since they consider that there is no hovering on mobile so no need to do anything. To add it, we needed to make the component always controlled to listen to `onClick` event on the Tooltip's `Trigger`.
||![Image](https://user-images.githubusercontent.com/15169499/131671108-88cc90b0-d12e-47c6-9c1d-de7b43fab391.jpg)|

add mobile support for Tooltip

---

src/components/Navbar/SettingsDrawer/AudioSection.tsx

- the audio reciter Combobox is empty
related to `useSWR`'s with `revalidateOnMount : false`. the value is always undefined. Removing this fixes the problem.
@osamasayed helped pinpointing this issue

fix : reciter items disappear

---

src/components/Navbar/SettingsDrawer/AudioSection.tsx
src/components/Navbar/SettingsDrawer/TafsirSection.tsx
src/components/Navbar/SettingsDrawer/TranslationSection.tsx
src/components/dls/Forms/Combobox/MultiSelect.stories.tsx
src/components/dls/Forms/Combobox/SingleSelect.stories.tsx
src/components/dls/Forms/Combobox/index.tsx

This PR:
1. Adds the ability to specify the minimum number of items required which once reached we shouldn't allow un-selecting the item(s). This can work in single and multi select mode. when it's single select, specifying the number to be `1` should be the way to set it. 
2. Fixes the issue of infinite rendering once the Tafsirs/Translations are cleared using backspace key inside the Settings Drawer.
3. Applies the feature added in 1 to the `Reciters` section inside the Settings Drawer which ensures at any given time at least 1 reciter should be selected.

Add minimum required items and fix infinite loop when clearing tags

---

src/components/AudioPlayer/AudioPlayer.module.scss
src/components/AudioPlayer/AudioPlayer.tsx
src/components/AudioPlayer/Slider.module.scss
src/components/AudioPlayer/Slider.tsx

* Replace opacity: 0 and visibility: hidden with display: none. This prevents the items from being interactive and from taking height/width in the container.
* Increase the spacing under the expanded audio player controls
* Pull the reciter name instead of using a placeholder value
* Improve the audio player expanded design on mobile. The transition is broken, needs a follow-up.
| <img width="347" alt="2021-09-01 at 13 41 13@2x" src="https://user-images.githubusercontent.com/11590314/131665351-7b6b3fec-1815-4dc4-87d4-785cf38e2b0e.png"> | <img width="337" alt="2021-09-01 at 13 41 34@2x" src="https://user-images.githubusercontent.com/11590314/131665397-c07d83bd-be84-4246-b1d8-b8cd66a1d572.png">|
| <img width="867" …

Audio player beta polish

---

src/components/dls/QuranWord/QuranWord.tsx
types/Word.ts

This PR adds the ability to only show the Tooltip when the character is of type `Word` since we have the following types:
|Type|Description|
|word| The Quranic Word |
|end| The Ayah marker that indicates the number|
|pause| A pause|
|sajdah| A Sajdah|
|rub-el-hizb|To Indicate The start of a Rub of a Hizb|
|<img width="538" alt="Screen Shot 2021-09-04 at 19 22 13" src="https://user-images.githubusercontent.com/15169499/132094268-32da4b67-83b6-4441-a43f-9de3428eb7ba.png">||

Only show tooltip for words

---

src/components/dls/Forms/Combobox/Combobox.module.scss
src/components/dls/Forms/Combobox/Tag/Tag.module.scss
src/components/dls/Forms/Combobox/index.tsx

This PR improves the combobox styling by adding more padding to each tag and also keeps the input in the same line if the input is empty and there are long tags present.
|<img width="270" alt="Screen Shot 2021-09-04 at 19 49 46" src="https://user-images.githubusercontent.com/15169499/132094985-72d4b48e-a2d9-4aa8-bd86-f8f355104ef8.png">|<img width="275" alt="Screen Shot 2021-09-04 at 19 49 40" src="https://user-images.githubusercontent.com/15169499/132094984-fcfcd2d9-4bd1-4eeb-9fa5-1892e1b905c9.png">

Improve combobox styling

---

src/styles/themes/_dark.scss

TSIA
After 
But we can improve this
- we probably should illuminate the surface of the popover, instead of using box-shadow 
- https://uxplanet.org/8-tips-for-dark-theme-design-8dfc2f8f7ab6
- shall we introduce token `foreground`, `background`. I think vercel is using this.?
- 
- Vercel : Popover is white, on dark theme
- Modal have a white-ish border on dark theme, with dark surface.

fix box shadow on dark mode

---

src/utils/seo.ts
src/vercel.json

This PR disables indexing pages by telling search engine crawlers not to follow or index any page through:
1. Setting the value of `robots` and `googlebot` meta tags to `noindex,nofollow` as per [Google's recommendation](https://developers.google.com/search/docs/advanced/robots/robots_meta_tag) through using `next-seo` [configs](https://github.com/garmeeh/next-seo#dangerouslySetAllPagesToNoFollow).
2. Also by `noindex` as the value of `x-robots-tag` header to Vercel's config file as per Vercel's [recommendation](https://vercel.com/docs/edge-network/headers#x-robots-tag). 
| <img width="457" alt="Screen Shot 2021-09-06 at 13 23 41" src="https://user-images.githubusercontent.com/15169499/132171895-c7b66864-bbf1-4e28-8642-c228e509aff9.png"> | <img …

Disable indexing pages for Beta

---

src/pages/search.module.scss

Adding some spacing, need some room to breathe.
Before
After
We probably should have an `Input` DLS. Added a trello card about that.

add spacing in searchContainer search page

---

src/components/Navbar/LanguageSelector.tsx
src/components/Navbar/NavigationDrawer/NavigationDrawerItem.module.scss
src/components/QuranReader/QuranReader.module.scss
src/components/QuranReader/ReadingView/PageFooter.module.scss
src/components/QuranReader/TafsirView/TafsirView.module.scss
src/components/QuranReader/TranslationView/TranslationView.module.scss
src/components/chapters/ChapterBlock.module.scss
src/components/dls/Button/Button.module.scss
src/components/dls/Link/Link.module.scss
src/redux/slices/AudioPlayer/persistConfig.ts
src/styles/themes/_light.scss

* Hide the language selector until we have support for localization. Was confusing users why we have the word "English" in the navbar.
* Replace all usage of `color: var(--color-primary-medium);` with `color: var(--color-text-default);`. both initially had a value of `#000` but the later is the one intended for text colors (see the next point).
* Reduce the text color and background contrast. Changed `#000` with `#272727`
* Add hierarchy to the home page surah cards by introducing boldness and fading secondary titles.
* Make the translation name text-faded as the information is intended to be secondary. 
* Blacklist the audio player visibility state in redux persist. It was a non-optimal experience when a user opens the site and the audio player is expanded

Beta week 1 misc fixes and improvements

---

src/components/AudioPlayer/AudioPlayer.module.scss
src/components/AudioPlayer/AudioPlayer.tsx
src/components/AudioPlayer/Slider.module.scss
src/components/AudioPlayer/Slider.tsx

On mobile, expanding the audio player was a bit clunky.
This PR fixed the issue
On desktop there's still some layout shift, similar to current next.quran.com, created a trello card about it. Will do in another PR

fix: audio player expand transition on mobile

---

src/components/AudioPlayer/AudioPlayer.module.scss
src/components/AudioPlayer/AudioPlayer.tsx
src/components/AudioPlayer/Slider.module.scss
src/components/AudioPlayer/Slider.tsx
src/components/DeveloperUtility/AudioPlayerAdjustment.tsx
src/components/FeedbackWidget/FeedbackWidget.module.scss
src/components/FeedbackWidget/FeedbackWidget.tsx
src/components/Navbar/Navbar.module.scss
src/components/Navbar/Navbar.tsx
src/components/QuranReader/ContextMenu.module.scss
src/redux/migrations.ts
src/redux/slices/AudioPlayer/persistConfig.ts
src/redux/slices/AudioPlayer/state.ts
src/redux/store.ts
src/styles/_constants.scss
src/utils/event.ts

This PR changes the behavior while browsing on mobile of `NavBar` to hide on scroll down and `AudioPlayer` to minimize when expanded on scrolling down.
|<img width="275" alt="Screen Shot 2021-09-09 at 10 19 55" src="https://user-images.githubusercontent.com/15169499/132616930-1657abcd-2991-4392-a1fe-9f16f84f1a2d.png">|<img width="275" alt="Screen Shot 2021-09-09 at 10 15 25" src="https://user-images.githubusercontent.com/15169499/132616886-8def21bf-01e6-47dd-b0fd-e32f0e19e9a4.png">|
|<img width="274" alt="Screen Shot 2021-09-09 at 10 21 14" src="https://user-images.githubusercontent.com/15169499/132617190-9b14e91b-ff5d-4e53-a654-3fae72d7a7f8.png">|<img width="274" alt="Screen Shot 2021-09-09 at 10 22 36" …

Hide Navbar and minize audio player on scroll

---

src/components/dls/Modal/Modal.module.scss
src/styles/_utility.scss

Autoprefixer can handle css vendoring for us. And nextjs supports autoprefixer out of the box.
So we can safely remove our css vendoring utility
Reference:
- https://nextjs.org/docs/advanced-features/customizing-postcss-config#default-behavior

remove vendor util that is already covered by autoprefixer in nextjs

---

src/redux/store.ts

This PR fixes deprecation issue for Redux's `getDefaultMiddleware`.

Fix getDefaultMiddleware deprecation

---

src/api.ts
src/pages/[chapterId]/[verseId]/index.tsx
src/pages/[chapterId]/[verseId]/tafsirs.tsx
src/pages/[chapterId]/index.tsx
src/pages/[chapterId]/info.tsx
src/pages/index.tsx

- remove `getChapter` api call in `getStaticProps`
- replace with `getChapterData` utility which get the data directly from the json in `/public/data/chapter/en.json` (depends on the language)
Example:
- the chapter data is being in `<NextSEOHead` as `title`. Functionality still works
- the `getChapter`function inside `api.ts` is not removed yet. In case we need it in the future. But we can also remove it to avoid confusion so there's only 1 way to do nothing.

get chapterData directly from the JSON file instead of from API

---

package.json
src/components/DeveloperUtility/ReciterAdjustment.tsx
src/components/Navbar/SettingsDrawer/AudioSection.tsx
src/components/Navbar/SettingsDrawer/TafsirSection.tsx
src/components/Navbar/SettingsDrawer/TranslationSection.tsx
src/components/QuranReader/index.tsx
src/components/Verse/AdvancedCopy/VerseAdvancedCopy.tsx
yarn.lock

This PR upgrades `SWR` version from [0.5.6](https://github.com/vercel/swr/releases/tag/0.5.6) to [1.0.1](https://github.com/vercel/swr/releases/tag/1.0.1) which introduced some breaking changes. The changes that were applied:
- Replace `swr` with `swr/immutable` which would stop revalidating on focus or reconnecting.
- Use `swr/infinite` instead of importing it from `swr` package.
- Use `fallbackData` instead of `initialData`.
Resources:
- https://swr.vercel.app/blog/swr-v1#migration-guide

upgrade SWR

---

src/components/Navbar/SettingsDrawer/ReadingExperienceSection.tsx

see the code, previously, this was an issue. But it's no longer an issue now. Not sure why, maybe the package is updated or something.

remove unnecassary `as unknown` type casting

---

src/components/Search/LanguagesFilter.tsx
src/components/Search/TranslationsFilter.tsx
src/pages/search.tsx

This PR makes it possible to select multiple languages/translations when searching for a keyword on the search page.
|<img width="319" alt="Screen Shot 2021-09-15 at 18 45 47" src="https://user-images.githubusercontent.com/15169499/133428068-7899de95-8a69-4dde-a2cf-bedcb8cd1c8d.png">|<img width="318" alt="Screen Shot 2021-09-15 at 18 45 55" src="https://user-images.githubusercontent.com/15169499/133428077-2a058904-6ce6-49df-bf2a-1c4081b3661d.png">|

Select multiple languages/translations on search page

---

src/components/AudioPlayer/PlayPauseButton.tsx
src/components/AudioPlayer/SurahAudioMismatchModal.module.scss

- fix: loading state unreachable on audioplayer after clicking 
- dark mode UI issue with modal, (mistmacth modal)
Before
After

misc changes: dark mode mismatch modal & loading state

---

src/components/Navbar/SearchDrawer/SearchDrawer.module.scss
src/components/QuranReader/QuranReader.module.scss
src/components/QuranReader/TranslationView/TranslationView.module.scss
src/components/QuranReader/TranslationView/index.tsx
src/components/Verse/VerseText.module.scss
src/components/Verse/VerseText.tsx
src/components/chapters/ChapterHeader/ChapterHeader.module.scss
src/components/chapters/ChapterHeader/index.tsx
src/styles/_utility.scss

Miscellaneous design changes based on various feedback. 
- Fix the clear button not appearing on dark mode
- Add a container utility that has 100% width on mobile, varying length based on desktop width.
- Use the container utility for the Quran reader. (this resolves the feedback request to reduce the side gaps on mobile) 
- Reduce several paddings in the Quran reader as requested by Aqeel.
- Fix a bug in the surah header where the Q icon used to appear above the surah name text (modified the z-index) 
- Add padding under the bismillah SVG in the surah header
The reading mode currently doesn't have any padding in the surah header. Working on resolving it.
| ![2021-09-16 at 00 20 41](https://user-images.githubusercontent.com/11590314/133517540-17e8017c …

Misc design changes

---

.github/workflows/build-storybook.yml

- We deploy storybook by pushing the storybook build artifact into `gh-pages` branch in this repository
- Previously the storybook deployment failed because, we run github action twice `on: [push, pull request]`.
- So sometime there's a race condition, between the 2 actions. Where both is trying to execute `Commit updates`, both action tried to commit and push to same branch at the same time. (see `build-storybook.yml` for the details
- So github rejected one the `push`
```
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
```
- now, we only run the action once `on: …

Fix storybook deployment + add  storybook deploy preview url in PR's comment

---

.eslintrc.json

This PR disables [`arrow-body-style`](https://eslint.org/docs/rules/arrow-body-style) linting rule which comes by default with [eslint-config-airbnb](https://github.com/airbnb/javascript) package

Disable arrow-body-style linting rule

---

src/components/Navbar/SearchDrawer/SearchDrawer.module.scss
src/components/Navbar/SearchDrawer/SearchDrawer.tsx
src/components/QuranReader/QuranReader.module.scss
src/components/QuranReader/index.tsx
src/components/dls/Spinner/Spinner.module.scss
src/components/dls/Spinner/Spinner.tsx

This PR adds a loading spinner instead of text when the user scrolls to the end of the Quran Reader and there are more verses to be fetched.
|<img width="1440" alt="Screen Shot 2021-09-19 at 14 30 10" src="https://user-images.githubusercontent.com/15169499/133919312-ba26c82c-2991-4f95-8256-d9ff0c90851f.png">|<img width="827" alt="Screen Shot 2021-09-19 at 14 29 20" src="https://user-images.githubusercontent.com/15169499/133919359-a6ba8487-f7b3-4dc2-9c0e-ef4aa7b26e09.png">|

Add Spinner for Infinite scroll

---

src/components/dls/Forms/Combobox/index.tsx

This PR resolves the issue with `Combobox` clearing tags on backspace press even when the combobx is not opened.

Solve combobox backspace issue

---

src/components/AudioPlayer/AudioPlayer.tsx
src/components/AudioPlayer/Slider.tsx
src/redux/slices/AudioPlayer/state.ts

Performance improvement, 
- remove currentTime from redux and use `useState` instead
- and we no longer dispatching `setCurrentTime` everytime currentTime is updated. Because this will trigger all selector to re run, which cost performance
[redux dev tools screen when the audio is playing, no `setCurrentTime` is dispatched]

perf: remove currentTime from redux

---

src/components/dls/Link/Link.tsx

Our link components didn't work before. Passing an href (like in the homepage welcome message) caused the href on the anchor tag to be null making it uninteractive.

Fix broken hrefs in the link component

---

src/components/QuranReader/ReadingView/Line.tsx
src/components/QuranReader/TranslationView/TranslationViewCell.tsx
src/hooks/useScrollToElement.ts
src/styles/reset.scss

Instead of doing smooth scrolling on an html level, we set the scrolling behavior to smooth when we call `useScrollToElement`

Fix global smooth scrolling

---

src/components/AudioPlayer/AudioPlayer.module.scss
src/components/AudioPlayer/AudioPlayer.tsx
src/components/AudioPlayer/AudioPlayerSlider.module.scss
src/components/AudioPlayer/AudioPlayerSlider.tsx
src/components/FeedbackWidget/FeedbackWidget.module.scss
src/styles/_constants.scss
src/utils/datetime.ts

* Reduce the height of the player on desktop and mobile (currently uses negative margin, the time and button should be combined into a single component) 
* Use total time instead of remaining time
| ![2021-09-25 at 16 49 25](https://user-images.githubusercontent.com/11590314/134775591-65a29f36-e9bf-41e4-b9bf-9c994d071158.png) | ![2021-09-25 at 16 49 38](https://user-images.githubusercontent.com/11590314/134775603-6dd2e47f-33e4-4519-93e4-0ef9c6bf32c2.png) |
| ![2021-09-25 at 16 48 43](https://user-images.githubusercontent.com/11590314/134775571-1f39a220-50e9-43eb-a002-27481689bc74.png) | ![2021-09-25 at 16 47 52](https://user-images.githubusercontent.com/11590314/134775548-323c3199-cd35-4a9c-ac7c-1b2ecdd4fb5d.png) …

New Audio player follow-up design polish

---

src/components/dls/Forms/Combobox/ComboboxItem/ComboboxItem.module.scss

This PR remove the CLS that happens when the user hovers on an item which sometimes leads to some items being split into two lines instead of the same line.
|<img width="283" alt="Screen Shot 2021-09-26 at 19 13 15" src="https://user-images.githubusercontent.com/15169499/134807593-ec874cbc-b9db-4f9f-a572-626f241a74f0.png">|<img width="280" alt="Screen Shot 2021-09-26 at 19 12 57" src="https://user-images.githubusercontent.com/15169499/134807591-42537a10-3d43-43ef-9cec-31a9f0d548bc.png">|

Remove ComboboxItem CLS on hover

---

src/components/Verse/VerseText.tsx
src/components/Verse/pageUtils.ts

This PR removes center aligning for IndoPak line-15 and line-16 Mushafs.
|![Before](https://user-images.githubusercontent.com/15169499/135384398-dc36a0d2-4919-4ffd-a2b1-f48599bd457f.png)|![After](https://user-images.githubusercontent.com/15169499/135384589-bac69676-6111-4a90-9c63-6b2ada453c94.png)|

Remove center-align for IndoPak Mushaf

---

src/components/AudioPlayer/RepeatAudioModal/RepeatAudioModal.tsx

When repeat mode is active, the action on the left will "Exit Repeat Mode". When clicked it will exit the repeat mode and pause the audio
- Repeat the range / verse
- Click the repeat button
- Click Exit Repeat Mode, it should pause the audio and exit the repeat mode (it's easier to see when the repeat mode badge PR is merged)

add "Stop Repeating" action to repeat audio modal

---

src/components/QuranReader/TranslationView/TranslationViewCell.tsx
src/components/Verse/PlayVerseAudioButton.tsx
src/redux/slices/AudioPlayer/state.ts

Clicking the play button here, now won't trigger additional API calls to fetch the timestamp data. We will use the verse's timestamp data that comes from verses API

Prevent additional API call when clicking "play" button on TranslationView Cell

---

src/utils/qs-stringify.test.ts
src/utils/qs-stringify.ts

This PR fixes the issue with sending `null` values to BE and also fixes the issue of splitting an array of 2 into 2 fields instead of having 1 field with 2 values separated by `,`.

Fix Stringify request params

---

src/api.ts
types/ApiResponses.ts

There's a bug when we rename audioFile -> audioData. The backend is still returning filed `audio_files`. This PR fixed the issue

fix: audio data bug

---

src/components/dls/KeyboardInput/KeyboardInput.module.scss
src/components/dls/KeyboardInput/KeyboardInput.stories.tsx
src/components/dls/KeyboardInput/index.tsx

This PR adds `KeyboardInput` component to DLS. The component will be used as a UI indicator to which keyboard shortcuts are available either globally or inside a specific component.

Add KeyboardInput component to DLS

---

src/pages/_app.tsx
src/utils/api.ts

Our production environment now points to CloudFront's edge api cache causing 25-30% reduction in api response time. 
Also set up preconnection to the api host to rduce the response time. Thank you @naveed-ahmad for the tip!

Add CloudFlare API host and set-up link preconnect

---

src/components/AudioPlayer/OverflowAudioPlayerActionsMenu.module.scss
src/components/AudioPlayer/OverflowAudioPlayerActionsMenu.tsx
src/components/dls/PopoverMenu/PopoverMenu.tsx
src/pages/_app.tsx

Desktop
Tablet
Mobile
When auto scroll to highlhgted verse on mobile / tablet
When auto scroll to highlighted verse on desktop

Hack: popovermenu position audioplayer

---

src/utils/api.ts

This PR removes an extra `/` added at the end of the root path which resulted in the generated API path being in the following format:
`https://staging.quran.com/api/qdc//resources/translations?language=en`
instead of
`https://staging.quran.com/api/qdc/resources/translations?language=en`

Fix API root path

---

src/components/Navbar/Drawer/Drawer.module.scss
src/components/Navbar/Drawer/index.tsx
src/hooks/useBrowserLayoutEffect.ts
src/hooks/usePreventBodyScrolling.ts

This PR disables scrolling when a drawer is open since there is no point of triggering the `scroll` event since if a drawer is open, it should be the main focus of the page. This also will prevent the `scroll` event that is being listened to inside `GlobalScrollListener` from firing which would save multiple redux dispatches and re-renders from happening. It will also improve the experience on mobile since without disabling the scrolling, the drawer plays up a bit on scrolling.

Disable scrolling when a drawer is open

---

src/components/Verse/AdvancedCopy/VerseAdvancedCopy.module.scss
src/components/Verse/AdvancedCopy/VerseAdvancedCopy.tsx

* Fix showing loading spinner while having validation error in range selection
* Add spacing for custom error message

Fix showing loading while validation error in advanced copy ayah range selection

---

locales/en/common.json
src/components/Navbar/SettingsDrawer/ReadingExperienceSection.tsx
src/components/dls/QuranWord/QuranWord.tsx
src/redux/migrations.ts
src/redux/slices/QuranReader/readingPreferences.ts
src/redux/store.ts
types/QuranReader.ts

Adding new settings "Word Click"
Expected behavior
- When "Play Audio" option is selected. Clicking the word will "play word by word audio", or update the timestamp of the current playing audio.
- When "No audio" option is selected. Clicking the word will do nothing

Add "on word click" settings

---

src/components/Navbar/SettingsDrawer/AudioSection.tsx

This PR fixes Playback Speed options issue inside the Settings Drawer where the options were not showing.
|<img width="387" alt="Screen Shot 2021-11-11 at 12 49 36" src="https://user-images.githubusercontent.com/15169499/141245030-edbfc0e9-9a18-455d-8c64-9c99364149ce.png">|<img width="381" alt="Screen Shot 2021-11-11 at 12 50 26" src="https://user-images.githubusercontent.com/15169499/141245037-47f4841c-0901-4730-95bd-b379ddc57faa.png">|

Fix Playback Speed issue

---

src/components/Navbar/LanguageSelector.tsx

This PR persists the user's locale in the Cookies so that we can redirect him to his previously selected locale whenever he lands on `/` route.  
Reference: [Next.js's docs](https://nextjs.org/docs/advanced-features/i18n-routing#leveraging-the-next_locale-cookie).
Closes #694

Persist selected locale

---

src/components/Navbar/NavigationDrawer/CommunitySection.module.scss

Before
After
This only happens on `system` theme

fix: discord logo bug

---

src/components/Navbar/SearchDrawer/Buttons/DrawerSearchIcon.module.scss

fix: search icon not centered in search drawer

---

locales/en/common.json
package.json
src/components/Navbar/SettingsDrawer/TranslationSelectionBody.module.scss
src/components/Navbar/SettingsDrawer/TranslationSelectionBody.tsx
src/components/dls/Forms/Input/Input.module.scss
src/pages/search.tsx
yarn.lock

- Add search translations feature
- Update Input styling
The dependency is lazy loaded. Only loaded when we go to this part of settings

Search translations feature

---

src/utils/locale.ts

`bahasa` mean `language`. We can just remove it to make the UI width shorter. #798 
Google does this as well

Update Melayu locale name

---

src/components/Navbar/LanguageSelector.module.scss

Width of Navbar Selectbox changed to 160px.

Select language does not have enough width #798 bug fixed

---

src/components/Navbar/SearchDrawer/Header/Header.module.scss
src/components/dls/Forms/Input/Input.module.scss

Closes #814
Closes #816
This is a very minimal change. In dark mode, the text color of the `Input` component and search input was dark since it was not set using the theme's CSS variables. This adds the color style property to the input elements.
None. Since you guys don't have any screenshot testing I think? And the change is only visual, so no unit tests either.
| ![image](https://user-images.githubusercontent.com/36920441/143567639-22b75191-cbfa-4c32-be3b-7d79c15055e2.png) | ![image](https://user-images.githubusercontent.com/36920441/143567056-7b5432c9-9ad2-42e0-bcc7-522bd58cb9c6.png) |

Fix text color of search input and DLS input component

---

src/components/Navbar/NavigationDrawer/NavigationDrawer.tsx
src/components/Navbar/NavigationDrawer/NavigationDrawerBodySkeleton.module.scss
src/components/Navbar/NavigationDrawer/NavigationDrawerBodySkeleton.tsx
src/components/Navbar/SettingsDrawer/SettingsBodySkeleton.module.scss
src/components/Navbar/SettingsDrawer/SettingsBodySkeleton.tsx
src/components/Navbar/SettingsDrawer/SettingsDrawer.tsx
src/components/chapters/ChapterAndJuzList.tsx
src/components/chapters/ChapterAndJuzListSkeleton.module.scss
src/components/chapters/ChapterAndJuzListSkeleton.tsx
src/components/dls/Skeleton/Skeleton.module.scss
src/components/dls/Skeleton/Skeleton.tsx
src/pages/index.tsx

Replaced `Spinner` component with Skeleton for homepage's side menus and Chapters list.
The skeletons disappear once their component loads, so to test it you mostly have to throttle the network to have enough time to see the skeleton loader.
I tested it on different screen sizes and RTL.
**Chapters list skeleton:**
https://user-images.githubusercontent.com/3989750/141656066-44e282a5-bc07-4138-8194-62de8aaefe3b.mp4
**Settings Menu Skeleton**
https://user-images.githubusercontent.com/3989750/141656281-72d36b72-6a12-47d8-9c11-8d88330191ca.mp4
**Nav Menu Skeleton:**
https://user-images.githubusercontent.com/3989750/141656168-e52c09ea-2c76-492c-b340-b298780252b6.mp4

Added Skeleton components for sidemenus and homepage

---

src/components/Notion/Blocks/index.tsx
src/components/Notion/Page/index.tsx
src/pages/product-updates/[id].tsx
src/pages/product-updates/index.tsx
src/utils/datetime.test.ts
src/utils/datetime.ts
src/utils/notion.ts

This PR updates the revalidation value of the Notion pages to match that of the earliest expiry date of an image (if found).
Closes #866

Update Notion image rendering logic

---

.eslintrc.json

Adding react/jsx-key rule as a warning for now
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-key.md
Turns out we have jsx missing "key". Will upgrade this rule into "error" later once we gradually fixed this issue.

chore: add eslint rule react/jsx-key

---

src/components/Navbar/SettingsDrawer/QuranFontSection.tsx

Right now our default font is King Fahad Complex (which is uthmani)
But when user switch to "Indopak" and switch back to "Uthamani", they will be switched into QPCHafs. 
This PR fixed that issue, and instead they will switch back into King Fahad Complex

fix default font when switching back to uthmani

---

locales/en/common.json
src/components/Navbar/SettingsDrawer/WordByWordSection.tsx
src/components/Navbar/SettingsDrawer/WordTooltipSection.tsx

There's a feedback, a user is a bit confused that there's no language selection in word tooltip section. 
What we do is basically, taking the lang selection from word by word, and duplicate it here in tooltip section. A quick fix for now.

Add language selction in WordTooltipSection

---

src/components/CommandBar/CommandBarBody/index.tsx
src/components/NextSeoWrapper.tsx
src/components/TarteelVoiceSearch/BodyContainer/SearchResults.tsx
src/utils/string.test.ts
src/utils/string.ts
src/utils/verse.test.ts

This PR shortens the `description` meta tags to match the [recommended number of characters](https://yoast.com/meta-descriptions/) (150-160 characters).
|<img width="1072" alt="Screen Shot 2021-12-13 at 14 26 30" src="https://user-images.githubusercontent.com/15169499/145770067-960cc965-2b59-4ca5-a3c0-4dd29e6e6e22.png">|<img width="1077" alt="Screen Shot 2021-12-13 at 14 26 23" src="https://user-images.githubusercontent.com/15169499/145770060-3ad5b688-5817-457e-babc-c18313f1c6bc.png">|

Shorten description meta tags

---

src/components/dls/Button/Button.module.scss
src/styles/themes/_dark.scss

This is just a temporary fix. I will do a more systematic update related to color token later.
Before
After

design update: update secondary color on dark theme

---

src/pages/about-us.tsx
src/pages/apps.tsx
src/pages/contentPage.module.scss

This PR removes multipls `h1` tags from `/apps` and `/about-us` routes as per [ahrefs](http://ahrefs.com/) recommendation:

[SEO] Remove multiple h1 tags

---

src/components/dls/QuranWord/QuranWord.module.scss

fix: missing gap after first word

---

src/components/QuranReader/TafsirView/SurahAndAyahSelection.tsx
src/components/QuranReader/TafsirView/TafsirView.module.scss

The close icon was not overlapping with the ayah selection
Before
After

fix(tafsir): close icon not visible on small screen

---

src/components/DeveloperUtility/TafsirsAdjustment.tsx
src/components/Navbar/SettingsDrawer/TafsirSection.tsx
src/components/Navbar/SettingsDrawer/TafsirSelectionBody.tsx
src/components/QuranReader/TafsirView/LanguageAndTafsirSelection.tsx
src/components/QuranReader/TafsirView/TafsirBody.tsx
src/pages/[chapterId]/[verseId]/tafsirs.tsx
src/pages/[chapterId]/tafsirs/[tafsirId].tsx
src/redux/defaultSettings/defaultSettings.ts
src/redux/defaultSettings/locales/ar.ts
src/redux/defaultSettings/locales/bn.ts
src/redux/defaultSettings/locales/ru.ts
src/redux/defaultSettings/locales/ur.ts
src/redux/slices/QuranReader/tafsirs.ts
src/redux/types/TafsirsSettings.ts
src/utils/apiPaths.ts
src/utils/navigation.ts
types/ApiResponses.ts

This PR adds slugs for Tafsirs which is better for SEO and readability. For example `/1:2/tafsirs/ru-tafseer-al-saddi` would show the same content as `1:2/tafsirs/170`.

add slugs to tafsirs

---

src/components/QuranReader/TafsirView/TafsirBody.tsx
src/components/dls/ContentModal/ContentModal.tsx
src/utils/navigation.ts

This PR updates the `fakeNavigate` util to preserve the current locale when selecting a different Tafsir.

[Tafsir] Preserve the locale in the url

---

src/components/QuranReader/TafsirView/LanguageAndTafsirSelection.tsx

This PR fixes an exception thrown when changing the locale from the Navbar while viewing a Tafsir via the url and not the Modal. e.g. when viewing `/2:1/tafsirs/tafseer-ibn-e-kaseer-urdu` and then switching the locale to Arabic.

[Tafsir] fix exception when switching locale

---

src/pages/_app.tsx
src/utils/css.ts

This PR adds logging when the user's browser doesn't support [CSS logical properties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties).

[Logging] unsupported logical css properties

---

src/components/QuranReader/QuranReaderBody.tsx
src/components/QuranReader/QuranReaderView.tsx
src/components/QuranReader/ReadingView/index.tsx
src/components/QuranReader/TranslationView/index.tsx
src/components/QuranReader/index.tsx

This PR adds the end of QuranReader navigation controls to the bottom of the virtualized list instead of outside of it.

[Windowing] Add footer to List

---

src/components/dls/Forms/Combobox/Icons/SearchInputIcon.module.scss

fix: combobox search input icon not centered

---

src/components/dls/Popover/Popover.module.scss
src/components/dls/Popover/index.tsx
src/components/dls/Tooltip/Tooltip.module.scss
src/components/dls/Tooltip/index.tsx

fix: quranword is cut on safari

---

src/components/QuranReader/TranslationView/TranslatioViewCellSkeleton.tsx
src/components/QuranReader/hooks/useSyncQueryParams.ts
src/components/QuranReader/index.tsx
src/hooks/useGetQueryParamOrReduxValue.ts
src/utils/queryParamValidator.test.ts
src/utils/queryParamValidator.ts
types/QueryParam.ts

This PR adds the ability to parse the `translations` query param in the URL and apply it inside the QuranReader. It also adds the ability to sync between the selected translations settings and the `translations` query param.

[Query Params] Add translations

---

src/components/QuranReader/hooks/useSyncReduxAndQueryParams.ts
src/components/QuranReader/index.tsx
src/hooks/useGetQueryParamOrReduxValue.ts
types/QueryParam.ts

This PR adds the ability to parse the word by word locale query param (`wbw_locale`) in the URL and apply it inside the QuranReader. It also adds the ability to sync between the selected word by word locale settings and the query param.

[Query Params] WBW query params

---

types/Tarteel/SearchResult.ts

In the Tarteel search backend we had some deprecated fields included in the search result matches. We have now fully removed those fields from the response. Those fields were already unused on quran.com, but the type definition needs to be updated.
Inspected the code to understand whether any of these fields were being used. Will test with the updated backend response before merging. Opening now for early review.

Remove unused Tarteel search response fields no longer sent by api

---

locales/en/common.json
locales/en/quran-reader.json
src/components/AudioPlayer/AudioPlayerBody/index.tsx
src/components/AudioPlayer/Buttons/PlayPauseButton.tsx
src/components/AudioPlayer/Buttons/SelectReciterMenu.tsx
src/components/AudioPlayer/RepeatAudioModal/RepeatAudioModal.tsx
src/components/AudioPlayer/SeekButton.tsx
src/components/DeveloperUtility/ReciterAdjustment.tsx
src/components/QuranReader/PlayChapterAudioButton.tsx
src/components/QuranReader/QueryParamMessage/QueryParamMessage.module.scss
src/components/QuranReader/QueryParamMessage/index.tsx
src/components/QuranReader/TranslationView/TranslatioViewCellSkeleton.tsx
src/components/QuranReader/hooks/useSyncReduxAndQueryParams.ts
src/components/QuranReader/index.tsx
src/components/Verse/PlayVerseAudioButton.tsx
src/components/dls/QuranWord/QuranWord.tsx
src/components/dls/Toast/Toast.tsx
src/hooks/useGetQueryParamOrReduxValue.ts

This PR shows a notification message to the user that the query params settings have been applied and giving the ability to the user to either use the Redux values instead or persist the query params values into Redux for later usage.

[Query Params] Add query params message

---

src/components/Navbar/SettingsDrawer/TranslationSelectionBody.tsx

This PR handles the case when the search query in the settings drawer's translation section doesn't match any existing translations.

Handle when no translations found

---

src/api.ts
src/components/AudioPlayer/Buttons/SelectReciterMenu.tsx
src/components/DeveloperUtility/ReciterAdjustment.tsx
src/components/Navbar/SettingsDrawer/ReciterSelectionBody.tsx
src/components/Navbar/SettingsDrawer/TranslationSelectionBody.tsx
src/components/Radio/ReciterStationList.tsx
src/utils/apiPaths.ts

- Fix reciter api 
- Search translation and recitation using localized names as well
- Show localized names, instead of default English names
- Change the site locale to Urdu or Arabic
- Open the settings, go to reciter or translations 
- You should see localised names and should be able to search using localised names as well

New reciter api

---

src/components/QuranReader/TafsirView/TafsirBody.tsx
src/components/Verse/PlainVerseText.tsx

This PR adds a component that only shows the verse text without the extra functionalities for specific scenarios e.g. ayah highlighting when audio is playing or showing a tooltip when hovering over a verse or showing the word by word translation/transliteration.

Add PlainVerseText

---

public/icons/west.svg

fix: back icon color

---

src/components/QuranReader/ReadingView/WordActionsMenu/index.tsx
src/components/QuranReader/ReadingView/WordPopover/index.tsx
src/components/QuranReader/TranslationView/QuranReflectButton.tsx
src/components/QuranReader/TranslationView/ShareVerseButton.tsx
src/components/Verse/OverflowVerseActionsMenu.tsx
src/components/Verse/OverflowVerseActionsMenuBody.tsx
src/components/Verse/PlayVerseAudioButton.tsx

This PR closes the verse actions menu of the Reading View after the action has been clicked by the user.

Close ReadingView actions menu after triggering action

---

src/components/QuranReader/ReadingView/WordPopover/WordPopover.module.scss
src/components/QuranReader/ReadingView/WordPopover/index.tsx
src/hooks/useLongPress.ts

This PR makes it possible to open the verse actions menu for the reading view on mobile when the user long presses a word.

Open reading view verse menu on long press on mobile

---

src/components/dls/Footer/FooterThemeSwitcher.tsx

This PR resolves #1165 by highlighting the active theme on the footer theme switcher
|<img width="760" alt="Screen Shot 2022-01-29 at 7 44 02 PM" src="https://user-images.githubusercontent.com/39024901/151669808-207c5bc7-879d-49f4-b73e-c37e1e2743c8.png"> | <img width="938" alt="Screen Shot 2022-01-29 at 7 51 31 PM" src="https://user-images.githubusercontent.com/39024901/151669826-da83a999-99d0-4e58-a6d9-1cd5f3143f4e.png">|

Fix: Hghlight currently selected theme on footer theme switcher

---

src/components/Reciter/ReciterInfo.module.scss

fix: reciter image aspect ratio

---

src/api.ts
src/components/QuranReader/TafsirView/TafsirBody.tsx
src/pages/[chapterId]/tafsirs/[tafsirId].tsx

This PR resolves #1066. On tafsirs modal / page when the user has selected tajweed Quran font tafsirs were not getting rendered since `Mushaf ID` was not sent to the tafsirs API. 
I have also added a second condition to `shouldUseInitialTafsirData` variable where it needs to be on default font to be true. This is because when rendering the tafsir with `initialTafsirData` means that we are using data `getStaticProps` which is from SSR and this will not work if user has changed their font preference from the default since we are persisting the preference data on the browser's local storage.
| ![Tafsir-Surah-Al-Fatihah-1-Quran-com](https://user-images.githubusercontent.com/39024901/151719290-740738b5-ade3-41ab-a7bc-44aa6d22d023.png) | …

Fix: Send Mushaf ID to Tafseers API

---

src/styles/themes/_sepia.scss

This only fix the effect on normal button dls. For customized button like the one in `VerseActions`. Still need to find the right color
Before
After

fix: sepia button hover effect

---

src/components/Navbar/SettingsDrawer/ReciterSelectionBody.module.scss
src/components/Navbar/SettingsDrawer/ReciterSelectionBody.tsx
src/components/dls/Forms/RadioGroup/Item.module.scss
src/components/dls/Forms/RadioGroup/Item.tsx
src/components/dls/Forms/RadioGroup/RadioGroup.module.scss
src/components/dls/Forms/RadioGroup/RadioGroup.tsx
src/components/dls/Forms/RadioGroup/Root.module.scss
src/components/dls/Forms/RadioGroup/Root.tsx

- use DLS radio group in reciter selection settings
- accept `renderItem` prop in `RadioGroup`
- add `Item` & `Indicator` components in `RadioGroup` to allow further customization
| <img width="258" alt="image" src="https://user-images.githubusercontent.com/58295120/151602040-23f3b828-ad10-4d23-80de-fb492cd02914.png"> | <img width="254" alt="image" src="https://user-images.githubusercontent.com/58295120/151602080-5d654880-d71a-4cc7-847e-e7d63dc3a346.png"> |

use DLS radio group in reciter settings

---

src/components/AudioPlayer/MediaSessionApiListeners.tsx

There's a case where the audio data is not yet ready. But it's already being used in the MediaSession. This PR fixed the issue

fix: audio data is not ready when playing audio

---

i18n.json

fix: radio station name not found on pages other than "home"

---

src/components/Fonts/FontPreLoader.tsx
src/components/QuranReader/TranslationView/TranslationText/TranslationText.module.scss
src/styles/fonts.scss
src/styles/global.scss

Both noto and Mehr look the same, but Mehr has fixed "line-height" issues and has tashkeel rendering support.
Mehr on top, bottom text is Noto. You can see lot of text cut off in Noto.

replace Noto Urdu with Mehr nastaleeq

---

src/components/QuranReader/ReadingView/TranslationsButton/index.tsx
src/components/QuranReader/ReadingView/WordActionsMenu/index.tsx

This PR closes the ReadingView's popover menu on Translations modal closing.

Close ReadingView popover menu on translations modal close

---

src/components/QuranReader/ReadingView/PageNavigationButtons/index.tsx

This PR fixes flipped previous page issue on RTL locales e.g. `/ar/2` in the reading view.
|<img width="77" alt="Screen Shot 2022-02-17 at 17 19 30" src="https://user-images.githubusercontent.com/15169499/154459987-43712179-a6c2-4c56-bee4-e4bccbe01e49.png">|<img width="68" alt="Screen Shot 2022-02-17 at 17 42 29" src="https://user-images.githubusercontent.com/15169499/154459992-cdf27e7c-504d-4177-a725-9900e9b0d68f.png">|

Fix flipped previous page button on RTL locales

---

src/pages/[chapterId]/[verseId]/tafsirs.tsx

This PR fixes the issue when we are using slugs for a chapter to view the Tafsir of a specific verse e.g. https://beta.quran.com/al-baqarah/10/tafsirs.

Fix Tafsir slugs throwing exception

---

src/api.ts
src/components/Fonts/FontPreLoader.tsx
src/components/Radio/ReciterStationList.tsx
src/components/Reciter/ReciterInfo.tsx
src/components/Reciter/RecitersList.tsx
src/components/dls/QuranWord/TajweedWordImage.tsx
src/pages/reciters/[reciterId]/[chapterId].tsx
src/styles/fonts.scss
src/utils/api.ts
src/utils/cdn.ts
src/utils/fontFaceHelper.ts

Fixed page 1 of v1 font https://github.com/quran/quran.com-api/issues/516 but there is no way to invalidate cached fonts in browsers. 
Added assets version that'll invalidate the cached content. For now, invalidation is at the global level, we should invalidate only assets that are changed, will do in successive PR.

add asset version to invalidate them.

---

src/components/QuranReader/ReadingView/index.tsx
src/components/QuranReader/TranslationView/index.tsx

This PR artificially increases the viewport of both `ReadingView` and `TranslationView` so that we pre-fetch more pages in order not to let the user see the skeletons as frequent.

Increase viewport for QuranReader

---

src/components/QuranReader/TafsirView/TafsirVerseAction.tsx
src/components/Verse/OverflowVerseActionsMenuBody.tsx
src/components/Verse/VerseActionAdvancedCopy/index.tsx

This PR includes:
1. Making the verse actions menu of the Reading view close on Tafsir modal close.
2. Adding the fade out effect of the Tafsir modal on close.
3. Fix the issue of calling undefined `onActionTriggered` on closing the Tafsirs Modal in Translation view.

Show fade out effect for Tafsir modal

---

src/components/QuranReader/TranslationView/TranslationViewCell.tsx
src/components/dls/QuranWord/QuranWord.tsx

This PR fixes the issue of trying to request the audio file of the end of verse's indicator (verse number) on click in the translation view.
| ------ |
|<img width="362" alt="Screen Shot 2022-02-22 at 16 35 12" src="https://user-images.githubusercontent.com/15169499/155105523-11ededa6-67a9-4ca9-9eff-bd35e746cd66.png">|

Fix clicking on verse indicator audio issue

---

src/utils/validator.ts

This PR handles the exception thrown when accessing a verse of a non-valid chapter Id e.g. `/test/1`
|Before|After|
|-----|-----|
|<img width="585" alt="Screen Shot 2022-02-22 at 18 13 55" src="https://user-images.githubusercontent.com/15169499/155121351-bbbf6573-caa3-44ec-bc11-46eb1aea705a.png">|<img width="526" alt="Screen Shot 2022-02-22 at 18 17 34" src="https://user-images.githubusercontent.com/15169499/155121880-619cdde2-c376-4f86-b9ab-4721b14f61a2.png">|

Handle chapter route exception

---

src/components/Navbar/SettingsDrawer/QuranFontSection.tsx
src/components/QuranReader/ReadingView/PageContainer.tsx
src/components/QuranReader/ReadingView/index.tsx
src/components/QuranReader/TafsirView/TafsirBody.tsx
src/components/QuranReader/TranslationView/TranslationPage/index.tsx
src/components/QuranReader/hooks/useFetchTotalPages.ts
src/redux/defaultSettings/defaultSettings.ts
src/redux/slices/QuranReader/styles.ts
src/redux/types/QuranReaderStyles.ts

This PR fixes the issue of wrong verses being shown when selecting Indopak's 16-line Mushaf in the ReadingView e.g. `/4`.

Fix Indopak 16-line ReadingVIew wrongs verses issue

---

src/components/QuranReader/ReadingView/hooks/useScrollToVirtualizedVerse.ts
src/components/QuranReader/ReadingView/index.tsx

This PR fixes the issue when `startingVerse` exists in the url, `undefined` e.g. `/id/9?startingVerse=1`
| ----- |
|<img width="736" alt="Screen Shot 2022-02-24 at 16 48 31" src="https://user-images.githubusercontent.com/15169499/155500124-16a0c176-8727-4c05-9ed9-c4c4899fd1d7.png">|

Fix startingVerse undefined ref

---

src/components/dls/PopoverMenu/PopoverMenu.module.scss

Based on feedback from yusuf, increasing the touch area for popovermenu
Before
After

increase popover menu touch area

---

src/components/QuranReader/ReadingView/PageContainer.tsx
src/pages/page/[pageId].tsx

This PR fixes the issue of wrong page number and verses for 16-line Indopak Mushaf. e.g. [page 30](https://next.quran.com/id/page/30).
|![BEFORE](https://user-images.githubusercontent.com/15169499/155874650-1fac1156-26a1-4016-8300-d7fe3ae59dbb.png)|![AFTER](https://user-images.githubusercontent.com/15169499/155874647-db5910e5-acc8-4b80-b953-f4de84b5b1e3.png)|

Fix 16-line Indopak Mushaf wrong page

---

src/components/Verse/VerseActionAdvancedCopy/index.tsx

This PR adds the ability to close the Advanced Copy modal when Esc key is pressed to make it consistent with other modals.

Close AdvancedCopy Modal on Esc key pressed

---

src/components/Navbar/SearchDrawer/Header/index.tsx

Before
- clicking "search" on mobile keyboard does not close the keyboard
After
- clicking "search" on mobile close the keyboard
Based on yusuf's feedback

on mobile, dismiss keyboard when user click "return"

---

src/components/Navbar/Drawer/Drawer.module.scss
src/components/Navbar/Drawer/index.tsx

How to test
* go to next.quran.com
* go to al baqarah
* play audio
* open settings drawer
* wait until the page auto scroll
* the "close" icon will be hidden.
Now try on this PR preview

fix: settings drawer hidden when audio auto scroll

---

src/components/QuranReader/ReadingView/PageContainer.tsx

This PR fixes Reading View's 16-line Indopak Mushaf initial verses issue where the initial verses contain all the words of the verses of the first page while sometimes the first page in the actual Mushaf doesn't contain the entire verse but only part of it.
| Before | After | Path |
| ------ | ------ | ------ |
|<img width="480" alt="Screen Shot 2022-03-03 at 19 54 28" src="https://user-images.githubusercontent.com/15169499/156570679-cdc5cdcc-b6f2-428f-9fb8-8406b534d100.png">|<img width="527" alt="Screen Shot 2022-03-03 at 19 54 07" src="https://user-images.githubusercontent.com/15169499/156570660-1d1d8a66-e586-43d5-b671-d7de9360d391.png">|https://quran.com/bn/haji/25|
|<img width="510" alt="Screen Shot 2022-03-03 at 19 56 58" src="https://user-images.githubusercontent.com/15169499/1565706 …

Fix 16-line Indopak wrong initial verses

---

src/components/QuranReader/TafsirView/TafsirBody.tsx
src/components/QuranReader/TafsirView/TafsirVerseAction.tsx
src/pages/[chapterId]/[verseId]/tafsirs.tsx
src/pages/[chapterId]/tafsirs/[tafsirId].tsx

`useSWR` was always called when opening overflow verse actions menu. Even when don't click "Tafsir" yet. This PR fixed the issue

fix: unnecassary api call when opening overflow verse actions

---

src/components/Search/SearchResults/SearchResults.module.scss

minor ui update: add space in search result summary

---

src/components/Search/SearchResults/SearchResultItem.module.scss

minor ui update: visual hierarchies in search result

---

src/components/QuranReader/api.ts
src/utils/apiPaths.ts

This PR removes translations-related request params for the Reading View API since they are not used.
| ------ |
|<img width="1431" alt="Screen Shot 2022-03-09 at 11 40 14" src="https://user-images.githubusercontent.com/15169499/157373992-5b97ea99-1ceb-49ef-87cf-f442bc40c6a2.png">|

[Reading View] Remove translations API request params

---

src/styles/_utility.scss

This PR improve the line-height of each line in the Reading view on mobile.
|<img width="271" alt="Screen Shot 2022-03-10 at 17 34 41" src="https://user-images.githubusercontent.com/15169499/157644410-9d13c8b6-d352-4237-8a5a-9b422895a0cd.png">|<img width="266" alt="Screen Shot 2022-03-10 at 17 34 17" src="https://user-images.githubusercontent.com/15169499/157644395-e84668ca-7b8a-48ef-b954-8d82f186d0b4.png">|

Improve line height on mobile

---

src/components/QuranReader/ReadingView/index.tsx

This PR disables page navigation for the reading view when the font scale is above 5 since we no longer maintain the full-page view.

Disable page navigations when font scale > 5

---

next.config.js

This PR adds caching headers to images and icons that makes them cached for a week since they are almost immutable.

Update images and icons cache-control

---

src/components/QuranReader/TafsirView/TafsirVerseAction.tsx
src/components/QuranReader/TranslationView/QuranReflectButton.tsx
src/components/dls/ContentModal/ContentModal.tsx

When opening contentModal, the `fakeNavigate` function is called multiple times. Because the function is tied to react lifecycle via useEffect. This adds unnecessary complexity. 
`fakeNavigate` function should be triggered inside `onClick`, not on `render`.
Removing this handler from contentModal to avoid other complexity in the future
---
Here's a few problem that's already found 
It's called multiple times (more than what we need) when opening tafsir,
When it's called often enough, it breaks safari.

Remove url handler from ContentModal

---

locales/en/common.json
src/components/QuranReader/TafsirView/TafsirBody.tsx
src/components/QuranReader/TafsirView/TafsirGroupMessage.tsx
src/components/QuranReader/TafsirView/TafsirMessage/TafsirMessage.module.scss
src/components/QuranReader/TafsirView/TafsirMessage/index.tsx
src/components/QuranReader/TafsirView/TafsirView.module.scss

Based on user [feedback](https://feedback.quran.com/b/bugs/tafsir-dosent-always-load), this PR shows a message when the text of a Tafsir is empty instead of showing a skeleton which confuses people to think that the Tafsir text is about to be shown. An example on a Tafsir with empty text: https://quran.com/46:25/tafsirs/tafisr-fathul-majid-bn
|<img width="705" alt="Screen Shot 2022-03-15 at 19 36 09" src="https://user-images.githubusercontent.com/15169499/158378964-97f7d6f6-1140-4922-9949-1040a860bf47.png">|<img width="725" alt="Screen Shot 2022-03-15 at 19 36 06" src="https://user-images.githubusercontent.com/15169499/158378951-84c9f9f4-88a7-4dca-918c-324aef6a2e8c.png">|

Handle empty tafsir text

---

src/pages/reciters/[reciterId]/[chapterId].tsx

This PR adds support for slugs of a chapter of a specific reciter e.g. `/reciters/1/an-nas`. Before only the chapter Id was supported e.g. `/reciters/1/114`.

[SEO] Support reciter chapter slugs

---

src/pages/reciters/[reciterId]/index.tsx

This PR makes it possible to use the chapter ID to search for a chapter in the list of chapters of a specific reciter e.g. `/reciters/1`

Include chapterId in reciter chapters search

---

src/components/QuranReader/SidebarNavigation/SidebarNavigation.tsx
src/components/QuranReader/SidebarNavigation/SidebarNavigationSelections.tsx

This PR lazy loads the Juz, Surah and Page lists inside the sidebar navigation to 
1. Lower the initial bundle size.
2. Lower The number of elements in the DOM in the initial render.
3. Reduce the time the main thread is busy traversing the DOM tree.
|Screenshots|
| ------ |
|<img width="770" alt="Screen Shot 2022-03-19 at 10 29 53" src="https://user-images.githubusercontent.com/15169499/159105127-61e01bd0-d6d5-483a-8c7e-9924f0f86907.png">|

[Perf] Lazy-load sidebar navigation selection lists

---

src/utils/verse.ts

This PR makes sure all lodash modules are loaded on demand to reduce the bundle size. After this PR `node_modules` bundle size (GZipped) has gone down 35%. 
|<img width="477" alt="Screen Shot 2022-03-20 at 17 38 42" src="https://user-images.githubusercontent.com/15169499/159158991-4544e8f9-60b3-497e-960f-bbf40e65dcf3.png">|<img width="206" alt="Screen Shot 2022-03-20 at 17 39 27" src="https://user-images.githubusercontent.com/15169499/159158995-5913e641-883f-4961-b07c-a7dbed7c3c41.png">|
|<img width="466" alt="Screen Shot 2022-03-20 at 17 57 22" src="https://user-images.githubusercontent.com/15169499/159159030-94854934-7e66-4893-80f4-e8afbd64d538.png">|<img width="171" alt="Screen Shot 2022-03-20 at 17 57 15" …

[Perf] Import lodash module on demand

---

src/components/Navbar/SettingsDrawer/QuranFontSection.tsx

The font preview is now below the + and - button. So it prevent annoying layout shift

update quran font preview position

---

src/components/DeveloperUtility/FontAdjustment.tsx
src/components/Navbar/SettingsDrawer/TranslationSection.tsx
src/redux/slices/QuranReader/styles.ts
src/styles/_utility.scss

This PR increases the maximum translation font scale to 10 instead of 5.
|<img width="385" alt="Screen Shot 2022-03-21 at 12 12 16" src="https://user-images.githubusercontent.com/15169499/159208609-d21ff9cc-6707-4af8-bd88-934e82b126ac.png">|<img width="383" alt="Screen Shot 2022-03-21 at 12 12 01" src="https://user-images.githubusercontent.com/15169499/159208598-885cbf68-6b23-465d-b045-9f8e91be164d.png">|

Increase maximum translation font scales

---

next-sitemap.js

This PR lowers the number of records per sitemap file from 30K to 20K.
| ------ |
|<img width="940" alt="Screen Shot 2022-03-21 at 15 12 52" src="https://user-images.githubusercontent.com/15169499/159224587-58f08d99-12ef-419d-bf84-d5f4691315b5.png">|

Update sitemap number of recoreds per file

---

src/components/QuranReader/TranslationView/TranslationText/TranslationText.module.scss
src/components/Verse/VerseText.module.scss
src/styles/themes/_dark.scss

---
In Apple's safari reading mode , the text is also a bit transparent, and it feels sligtly more comfortable

lighter text color on dark mode

---

src/api.ts
src/components/QuranReader/TafsirView/TafsirBody.tsx
src/pages/[chapterId]/[verseId]/tafsirs.tsx
src/pages/[chapterId]/tafsirs/[tafsirId].tsx
src/utils/apiPaths.ts

SWR has this feature to simplify data loading process with nextjs https://swr.vercel.app/docs/with-nextjs
so instead of checking manually `shouldUseInitialTafsirData` we can leverage this SWR feature to simplify our logic

refactor tafsir data fetching: use useSWR SSR

---

package.json
yarn.lock

There seems to be an [issue](https://github.com/prettier/prettier/issues/12504) with Prettier `v2.6.0` so this PR downgrades the version back to `2.5.1`.
| ------ |
|<img width="898" alt="Screen Shot 2022-03-23 at 10 17 16" src="https://user-images.githubusercontent.com/15169499/159617268-eb97a182-26a1-4712-bbff-4721bc8d2f02.png">|

Downgrade prettier

---

src/components/AudioPlayer/AudioPlayer.module.scss
src/components/AudioPlayer/AudioPlayer.tsx
src/components/AudioPlayer/AudioPlayerBody/index.tsx
src/components/AudioPlayer/AudioPlayerSlider.module.scss
src/components/AudioPlayer/AudioPlayerSlider.tsx
src/components/GlobalScrollListener.tsx
src/redux/defaultSettings/defaultSettings.ts
src/redux/migrations.ts
src/redux/slices/AudioPlayer/persistConfig.ts
src/redux/slices/AudioPlayer/state.ts
src/redux/types/AudioState.ts

This PR update the code base to no longer use `isMobileMinimizedForScrolling` which was stlll being dispatch on every scroll up or down.

remove isMobileMinimizedForScrolling

---

src/components/Search/PreInput/index.tsx

This PR fixes the issue with chapters data not being available in `DataContext` when opening the Search drawer because `Navbar` is higher in the components tree than the `DataContext` provider since it belongs to `_app`.
| ------ | 
|<img width="964" alt="Screen Shot 2022-03-23 at 19 00 40" src="https://user-images.githubusercontent.com/15169499/159694763-74fefe75-f776-4404-9938-1192be7ba1f0.png">|

Fix search drawer missing context data exception

---

src/components/QuranReader/EndOfScrollingControls/ChapterControls.tsx

It's easier to parse the information when there's an image/icon.
If this PR is good, will add the icon to the other EndOfScrolling as well, (juz and page)

add next and prev icon to chaper's end of scrolling

---

src/components/Navbar/SearchDrawer/Header/Header.module.scss
src/components/Navbar/SearchDrawer/Header/index.tsx

**Note** : This PR has nothing to do with the RTL issue
1. on Google the "clear" or "x" button is always on the left side. It doesn't push the microphone icon to when it becomes visible
2. There's a tiny separator line to indicate that the the microphone and searchbox is separated

search drawer: add "clear" separator & switch position

---

src/components/Navbar/SettingsDrawer/TranslationSection.tsx

|<img width="745" alt="Screen Shot 2022-04-03 at 5 14 16 PM" src="https://user-images.githubusercontent.com/15169499/161434812-b6013a04-7238-4bfb-871e-64502f7a2817.png">|<img width="388" alt="Screen Shot 2022-04-03 at 5 07 33 PM" src="https://user-images.githubusercontent.com/15169499/161434767-fccd91c4-5fb8-41e9-8318-8953d6297e43.png">|

Handle when translation name is not in the response

---

src/components/AudioPlayer/AudioPlayer.module.scss
src/components/AudioPlayer/AudioPlayer.tsx

This PR adds loading indicator while the `AudioPlayerBody` component is being loaded.
|<img width="1440" alt="Screen Shot 2022-04-08 at 10 26 30 AM" src="https://user-images.githubusercontent.com/15169499/162397010-13dfc4bd-58d5-4c4a-a37a-32b95428fdfe.png">|<img width="1440" alt="Screen Shot 2022-04-08 at 10 26 18 AM" src="https://user-images.githubusercontent.com/15169499/162396999-9259c057-e006-4106-9a19-323b76da8520.png">|

Add audioPlayer lazy loading indicator

---

src/components/CommandBar/CommandsList/CommandList.module.scss

Fix command bar highlight ui

---

src/components/QuranReader/api.ts
src/pages/[chapterId]/[verseId]/index.tsx

This PR fixes [an issue](https://feedback.quran.com/bugs/p/al-araf-missing-verse-11) of missing verses of a range when the first Mushaf page of the range exceeds 10 verses and the user hasn't changed the default font. An example of the issue https://quran.com/36/1-27 or https://quran.com/7/1-87
1. Visit `36/1-27` or `/7/1-87`
2. All the verses should show correctly
|<img width="466" alt="Screen Shot 2022-04-11 at 11 25 19 AM" src="https://user-images.githubusercontent.com/15169499/162709314-d31ece41-a5c3-456b-8a78-4597e98731eb.png">|<img width="433" alt="Screen Shot 2022-04-11 at 11 26 41 AM" src="https://user-images.githubusercontent.com/15169499/162709290-e909d4d9-4898-4d71-a48b-6331694c0892.png">|

Fix Range missing verses

---

src/components/AudioPlayer/OverflowAudioPlayerActionsMenu.module.scss

Updated `OverflowAudioPlayActionsMenuBody`'s position for `smallerThanTablet` breakpoint
| ![image](https://user-images.githubusercontent.com/28780579/186915405-1269c3ad-329a-4320-8264-dcbf86dc25a3.png) |![image](https://user-images.githubusercontent.com/28780579/186915491-8d96bca2-5905-4ebe-8533-2e225d4f22a2.png) |

fix: overflowing reciters menu

---

src/components/Collection/CollectionDetailContainer/CollectionDetailContainer.tsx
src/components/dls/Spinner/Spinner.module.scss
src/components/dls/Spinner/Spinner.tsx

In a few place, spinner only shown for a split second. Almost useless, and quite distracting.
This PR add `shouldDelayVisibility` props to the Spinner. So that the spinner only shown when the loading is long enough

spinner, add props to delay visibility

---

src/xstate/actors/rangeCycle/rangeCycleMachine.ts

the root cause of this issue is that the `duration` data from API becomes negative `-`.
This PR is just a bandage

fix: verse delay not working

---

src/components/dls/QuranWord/QuranWord.module.scss
src/components/dls/Tooltip/Tooltip.module.scss

Addressing the issue: https://github.com/quran/quran.com-frontend-next/issues/1810
Increasing the max-width and wrapping content of tooltip.
One of the longest translation is: `"and those who seclude themselves for devotion and prayer"` (2:125) - see screenshot below
| ![Screenshot 2022-09-25 at 21 03 00](https://user-images.githubusercontent.com/31985946/192163110-f8b47f2b-7abd-4679-96ab-ac0cebbcce92.png) | ![Screenshot 2022-09-25 at 21 02 41](https://user-images.githubusercontent.com/31985946/192163112-6ccdd462-1dbd-4417-a94e-7c9c6b10d23b.png)|
|![Screenshot 2022-09-25 at 21 13 26](https://user-images.githubusercontent.com/31985946/192163329-5124fced-5cd8-4f1f-aabd-a107e857c5f1.png)|![Screenshot 2022-09-25 at 21 13 …

Bug-1810: Increasing max-width and wrapping content of tooltip

---

src/components/Navbar/Drawer/index.tsx

Fixes #1807 
When drawer triggers an action to fetch e.g. translation. the drawer is moved to the top on render with the nav on nav hidden. This will keep the nav visible on drawer open.
The issue is on both mobile and desktop. This PR fixes both.
|![bug-cropped-trimmed](https://user-images.githubusercontent.com/31985946/192151879-4cfa1ae5-92a3-4b17-80f4-fa7792a7955a.gif)|![final-bug-fixed](https://user-images.githubusercontent.com/31985946/192151882-98612edd-9354-4aae-bb21-fa47a7e843d4.gif)|
| <img width="387" alt="Screenshot 2022-09-25 at 16 46 54" src="https://user-images.githubusercontent.com/31985946/192152511-d938c239-5cb5-49a3-b29b-e4d739bd624c.png">|<img width="388" alt="Screenshot 2022-09-25 at 16 47 14" …

Making Nav bar visible on re-render with drawer open

---

src/components/Navbar/SettingsDrawer/TranslationSelectionBody.tsx
src/hooks/useRemoveQueryParam.ts

When user settings remove all translations, remove translations from query param in URI
When system wide translations are changed whilst on a Surah page a query param ?translations=... is added. Once the system wide translations is removed, the translations is not removed.

Remove translation query param when no translations

---

src/components/dls/Forms/Combobox/ComboboxItem/ComboboxItem.module.scss

fix: combobox empty message not readable

---

src/components/Navbar/SettingsDrawer/TafsirSection.module.scss
src/components/Navbar/SettingsDrawer/TafsirSection.tsx
src/components/Navbar/SettingsDrawer/TranslationSection.module.scss
src/components/Navbar/SettingsDrawer/TranslationSection.tsx

This PR resolves issue #1770. Skeleton of translation and tafsir sections in the setting drawer were rendering IDs inside the skeleton. I am guessing it was implemented like that previously in order to have the id texts as a placeholder. 
This PR resolves the issue by removing ID renders and adding a style to the skeletons like it's done in other places like [LanguageAndTafsirSelection](https://github.com/quran/quran.com-frontend-next/blob/master/src/components/QuranReader/TafsirView/LanguageAndTafsirSelection.tsx#L32)
I was not able to reproduce the issue on Chrome 106.0 Mac OS, but I was able to replicate it in Safari 16.0. In order to test this issue, you can replace `DataFetcher` block (line 139) with `translationLoading()` on …

Fix: Loading skeleton showing text on setting drawer

---

src/components/AudioPlayer/RepeatAudioModal/RepeatAudioModal.tsx

Previously play range go from 3 to infinity and now it will go from 8 to infinity. Changing infinityThreshold from 3 to 8.
Fix issue #1647 
| [
] | [
] |

[Feat]:Extend repeat ranges for audio repeat settings #1647

---

src/utils/navigation.ts
src/utils/verse.ts
types/SearchNavigationResult.ts

This PR handles when the search API returns `range` type. e.g. when typing "3:5-7".

Handle range navigation results

---

src/components/DisableAnimationsUntilHydration.tsx
src/components/GlobalListeners.tsx
src/components/GlobalPersistGateHydrationListener.tsx
src/pages/_app.tsx
src/redux/Provider.tsx
src/redux/slices/persistGateHydration.ts
src/redux/store.ts
src/redux/types/SliceName.ts
src/styles/global.scss
src/utils/isClient.ts
types/Window.ts

Previously we had redux persist gate logic that would cause all the DOM elements to be unmounted on initial page load during the redux-persist hydration, and mounted again right after. 
This was caused by the following piece of code: 
I've modified the code to use a single dom tree for both the hydrated and non-hydrated states. Redux uses the non persist initial state, and then dispatches a `REHYDRATE` event to populate the state. With this approach, a bunch of animations would happen on initial load (because the state is modified). I added a global utility that prevents all animations until the hydration is complete.

Fix persist gate double mounting

---

locales/en/home.json
src/components/chapters/JuzView.module.scss
src/components/chapters/JuzView.tsx

In the Juz view it wasn't obvious what action the user needs to take to read a full juz. There was an interaction masked by a hover effect. Added a "Read Juz" button to improve discoverability. 
| <img width="375" alt="image" src="https://user-images.githubusercontent.com/11590314/209964493-8b518649-73de-4d98-9332-199b78d1c9d9.png"> | <img width="375" alt="image" src="https://user-images.githubusercontent.com/11590314/209964644-182e59a6-f56b-4391-a8e6-e00ac061cb35.png"> |

Improve the Read Juz discoverability 

---

package.json
yarn.lock

Since we're upgrading to react v18, there are some [type-conflicts with SWR v1.2](https://github.com/vercel/swr/pull/1913). This PR upgrades SWR to v2.

Upgrade to swr v2

---

src/components/Navbar/NavigationDrawer/LinkContainer.tsx
src/components/Navbar/SearchDrawer/AdvancedSearchLink.tsx
src/components/QuranReader/ReadingView/PageFooter.tsx
src/components/Search/SearchResults/SearchResultItem.tsx
src/components/Search/SearchResults/index.tsx
src/components/dls/Link/Link.tsx

Next.js v13 introduces a [new behavior](https://nextjs.org/docs/upgrading#link-component) for `next/link`. There is no need for a child `<a>` anymore. This PR migrates all occurrences of `next/link` to the new behavior.

Migrate to new next/link

---

src/components/dls/KeyboardInput/MetaShortcut.tsx
src/components/dls/KeyboardInput/index.tsx

This line causes the text to change on the client because `isMacOs` defaults to `false` on the server.
```tsx
// src/components/dls/KeyboardInput/index.tsx
{meta && (<span>{isMacOs ? '⌘' : 'ctrl'}</span>)}
```
This PR fixes this issue by lazy loading the shortcut on the client only.
The error:

load shortcut on client only

---

next.config.js
package.json
yarn.lock

Next v13 was showing warnings due to invalid config:
This PR solves this issue by removing `next-compose-plugins` and writing custom logic for plugins:
```js
let finalConfig = { ...config };
const plugins = [
// ...
];
plugins.forEach((plugin) => {
finalConfig = plugin(finalConfig);
});
```

Remove next-compose-plugins and write custom logic for plugins

---

src/components/dls/Footer/Footer.module.scss
src/components/dls/Footer/Links.tsx

We currently return an empty fragment in the footer's links while loading localized slugs. However, this causes a huge CLS and is not ideal since only one section (Popular Links) requires the localized slugs.
```tsx
// src/components/dls/Footer/Links.tsx
const chaptersData = useGetChaptersData(lang);
if (!chaptersData) {
return <></>;
}
```
---
This PR solves this issue by showing a disabled `<p>` with the title as a placeholder until we load the slugs. Preview:
---
| ------ | ----- |
| <img width="400" alt="image" src="https://user-images.githubusercontent.com/58295120/212475980-9305755f-3520-445c-866b-732c42cf1956.png"> <img width="400" alt="image" src="https://user-images.githubusercontent.com/58295120/212475965-adfd8180-0e11-4446-88f5-42ccbd5b2247.png"> | <img …

Show links as <p> tags in footer while loading

---

src/components/QuranReader/QuranReader.module.scss
src/components/QuranReader/TranslationView/TranslationView.module.scss
src/components/QuranReader/TranslationView/index.tsx

Currently, the global footer causes CLS issues on the TranslationView and ReadingView due to [an issue](https://github.com/petyosi/react-virtuoso/issues/760) caused by `react-virtuoso`. This PR fixed this issue by setting a min-height to the TranslationView and ReadingView containers.
| ![image](https://user-images.githubusercontent.com/58295120/213972630-6be45012-2a31-435d-9cf1-7cd7e2bb7a03.png) | ![image](https://user-images.githubusercontent.com/58295120/213972653-fee09167-78f8-47ff-b172-f1c6a25b051a.png) |
| ![image](https://user-images.githubusercontent.com/58295120/213972818-588f61b6-0aca-4179-b020-b87cf449800f.png) | ![image](https://user-images.githubusercontent.com/58295120/213972745-41f1b7c1-6546-4855-b …

Fix chapter page CLS

---

src/components/QuranReader/QuranReaderView.tsx
src/components/QuranReader/TranslationView/TranslationPage/TranslationPageVerse.tsx
src/components/QuranReader/TranslationView/TranslationPage/index.tsx
src/components/QuranReader/TranslationView/index.tsx
src/components/QuranReader/contexts/ReadingProgressContext.tsx
src/components/QuranReader/hooks/useSyncReadingProgress.ts
src/components/QuranReader/index.tsx

This PR solves:
1. Reading time was being calculated even when you were not on the same tab.
2.  Last verse of the translation view was not being tracked.

Fix reading goals progress tracking

---

src/components/TarteelVoiceSearch/BodyContainer/SearchResults.tsx

Currently, an exception will throw if you open up the voice search and say "Allah". This is because there are a LOT of verse keys returned by tarteel, and when we try to use the QDC filter API, the request fails. 
This PR fixed this issue by taking only the first 10 verse keys.

Limit tarteel results to 10

---

src/components/dls/QuranWord/TajweedWordImage.module.scss

#1946 
The font size for the Tajweed style was not updating on Firefox. Behind the scenes, the font for Tajweed is actually a png image retrieved from a CDN URL and then the size is adjusted with the CSS `zoom` property. However, the `zoom` property is [not supported](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom) by Firefox, hence why the font size adjustment was not working.
Each png image has a fixed height of `100px`, therefore I've changed the CSS `zoom` property to use `height` instead and have calculated the pixel values using the zoom values. Using this method works on all browsers including Firefox.
I did not use `transform: scale()` as this does not give the same result as zoom and causes further complications.
1. Using Firefox, [open a Surah](http://localhost:3000/3)
2. …

fix: 🐛 changed tajweed word imgs to use height css property

---

.vscode/settings.json
src/components/chapters/RevelationOrderView.tsx

Bismillah
#1957 
The Surah icons were not updating when changing the sorting order in the 'Revelation Order' tab. The incorrect index was being passed into the `SurahPreviewRow` component which is responsible for getting the chapter icon.
This PR fixes the issue by using the correct value for the chapter id.
I have added additional config in the `settings.json` file which is being used by the [i18n Ally VS Code extension](https://marketplace.visualstudio.com/items?itemName=lokalise.i18n-ally). This extension makes using i18n easier.
If you would like me to remove this config from this PR, please let me know.
1. Go to [localhost](http://localhost:3000/) and click on the 'Revelation Order' tab
2. Check the Arabic chapter icons are mapping correctly to the Surah
3. Change the sort by order …

fix: 🐛 Surah icon order after sorting in Revelation Order tab

---

src/utils/array.ts
src/utils/wordByWord.test.ts

- replace array includes with map look-up, which improves time complexity from O(n*m) to O(n+m)
this is a fiddle with the test
https://jsfiddle.net/mahmoud_alragabi/v3wL0ob4/
and here is a screenshot of the performance improvement almost to 3x

Improve performance for mergeTwoArraysUniquely

---

src/components/Profile/DeleteAccountButton.tsx

The text in the delete profile modal was broken due to wrong localization strings.

Fix delete profile modal text

---

src/components/QuranReader/TranslationView/hooks/useScrollToVirtualizedVerse.ts

Currently, when you click on a lot of verses quickly in the sidebar navigation, you'll be scrolled to all of them respectively due to the `setTimeout` for each click. This PR clears the preview `setTimeout` before setting a new one.

Clear scroll timeout when setting a new one

---

src/components/HomePage/ReadingStreak/index.tsx
src/components/QuranReader/ReadingView/index.tsx
src/components/QuranReader/TranslationView/index.tsx
src/hooks/auth/useGetStreakWithMetadata.ts

This PR prevents an extra HTTP request that gets triggered when reading to refresh the streak data. Instead of using Virtuoso's Footer, we add `1` to the list count and we render the footer as the last element.

Render Quran Reader footer using virtuoso

---

src/components/QuranReader/SidebarNavigation/SurahList.tsx
src/components/QuranReader/SidebarNavigation/VerseList.tsx

This PR fixes 2 problems:
1. When you search for a verse in the sidebar and navigate to a different chapter, the input is not being reset and the verse list is reflecting the old chapter:
---
2.  When you navigate to a different chapter, the surah list was not being updated to reflect the new state:

Reset sidebar navigation inputs and sync their state

---

src/components/Search/SearchResults/SearchResultItem.tsx
src/components/dls/Pagination/Pagination.tsx
src/pages/search.tsx

Salam Alaikoum,
This PR is an attempt to fix https://github.com/quran/quran.com-frontend-next/issues/1988
1. Search for any word eg.. `ta` on home page search bar
2. Click on the first search result option
3. On the search page you should be able to change the search input, remove, backspace, etc..
Before:
https://github.com/quran/quran.com-frontend-next/assets/26346408/1ba04708-a0c3-4bf4-9fe4-c4bcd01dc61a
After:
https://github.com/quran/quran.com-frontend-next/assets/26346408/60c0d752-0c1d-40a2-91d1-b0b51f101e6a

fix: #1988 tightened router based searchQuery state update block

---

src/components/Collection/SaveToCollectionModal/SaveToCollectionModal.tsx

This PR changes the type of the collections list from normal `Modal` to `ContentModal` to make it scrollable for when there are a lot of collections. Fixes [issue](https://feedback.quran.com/bugs/p/collections-buggy) reported here.
|![Jul-03-2023 19-48-40](https://github.com/quran/quran.com-frontend-next/assets/15169499/d09382e3-b1c3-4921-9100-e7c840a5dcc8)|![Jul-03-2023 19-44-57](https://github.com/quran/quran.com-frontend-next/assets/15169499/cef612b1-1abe-48c8-99e8-be9e8f56fce9)|

Scrollable collections list modal

---

src/components/dls/PopoverMenu/PopoverMenu.module.scss

This bug was caused due to that not all icons have pre-defined dimensions nor a browser default. This PR fixes this issue by setting width and height for popover item's SVG.
| ![CleanShot 2023-07-07 at 13 11 38@2x](https://github.com/quran/quran.com-frontend-next/assets/58295120/578ce92e-f917-4b24-9197-9068d037d7bf) | ![CleanShot 2023-07-07 at 13 10 15@2x](https://github.com/quran/quran.com-frontend-next/assets/58295120/1174549e-f8fb-4846-badc-1577985b9686) |

Fix popover menu SVGs

---

src/components/HomePage/QuickLinks/QuickLinks.module.scss

This PR change keep the scrollbar hidden when there are few items in the quick links container in Firefox.
| ![before](https://github.com/quran/quran.com-frontend-next/assets/83069563/c9a0d8d1-546f-46eb-a8f7-85b6ae966f22) | ![after](https://github.com/quran/quran.com-frontend-next/assets/83069563/c69b03b8-b4c5-4f4d-8ef7-e04859236023) |

Scrollbar: Hide when few items in firefox

---

src/components/QuranReader/TranslationView/TranslationText/FootnoteText.tsx
src/components/QuranReader/TranslationView/TranslationText/index.tsx

Feature: #2004
footnote number identifier
Every footnote should when clicked do the following:
- Should show the current clicked footnote number 
- Should also show the current clicked sub-footnote number if present
1. Test footnote is number displaying correctly with the "footnote" text in any Surah
2. Test sub-footnote is number is correctly displaying in Bridge's Foundation translation (ex: Surah 30, Verse 11)
**| Before:**
**| After:**

Added footnote number identifier: Feature #2004

---

src/utils/auth/preferencesMapper.ts

This PR sends the locale in default settings as:
```json
{
"language": { "language": "en" },
// ...
}
```
rather than:
```json
{
"language": "en",
// ...
}
```

Send locale settings as object

---

src/components/GlobalScrollListener.tsx
src/components/QuranReader/ContextMenu.module.scss
src/components/QuranReader/ContextMenu.tsx
src/components/QuranReader/ReadingPreferenceSwitcher/ReadingPreference.module.scss
src/components/QuranReader/ReadingPreferenceSwitcher/ReadingPreferenceOption.tsx
src/components/QuranReader/ReadingPreferenceSwitcher/ReadingPreferenceSwitcher.module.scss
src/components/QuranReader/ReadingPreferenceSwitcher/index.tsx
src/components/QuranReader/SidebarNavigation/SidebarNavigation.module.scss
src/components/dls/Switch/Switch.module.scss
src/components/dls/Switch/Switch.tsx
src/redux/slices/QuranReader/contextMenu.ts

Attempt to fix #1924 . Add reading preference switch to header.
- Show preference toggle in header if the default one disappears
- Remember the verse when switching
- Adjusts sizing for desktop / mobile devices
- Hides Juz / Hizb info on the header on mobile once user has scrolled past the beginning of the page (noticed otherwise the header occupies more than 1/3 of the screen
| ![Before - desktop](https://github.com/quran/quran.com-frontend-next/assets/32406853/fbc91b27-6d1c-4e17-a50e-34bc9a12506a) | ![After - desktop](https://github.com/quran/quran.com-frontend-next/assets/32406853/f1c57dbb-8f1f-415d-a83c-5ae18aebee48) |
| ![Before - mobile](https://github.com/quran/quran.com-frontend-next/assets/32406853/29071169-7211-4a26-8cd1-429241f31e59) | …

Add reading preference switch to navbar

---

src/components/QuranReader/ReadingView/PageContainer.tsx
src/components/QuranReader/ReadingView/index.tsx
src/components/QuranReader/TranslationView/TranslationViewVerse/hooks/useDedupedFetchVerse.ts
src/hooks/useIsUsingDefaultSettings.tsx
src/redux/slices/QuranReader/styles.ts

This PR fixes #1960 along with other reported issues on [feedback.quran.com](https://feedback.quran.com/bugs/p/the-quranic-text-appears-as-gibberish).
This issue is caused due to how we detect if the user is using the default settings for their language in order to use the first 9 verses passed by the server (`initialData`). Currently, `isUsingDefaultFont` for an example is a piece of state and not a computed property. This resulted in a wrong value when the user is defaulted to a language (i.e. english), and then changes to another language with different settings (i.e. bengali). 
This PR adds a new hook (`useIsUsingDefaultSettings`) that manually checks is default font settings match the current settings.

Fix Quran reader when switching languages

---

src/components/QuranReader/TafsirView/TafsirBody.tsx
src/utils/tafsir.ts

This PR auto-selects first Tafsir when the language changes to solve the issue when the same Tafsir name exists in the old and new languages and old Tafisr still shows.
| ![after](https://github.com/quran/quran.com-frontend-next/assets/15169499/47ba9487-da34-4d1d-98cc-f5a22f885244) | ![before](https://github.com/quran/quran.com-frontend-next/assets/15169499/c4114dbb-a8d7-4a5b-bb54-405e4be69377) |

Select first Tafsir on language change

---

src/components/QuranReader/TranslationView/TranslationViewVerse/hooks/useDedupedFetchVerse.ts

This PR fixes a bug caused in the translations view where the default translation would still show up even if the user specified no translations in their preferences.

Force-remove translations depending on user preferences

---

src/components/Login/EmailLogin.tsx
src/components/Login/LoginContainer.tsx
src/utils/auth/apiPaths.ts

This PR adds the ability to pass a redirect (`r`) query param for magic login, and the user will be redirected to it after clicking the link.

Add redirect param to login page

---

src/components/Navbar/SettingsDrawer/TranslationSelectionBody.tsx

Our Backend API returns list of translations sorted by priority, but FE overrides this sorting by sorting them alphabetically. This PR removes sorting done on FE.

Remove FE sorting translations list

---

src/components/QuranReader/TafsirView/TafsirBody.tsx

This PR disables the browser's translation for tafsir content which was causing in-accurate content not intended by the author.

Disable tafsir browser translation

---

src/components/QuranReader/TranslationView/TranslationViewVerse/hooks/useDedupedFetchVerse.ts
src/hooks/useIsUsingDefaultSettings.tsx

The first couple of verses ( loaded in `initialData`) were not showing user selected translations if they're not present in the URL params.
This bug was caused by `useIsUsingDefaultSettings` only checking for translations in the URL params and not in the user settings as well.

Fix translations

---

src/components/Navbar/NavbarBody/index.tsx

This PR temporarily disables sending un-necessary get user feature flags requests to our backend since in-app notifications are not used. Will be reverted back when they are.

Temporarily disable sending feature flags requests

---

src/components/Auth/RedirectToLoginPage.tsx
src/components/Auth/withAuth.tsx
src/pages/collections/all/index.tsx
src/pages/learning-plans/[slug]/lessons/[lessonSlugOrId]/index.tsx
src/pages/my-learning-plans/index.tsx
src/pages/notes-and-reflections/index.tsx
src/pages/profile.tsx
src/pages/reading-goal/index.tsx
src/pages/reading-goal/progress.tsx

Currently, we are using `useRequireAuth` hook as a way to redirect to login page when a non-logged in user is trying to access authenticated components. But issue is at least 1 request is sent to backend that fails while Frontend already knows the user is not logged in. So This PR is introducing a Higher-Order-Component `withAuth` that will not render authenticated components except when the user is logged in, otherwise redirects the user to login page.

Add hoc to redirect to login page

---

src/components/Auth/RedirectToLoginPage.tsx
src/components/Course/CourseDetails/StatusHeader/index.tsx
src/components/Course/CourseDetails/Tabs/Syllabus/index.tsx
src/components/HomePage/QuranGrowthJourneySection/CallToActionButtons/QuranGoalsButtons.tsx
src/components/HomePage/QuranGrowthJourneySection/CollapsibleSection/QuranReadingGoals/StreakIntroductionWidget.tsx
src/components/Login/LoginContainer.tsx
src/components/Login/SocialLogin.tsx
src/components/Navbar/NavbarBody/ProfileAvatarButton.tsx
src/components/Verse/Notes/index.tsx
src/pages/ramadan-activities/index.tsx
src/utils/auth/apiPaths.ts
src/utils/navigation.ts

This PR redirects user to the current location after logging in.

Redirect to current page after logging in

---

src/components/Navbar/Navbar.module.scss
src/components/Navbar/Navbar.tsx
src/components/QuranReader/EndOfScrollingControls/index.tsx
src/components/QuranReader/SidebarNavigation/SidebarNavigation.module.scss
src/components/QuranReader/hooks/useSyncReadingProgress.ts
src/pages/_app.tsx
src/pages/index.module.scss
src/pages/index.tsx

This PR reverts back Ramadan-related changes.

Revert Ramadan 2024 changes

---

src/components/Verses/BookmarkPill.module.scss
src/components/Verses/RecentReadingSessionsList/ReadingSessionPill/ReadingSessionPill.module.scss
src/components/Verses/RecentReadingSessionsList/ReadingSessionPill/index.tsx

This PR updates bookmarks and reading session pills in the homepage to make them smaller and not look like call-to-action buttons.
|<img width="1445" alt="Screenshot 2024-04-14 at 2 03 07 PM" src="https://github.com/quran/quran.com-frontend-next/assets/15169499/3fb6c48f-84cb-4385-bc06-309e2709bfcc">|<img width="1280" alt="Screenshot 2024-04-14 at 2 02 53 PM" src="https://github.com/quran/quran.com-frontend-next/assets/15169499/df520c2d-af5d-4d93-9b3e-9389eb9c381c">|

Change bookmarks and reading sessions buttons UI

---

src/components/Onboarding/OnboardingProvider.tsx
src/pages/_app.tsx

This PR fixes an issue that was preventing the server from rendering the HTML correctly resulting in missing all meta tags including preview links etc by only loading `Joyride` package on the client side.
`curl "https://localhost:3000/1"` Before vs after:

Only allow Joyride on client side

---

src/components/QuranReader/TranslationView/hooks/useGetVersesCount.ts
src/components/QuranReader/TranslationView/index.tsx

Fixes  #QF-352
Updated translation view initial data with the API data.
I have tested the Quran reader, in both translation view and reader view, in different Mushaf settings like the Madani and Idopack in different routes, the following are some of which:
- https://quran.com/rub/1
- https://quran.com/1:1
- https://quran.com/1:1-2:20
- https://quran.com/1/1
- https://quran.com/14
- https://quran.com/hizb/30
| ![Capture-2024-05-13-112821](https://github.com/quran/quran.com-frontend-next/assets/8735775/4ad95087-4193-4825-b6ad-bb88fbeb2191) | ![Capture-2024-05-13-112912](https://github.com/quran/quran.com-frontend-next/assets/8735775/1c24e461-c03b-4ebf-b0a9-f484c678fcad) |

QF-352: Update translation view initial data with the api data

---

src/pages/page/[pageId].tsx
src/utils/page.ts
src/utils/validator.ts

Fixes  #QF-369
Fixes `page/[pageId]` when `pageId` is greater than 604
I have tested the Quran reader, in different Mushaf settings like the Madani and Indopack in different routes from 604 to 610.
| ![Quran_com](https://github.com/quran/quran.com-frontend-next/assets/8735775/fafa201e-6c29-4b9c-b967-ef8be8cb60da) | ![localhost](https://github.com/quran/quran.com-frontend-next/assets/8735775/4c45b0d2-7225-4192-bfa1-d9f6569ef829) |

QF-369: fix pages routes with pageId greater than 604

---

src/components/ReadingGoal/UpdateReadingGoalModal/index.tsx
src/components/ReadingGoalPage/index.tsx
src/components/ReadingGoalPage/utils/validator.ts
src/pages/page/[pageId].tsx
src/utils/validator.ts

Fixes #QF-433
In creating or updating a goal the button will be disabled if the page number is outside the range of the selected Mushaf settings 
I created and updated a goal using different Mushaf settings and the button is disabled when I type a page number that is greater than the Mushaf pages count:
- Indopak 15 lines
- Indopak 16 lines
- Uthmani

validate page id by the selected mushaf id

---

src/components/Auth/withAuth.tsx

Fixes #QF-440
This PR fixes issue with pages wrapped with HOC `withAuth` that causes them to be blank when accessed directly.
1. Open your [Your Progress](https://quran.com/reading-goal/progress) page directly or open it from user dropdown then refresh the page.
2. The page should be rendered as expected.
| <img width="1728" alt="cce7bc77-08ca-41e9-84cd-a6a03a2a5c23" src="https://github.com/quran/quran.com-frontend-next/assets/15169499/50773889-2be4-419b-998f-947e72f5e450"> | <img width="1724" alt="Screenshot 2024-05-18 at 11 09 40 AM" src="https://github.com/quran/quran.com-frontend-next/assets/15169499/095a4436-c835-47cc-ba6b-8b509c24d4b0"> |

Fix withAuth

---

src/redux/migrations.ts
src/redux/store.ts

Fixes #482
Update redux persist migrations to overwrite `tajweed` quran font to `tajweed_v4`.
I have checked the local storage and redux devtools to make sure that the `quranFont` property is set to the newer version but still showing the old version if I selected the `tajweed` mushaf from the settings.

migrate tajweed mushaf to the latest version

---

src/api.ts
src/components/Navbar/SettingsDrawer/WordByWordSection.tsx
src/utils/apiPaths.ts
types/ApiResponses.ts
types/AvailableWordByWordTranslation.ts

Temporarily remove wbw translations

---

src/components/QuranReader/hooks/useFetchPageVerses.ts
src/components/QuranReader/hooks/useFetchPagesLookup.ts
src/pages/page/[pageId].tsx
src/pages/page/hooks/useGetPageVersesResponse.ts
src/pages/page/utils/getPageVersesParams.ts
src/pages/page/utils/getQuranReaderData.ts

Fixes #QF-469
Fetch page's verses data on the client to specify the select mushaf ID instead of always using the default mushaf ID which is Uthmani.
This has been tested on chrome with different pages following this route: `/page/[pageId]` using Indopak, 15 lines, translation mode.
| ![Screenshot 2024-06-09 at 12 12 54 PM](https://github.com/quran/quran.com-frontend-next/assets/8735775/1524b4ee-ecc9-4121-b7ab-41a3aff36a1b) | ![Screenshot 2024-06-09 at 12 13 08 PM](https://github.com/quran/quran.com-frontend-next/assets/8735775/50e7f0cd-9f91-4089-9def-9d3ec85f9dc9) |

Fix indopak translation mode missing ayahs

---

src/components/ReadingGoal/ReadingGoalInput/index.tsx
src/components/dls/Forms/Input/index.tsx

Fixes #QF-470
prevent decimal values on create/edit goal input and show numeric keyboard on mobiles.
This has been tested on chrome.

prevent decimal and show numberic input on mobile

---

src/components/MediaMaker/Content/index.tsx

Fixes #QF-1056
This PR disables browser's auto-translating content of the media generator.

QF-1056 disable auto-translate for media generator content

---

src/api.ts
src/pages/auth.tsx
src/utils/api.ts
src/utils/apiPaths.ts
src/utils/auth/api.ts
src/utils/build.ts
src/utils/url.ts

Fixes #QF-1165 and resolve other build and redirect issues

[QF-1165]: resolves the build and redirect issue

---

src/pages/auth.tsx

Fixes #[QF-1164] #[QF-1166] #[QF-1167]
This PR resolves issue of login and redirection after login
| [Safari](https://jam.dev/c/5fb1b4f5-bd25-4bb7-bfa0-01850acffbf0) | [Chrome](https://jam.dev/c/5ab41ea3-cb9b-447d-9715-ced36029cf89) |
[QF-1164]: https://quranfoundation.atlassian.net/browse/QF-1164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[QF-1167]: https://quranfoundation.atlassian.net/browse/QF-1167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[QF-1166]: https://quranfoundation.atlassian.net/browse/QF-1166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: base url for auth page issue

---

src/components/Navbar/SettingsDrawer/TranslationSection.tsx

Fixes #QF-1127
The PR fixes the issue of undefined in translations list when one selected translation gets un-approved.

fix: fixed undefined issue for unapproved translations

---

src/components/dls/Footer/TitleAndDescription.tsx

QF-1105 remove hiring footer section

---

src/components/dls/QuranWord/QuranWord.tsx

Fixes #QF-1427
This PR always enables Ayah popover for reading view.

Always enable Ayah menu for reading view

---

src/components/Navbar/SearchDrawer/Footer/Footer.module.scss
src/components/Navbar/SearchDrawer/Header/Header.module.scss
src/components/Navbar/SearchDrawer/Header/index.tsx
src/components/Navbar/SearchDrawer/SearchDrawer.tsx
src/components/Search/CommandBar/CommandsList/index.tsx
src/components/Search/SearchBodyContainer.tsx
src/components/Search/SearchInput/SearchInput.module.scss
src/components/Search/SearchInput/index.tsx
src/components/Search/SearchResults/index.tsx
src/utils/navigation.ts

Search UI updates

---

locales/en/reading-goal.json

This PR addresses the issue where HTML tags were being displayed as plain text instead of being rendered properly in the UI. The fix ensures that HTML content is parsed and rendered correctly.
**Fixes #2332**
The issue occurred because HTML tags like `<p>` and `<span>` were not being interpreted correctly, leading to raw HTML being displayed as text in the UI. This PR resolves the problem by ensuring that the component properly parses and renders HTML content.
- Verified that HTML tags are rendered correctly in the UI.
- Conducted manual testing to ensure no regressions in other parts of the application.
- Added unit tests to cover the fix and ensure future stability.
| Before| After|
| --- | ---|
|<img width="621" alt="image" src="https://github.com/user-attachments/assets/bd50931f-962a-4 …

Fix: HTML tags rendering as text in UI #2332

---

src/components/QuranReader/TranslationView/TranslationText/FootnoteText.tsx
src/components/Verse/AdvancedCopy/utils/getTextCopy.ts
src/utils/string.test.ts
src/utils/string.ts

Ayah feferences in footnotes for most translations are not links 
Closes #QF-2194
Client-side regex to find references and convert them to a href
Different footnotes to test with specific edge cases: 
http://local.quran.com/2/37 ( Adam and Eve were inspired to say is mentioned in 7:23 )
http://local.quran.com/2/43 ( Islāmic community (see 9:60) required,
The alms-tax (zakâh) is the payment of 2.5% of someone’s savings only if the amount is equivalent to or greater than 85 g of gold, if that amount remains untouched for a whole Islamic year—around 355 days.)
http://local.quran.com/2/62
After the coming of Prophet Muḥammad (ﷺ) no religion other than Islām is acceptable to Allāh, as stated in 3:85.
[ (V.2:62) A past nation used to live in Mûsal (Iraq) and say Lâ ilâha illallâh (none has the …

Make ayah references in footnotes urls

---

src/components/Navbar/SettingsDrawer/ResetButton.tsx
src/components/Navbar/SettingsDrawer/WordByWordSection.tsx
src/hooks/auth/usePersistPreferenceGroup.ts
src/utils/auth/api.ts

Closes [#QF-2580](https://quranfoundation.atlassian.net/browse/QF-2580) 
This PR fixes multiple issues related to calling preferences APIs: 
* If there is an error with API call to update wordByWord preferences, Frontend does not show the error toast.
* If there is an error with reset settings API call, Frontend shows success toast instead.
* If there is an issue with API call to update wbw locale (e.g. selecting French), toast disappears instantly due to changing url params.

Fix preferences APIs error handling

---

src/redux/migrations.ts

Closes: [QF-2899](https://quranfoundation.atlassian.net/browse/QF-2899)
[QF-2899]: https://quranfoundation.atlassian.net/browse/QF-2899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: initialize bookmarkedPages as empty object in state migration
