quran/quran.com-frontend-next

.eslintrc.yml, src/api.ts, src/components/dls/Tabs/Tabs.tsx
One example of how to accomplish #21 in the current setup.
Refs #18 since this accomplishes a part of the pieces we wanted to break out.
Closes #21
=> Add prettier/prettier rules to .eslintrc.yml

.github/workflows/test.yml
=> Add github action for running tests

package.json, yarn.lock
Fixes https://github.com/quran/quran.com-frontend-next/issues/20
cc @nabeel-
=> Add husky & lint-staged

src/styles/GlobalStyles.ts
=> ayat highlight fix

.github/workflows/build-storybook.yml
@Anasss added this. Can we have a longer term solution for this? It's breaking CI on master atm
=> Allow empty for storybook deployment

package.json, public/sitemap.xml, sitemap-generator.js, yarn.lock
Fixes https://github.com/quran/quran.com-frontend-next/issues/43
=> Setup sitemap generator and xml

.github/workflows/build-storybook.yml
This is a follow-up to #48 and #28
we will skip commit when there are no changes
=> Fix storybook deployment

.github/workflows/pull_request_template.md
=> Create a pull request Github template

.github/workflows/build-storybook.yml, .gitignore, .storybook/main.js, .storybook/preview.js, package.json, src/components/dls/Pill/Pill.tsx, src/styles/GlobalStyles.ts, yarn.lock
Add chromatic for storybook
https://www.chromatic.com/library?appId=5efe7c590819e2002223f873
=> Add chromatic

src/components/QuranReader/PageView/Line.tsx, src/components/QuranReader/PageView/Page.tsx, src/components/QuranReader/PageView/groupLinesByVerses.ts, src/components/QuranReader/PageView/groupPagesByVerses.ts, src/components/QuranReader/PageView/index.tsx
- Created a `Page` component to be able to split the reading mode and label different pages.
- Memoized the following functions for increased performance:
- Line component
- Page component
- PageView component
- groupLinesByVerses
- groupPageByVerses
Ran the PageView with Surat al-Baqarah and scrolled through it
- All the content renders properly
- The verses are split by page
- I felt an increase in performance, but it could be a placebo for adding memoization
=> Create the Page component and Memoize function calls

src/pages_/_document.tsx
Replace the `<html>` component with the Next 10 `<HTML>` for AMP support and internationalized routing (follow-up) 
Got minor lighthouse improvements 
| ![image](https://user-images.githubusercontent.com/11590314/97810154-1f2fae00-1c72-11eb-851c-e4b6dfff308c.png) | ![image](https://user-images.githubusercontent.com/11590314/97810161-29ea4300-1c72-11eb-9d0f-7a6e2d4a8fa4.png)|
=> Use the Next HTML component

package.json, yarn.lock
=> upgrade to next 10.0.5

src/components/developerUtility/FontAdjustment.tsx, src/components/developerUtility/ReadingViewAdjustment.tsx, src/components/developerUtility/index.tsx, src/pages_/_app.tsx, src/redux/slices/QuranReader/styles.ts, src/utils/environment.ts
Added a set of developer utility tools that are useful for testing locally and on staging environments. This tool will be expanded upon over time.
Modified the font size, style, translation reading mode. All modes toggle as expected.
=> Add developer utilities

src/components/chapters/ChapterBlock.tsx, src/components/chapters/ChapterIcon.tsx, src/components/dls/Cards/Card.tsx, src/components/dls/Pill/Pill.tsx, src/components/dls/QuranWord/QuranWord.tsx, src/components/dls/Tabs/Tabs.tsx, src/components/dls/Text/Text.tsx, src/utils/seo.ts, src/utils/styles.ts, yarn.lock
Implemented the design system tokens speced here: https://www.notion.so/Design-System-101-89e4170a42024da1a5d2d1ab2d3f5acb. 
Will create follow-ups to 1) remove non-token css usage and 2) Adding typescript support to the theme prop.
The pages now render w/o errors with slight changes to the home page dimensions (Addressed in a f/u)
=> Add Design System Tokens

package.json, src/components/AudioPlayer/AudioPlayer.tsx, src/components/DeveloperUtility/DeveloperUtility.tsx, src/components/Navbar/Navbar.tsx, src/components/QuranReader/Notes/Notes.tsx, src/components/QuranReader/TranslationView/index.tsx, src/components/chapters/ChapterBlock.tsx, src/components/chapters/ChapterIcon.tsx, src/components/chapters/ChapterList.tsx, src/components/dls/Cards/Card.tsx, src/components/dls/Cards/CardRow.tsx, src/components/dls/Cards/__snapshots__/Card.test.tsx.snap, src/components/dls/Pill/Pill.tsx, src/components/dls/Tabs/Tabs.tsx, src/styles/styled.d.ts, src/styles/theme.ts
Replaced all the CSS usage with design tokens, this adds consistency and will allow us to quickly tweak the design specs in the future. 
Added a few design tokens that were previously left as placeholders: Box shadow, border radiuses, opacity, z indexes (formerly elevation).
=> Replace hardcoded CSS with Token usage

package.json, src/components/AudioPlayer/AudioPlayer.tsx, src/components/Navbar/Navbar.tsx, src/components/QuranReader/Notes/Notes.tsx, src/components/QuranReader/PageView/Page.tsx, src/components/QuranReader/index.tsx, src/pages_/[chapterId].tsx, src/redux/store.ts, src/styles/constants.ts, src/styles/styled.d.ts, src/styles/theme.ts
Notes sidebar now overlays on mobile devices and pushes the Quran reader content. As per the design spec. 
| Desktop | Mobile |
|![image](https://user-images.githubusercontent.com/11590314/106560688-17f99400-6530-11eb-8903-b1fee28b5d30.png)| ![image](https://user-images.githubusercontent.com/11590314/106560736-2e9feb00-6530-11eb-8e54-fbdbe8a99309.png)|
=> Add Notes Section sidebar interaction

src/components/AudioPlayer/AudioPlayer.tsx, src/components/DeveloperUtility/DeveloperUtility.tsx, src/components/DeveloperUtility/NavbarAdjustment.tsx, src/components/Navbar/Navbar.tsx
Fixed the audio bar and navbar transitions leaving no empty spaces. Added a developer utility item to toggle the navbar visibility states
=> Adjust audio player and navbar transitions

src/components/DeveloperUtility/ContextMenuAdjustment.tsx, src/components/DeveloperUtility/DeveloperUtility.tsx, src/components/QuranReader/ContextMenu.tsx, src/components/QuranReader/index.tsx, src/redux/slices/QuranReader/contextMenu.ts, src/redux/store.ts
Added the container for the context menu with visibility states.
=> Add context menu container

package.json, yarn.lock
=> Upgrade to Next.js 10.0.6

next.config.js
=> Upgrade to webpack 5

src/components/DeveloperUtility/DeveloperUtility.tsx
Added a button name for the developer utility button to fix the accessibility warning
=> Add Developer utility button name for accessibility 

src/components/AudioPlayer/AudioPlayer.tsx, src/components/Navbar/Navbar.tsx, src/components/QuranReader/ContextMenu.tsx, src/components/QuranReader/index.tsx, src/pages_/index.tsx, src/redux/slices/navbar.ts, src/styles/constants.ts
* Prevent the Audio Bar from overflowing
* Added the navbar + context menu stickiness and transitions
=> Add Navbar + context menu stickiness and transitions

package.json, src/components/chapters/ChapterList.tsx, src/pages_/_document.tsx, src/pages_/about.tsx, src/pages_/index.tsx, yarn.lock
We previously had bootstrap integrated, but we won't be using it much in the new build. Removed the integration to decrease the bundle size
=> Remove bootstrap dependency

.babelrc, .eslintrc.yml, package.json, src/components/Navbar/Navbar.tsx, src/components/dls/Button/Button.stories.tsx, src/components/dls/Button/Button.tsx, tsconfig.json, types/global.d.ts, yarn.lock
Replaced next/image with inline SVGs for better performance and bundling.
=> Replace icon usage to inline SVGs

package.json, yarn.lock
=> Update Next.js to 10.0.7

src/components/AudioPlayer/AudioKeyboardListeners.tsx, src/components/AudioPlayer/AudioPlayer.tsx, src/components/AudioPlayer/Slider.tsx, src/styles/styled.d.ts, src/styles/theme.ts, src/utils/datetime.ts
=> Add audio player styles and event listeners

src/components/AudioPlayer/AudioPlayer.tsx, src/components/AudioPlayer/Slider.tsx
=> Listen to extenal audio playback events

README.md
=> Replace slack with discord community

.storybook/main.js, package.json, src/components/dls/Modal/Modal.stories.tsx, src/components/dls/Modal/Modal.tsx, src/hooks/useKeyPressedDetector.ts, src/styles/styled.d.ts, src/styles/theme.ts, yarn.lock
This PR add `Modal` component to QDC's DLS a story has been included as well to showcase different use-cases for the component.
=> Add Modal DLS

public/icons/tick.svg, src/components/dls/Forms/Checkbox/Checkbox.stories.tsx, src/components/dls/Forms/Checkbox/Checkbox.tsx
This PR adds `Checkbox` component to QDC's DLS.
=> Add checkbox component to DLS

src/components/dls/Forms/RadioButton/RadioButton.stories.tsx, src/components/dls/Forms/RadioButton/RadioButton.tsx
This PR adds `RadioButton` component to QDC's DLS.
=> Add radiobutton component to DLS

src/api.ts, src/components/Navbar/Navbar.tsx, src/components/Navbar/SideSearch/SideSearch.tsx, src/hooks/useDebounce.ts, src/hooks/useElementComputedPropertyValue.ts, src/pages/search.tsx, src/redux/slices/navbar.ts, src/utils/apiPaths.ts, types/APIRequests.ts, types/APIResponses.ts, types/SearchResult.ts
This PR adds a side search that can be opened by clicking on the search icon in the Navbar. This is the initial PR of the searching feature and will be improved in the subsequent PRs.
| |<img width="1439" alt="Screen Shot 2021-08-04 at 12 11 59" src="https://user-images.githubusercontent.com/15169499/128125728-c739d4f7-8757-47bc-a39d-546ac8ddca90.png">|
| |<img width="273" alt="Screen Shot 2021-08-04 at 12 12 23" src="https://user-images.githubusercontent.com/15169499/128125738-a667ce5c-9189-47d6-b215-a9b9e4fea357.png">|
=> Add side search section

src/components/Navbar/Navbar.tsx, src/components/Navbar/NavigationDrawer/MobileApps.tsx, src/components/Navbar/NavigationDrawer/NavigationDrawer.tsx, src/components/Navbar/NavigationDrawer/NavigationDrawerItem.tsx, src/components/Navbar/SearchDrawer/SearchDrawer.tsx, src/components/dls/Button/Button.tsx, src/pages/search.tsx, src/redux/slices/navbar.ts
This PR adds improvements to [Search Drawer's PR](https://github.com/quran/quran.com-frontend-next/pull/211).
=> Updating SearchDrawer and NavigationDrawer

src/api.ts, src/components/Verse/AdvancedCopy/VerseAdvancedCopy.tsx, src/utils/apiPaths.ts, types/APIRequests.ts, types/APIResponses.ts
This PR integrates the advanced copy with advanced copy API to load the translations' names and to generate the content that will be copied to the clipboard and to the text file.
=> Integrate advanced copy with API

.github/workflows/lighthouse-audit.yml, .lighthouserc.js
To setup an action that will run lighthouse CI in existing workflow so that, we can get lighthouse score on every Pull Request
Lighthouse Audit is performed on 3 URLs now
- / 
- /2
- /2/255
=> Setup Lighthouse CI

src/components/AudioPlayer/AudioPlayer.tsx
=> Disable Audio keyboard listeners

src/api.ts, src/components/Navbar/SearchDrawer/SearchDrawer.tsx, src/components/Navbar/SearchDrawer/SearchDrawerBody.tsx, src/components/Search/LanguagesFilter.tsx, src/components/Search/SearchResultItem.tsx, src/components/Search/TranslationsFilter.tsx, src/components/dls/Forms/SearchDropdown/SearchDropdown.tsx, src/components/dls/Pagination/Pagination.stories.tsx, src/components/dls/Pagination/Pagination.tsx, src/hooks/useAddQueryParamsToUrl.ts, src/hooks/useKeyPressedDetector.ts, src/pages/search.tsx, src/utils/apiPaths.ts, types/APIResponses.ts, types/AvailableLanguage.ts
=> Add search page

src/components/AudioPlayer/AudioPlayer.tsx, src/components/AudioPlayer/Slider.tsx, src/styles/utility.tsx
Made a few UI improvements to the audio player on mobile. Will create a follow-up PR with more changes iA. 
=> Improve the Audio mobile player

.vscode/settings.json, README.md
=> Add scss variable names auto-complete support

src/components/AudioPlayer/AudioPlayer.module.scss, src/components/AudioPlayer/Slider.module.scss, src/components/Search/Filter.module.scss, src/components/Search/SearchResultItem.module.scss, src/components/chapters/ChapterBlock.module.scss, src/components/dls/Cards/Card.module.scss, src/components/dls/Dropdown/Dropdown.module.scss, src/components/dls/Forms/Checkbox/Checkbox.module.scss, src/components/dls/Forms/RadioButton/RadioButton.module.scss, src/components/dls/Pagination/Pagination.module.scss, src/pages/search.module.scss, src/styles/theme.scss
=> Replace css theme variable naming from plural to singular

src/components/AudioPlayer/AudioPlayer.module.scss, src/components/Navbar/Navbar.module.scss, src/components/Navbar/NavigationDrawer/NavigationDrawerItem.module.scss, src/components/Navbar/NavigationDrawer/NavigationDrawerItem.tsx, src/styles/constants.scss
=> Navigation Drawer Item: Remove styled-components usage

src/components/Verse/AdvancedCopy/VerseAdvancedCopy.module.scss, src/components/Verse/AdvancedCopy/VerseAdvancedCopy.tsx, src/components/Verse/AdvancedCopy/VersesRangeSelector.module.scss, src/components/Verse/AdvancedCopy/VersesRangeSelector.tsx
Remove styled components
|  ![image](https://user-images.githubusercontent.com/12745166/128693246-254659ae-ea31-4c85-a860-49f223b31ed8.png) | ![image](https://user-images.githubusercontent.com/12745166/128693067-3c716fa4-73c1-49ea-bb75-6de0e0a85e42.png) |
=> Verse/AdvancedCopy: remove styled-components

src/components/Verse/VerseActionModal.module.scss, src/components/Verse/VerseActionModal.tsx, src/components/Verse/VerseActions.module.scss, src/components/Verse/VerseActions.tsx, src/components/Verse/VerseActionsMenu.module.scss, src/components/Verse/VerseActionsMenu.tsx, src/components/Verse/VerseActionsMenuItem.module.scss, src/components/Verse/VerseActionsMenuItem.tsx, src/components/Verse/VerseText.module.scss, src/components/Verse/VerseText.tsx
=> refactor verse directory: remove styled components

src/components/Verse/AdvancedCopy/VersesRangeSelector.module.scss
Fix small css bug
| ----|  -----|
| ![image](https://user-images.githubusercontent.com/12745166/128800192-27a0f554-fa78-4331-a232-ce25e284d238.png)  | ![image](https://user-images.githubusercontent.com/12745166/128800180-228f81c3-b95c-43b6-8c30-1d1f26f54c34.png) |
=> fix: css bug when refactoring styled-components

src/components/Verse/VerseText.tsx
- fix: css bug in QuranReader, can't change quran font size
- go to the readingview: translation . change the the quran font size
=> fix: css bug in QuranReader, can't change font size

src/components/QuranReader/TafsirView/index.tsx, src/components/QuranReader/index.tsx, src/pages/[chapterId]/[verseId]/tafsirs.tsx, types/Tafsir.ts
This PR adds the name of the tafsir.
| <img width="1440" alt="Screen Shot 2021-08-12 at 04 07 26" src="https://user-images.githubusercontent.com/15169499/129103621-f2eb880c-92a7-4b9f-abe1-c8a3226fe507.png">| <img width="1440" alt="Screen Shot 2021-08-12 at 04 06 37" src="https://user-images.githubusercontent.com/15169499/129103612-d170c3e0-4da8-442a-9a9a-547e16f034ef.png">|
=> Add tafsir's name

src/api.ts, src/components/QuranReader/index.tsx, src/pages/page/[pageId].tsx, src/utils/apiPaths.ts, src/utils/validator.ts
This PR adds the ability to read a specific Quranic page through the url `/page/{pageNumber}`.
|  | <img width="1440" alt="Screen Shot 2021-08-13 at 05 57 26" src="https://user-images.githubusercontent.com/15169499/129280620-aa80946a-95b2-4a0d-a010-b00d84ec78d9.png"> |
=> Add ability to read a specific Quranic page

src/components/Navbar/NavigationDrawer/NavigationDrawerItem.module.scss, src/components/dls/Button/Button.module.scss, src/styles/themes/dark.scss, src/styles/themes/light.scss
- Fix side menu font size
- Fix play button text color not adapting to theme
- Add new placeholder color values for the themes (still placeholders)
=> Misc Design Changes

src/components/chapters/ChapterHeader/index.tsx
This PR removes Bimillah from the header of Surah 1 and Surah 9.
| <img width="1440" alt="Screen Shot 2021-08-14 at 19 34 41" src="https://user-images.githubusercontent.com/15169499/129446526-ebb66b8b-4ddf-4125-9374-8484cd74eb80.png"> | <img width="1440" alt="Screen Shot 2021-08-14 at 19 35 01" src="https://user-images.githubusercontent.com/15169499/129446529-eeca1ab3-e1d1-41e7-91ce-312f767d0128.png"> |
|<img width="1440" alt="Screen Shot 2021-08-14 at 19 40 27" src="https://user-images.githubusercontent.com/15169499/129446648-1a5adb1d-8e81-4b54-8ae7-0ecc4c75a410.png">|<img width="1440" alt="Screen Shot 2021-08-14 at 19 40 35" src="https://user-images.githubusercontent.com/15169499/129446649-961ea0f0-e1be-498e-aa65-6aded3353027.png">
=> Remove Bismillah for Surah 1 (Al Fatihah) and Surah 9 (Al Tawbah)

next-env.d.ts, src/api.ts, src/utils/apiPaths.ts
hot fix timestamp initial data was found
=> hot fix:  timestamp initial data was found

src/pages/about.tsx
This PR statically generate about page at build time since its content will barely change.
| <img width="749" alt="Screen Shot 2021-08-17 at 18 30 37" src="https://user-images.githubusercontent.com/15169499/129718748-1c779851-8d63-4305-b12a-ed7da81bdc4a.png"> | <img width="513" alt="Screen Shot 2021-08-17 at 18 29 18" src="https://user-images.githubusercontent.com/15169499/129718736-8804d7b9-9885-441a-b44c-ab3fb5345c38.png"> |
=> Statically generate about page

configs/SecurityHeaders.js, next.config.js
This is a follow up PR to [security headers' PR](https://github.com/quran/quran.com-frontend-next/pull/279).
=> Follow Up: update security headers

configs/SecurityHeaders.js
=> csp quick fix

src/components/dls/Button/Button.stories.tsx, src/components/dls/Spinner/Spinner.stories.tsx
=> Storybook spinner

src/components/Navbar/NavigationDrawer/NavigationDrawer.module.scss, src/components/Navbar/SearchDrawer/SearchDrawer.module.scss
only show css box shadow when the renderer is open
=> misc: drawer only show shadow when open

src/components/Navbar/NavigationDrawer/NavigationDrawerItem.module.scss
quick fix navigation drawer item hover css
https://www.loom.com/share/890b928e5a794cb68cdd0fcbf5c01d47
=> navigation drawer hover fix

src/styles/theme.scss
Tested the tokens and modified them to represent a full pixel unit. (e.g. the small size used to represent 11.2 pixels, now it represents 12 pixels)
=> Update the theme font tokens

src/components/QuranReader/TranslationView/BookmarkIcon.tsx, src/components/QuranReader/TranslationView/TranslationView.module.scss, src/components/QuranReader/TranslationView/index.tsx, src/components/Verse/VerseActions.module.scss, src/components/Verse/VerseActions.tsx, src/components/dls/Button/Button.module.scss, src/styles/_utility.scss
=>  Translation view improvement

src/components/QuranReader/ReadingView/Page.module.scss, src/components/Verse/VerseText.tsx
This PR fixes a few issues with the `QuranReader`.
|<img width="275" alt="Screen Shot 2021-08-30 at 17 59 01" src="https://user-images.githubusercontent.com/15169499/131330259-9bd13fcb-6467-4d70-af60-8f7c9d6c5226.png">|<img width="274" alt="Screen Shot 2021-08-30 at 17 58 55" src="https://user-images.githubusercontent.com/15169499/131330252-2ba6eb04-9e3a-4c10-beb5-c63222e4fba4.png">|
|<img width="276" alt="Screen Shot 2021-08-30 at 17 59 50" src="https://user-images.githubusercontent.com/15169499/131330265-5c06ec3a-0501-4559-a498-f9f6aa9f5c09.png">|<img width="276" alt="Screen Shot 2021-08-30 at 17 59 56" src="https://user-images.githubusercontent.com/15169499/131330269-779630de-d61b-4909-bb4a-b0bc7b4b3d4c.png">|
|<img width="275" alt="Screen Shot …
=> Fix wbw translation on mobile

configs/SecurityHeaders.js, package.json, src/components/HomePage/HomePageWelcomeMessage.module.scss, src/components/HomePage/HomePageWelcomeMessage.tsx, src/pages/index.module.scss, src/pages/index.tsx, src/styles/themes/_light.scss, yarn.lock
=> Add feedback fish and a home page welcome message

src/components/ThirdPartyScripts/HotjarScript.tsx, src/components/ThirdPartyScripts/ThirdPartyScripts.tsx
=> Add the hotjar script

src/components/ThirdPartyScripts/HotjarScript.tsx, src/components/ThirdPartyScripts/ThirdPartyScripts.tsx
=> Enable hotjar only on production

src/components/ThirdPartyScripts/HotjarScript.tsx, src/components/ThirdPartyScripts/ThirdPartyScripts.tsx
=> Add hotjar to the whitelist security policy

src/components/FeedbackWidget/FeedbackWidget.module.scss, src/components/FeedbackWidget/FeedbackWidget.tsx, src/pages/_app.tsx
Disabled the widget on mobile because FF doesn't have good support for it.
=> Add global feedback widget

src/components/Navbar/NavigationDrawer/NavigationDrawer.tsx, src/components/Navbar/SearchDrawer/SearchDrawer.tsx, src/components/Navbar/SettingsDrawer/SettingsDrawer.tsx
This PR adds ability to close the search, navigation and settings drawers when clicking outside of them or on pressing the ESCAPE key.
=> Make drawers close on click outside or on pressing ESC key

src/components/DeveloperUtility/DeveloperUtility.module.scss, src/styles/themes/_dark.scss
=> Update the dark theme tokens

src/components/QuranReader/TranslationView/TranslationView.module.scss, src/components/QuranReader/TranslationView/index.tsx, src/components/Verse/VerseLink/index.tsx, src/styles/themes/_dark.scss, src/styles/themes/_light.scss
Quick design updates based on my conversation with Aqeel.
=> Token updates part 26

src/components/Navbar/SettingsDrawer/QuranFontSection.tsx, src/components/Navbar/SettingsDrawer/ReadingExperienceSection.tsx, src/components/Navbar/SettingsDrawer/ThemeSection.tsx, src/components/dls/Forms/RadioGroup/RadioGroup.tsx, src/components/dls/Forms/Select/Select.module.scss, src/components/dls/Forms/Select/Select.stories.tsx, src/components/dls/Forms/Select/index.tsx, src/redux/slices/theme.ts, src/utils/input.ts
This PR adds `Select` component to DLS and replaces some Combobox in the Setting drawer with the `Select` component. 
| <img width="384" alt="Before" src="https://user-images.githubusercontent.com/15169499/131793039-ef96af77-0346-4bbc-ba5b-35c4cd64c9e3.png"> | <img width="384" alt="After" src="https://user-images.githubusercontent.com/15169499/131793024-d1bf38ef-c606-4ba0-ac47-2ef38b6d2061.png"> |
|<img width="384" alt="Before 1" src="https://user-images.githubusercontent.com/15169499/131793041-efa5d10a-6694-4133-a0c9-22fb80324c54.png">|<img width="385" alt="After 1" src="https://user-images.githubusercontent.com/15169499/131793031-fe37049e-c2de-4581-8c5f-1937a6c4014c.png">|
|![Before 2](https://user-images.githubusercontent.com/15169499/131793044-7de …
=> Add Select to DLS and replace Combobox with Select

src/components/dls/Link/Link.module.scss, src/components/dls/Link/Link.stories.tsx, src/components/dls/Link/Link.tsx
Create link DLS
preview is in storybook
=> create link DLS

package.json, src/components/dls/HoverCard/HoverCard.module.scss, src/components/dls/HoverCard/HoverCard.stories.tsx, src/components/dls/HoverCard/index.tsx, yarn.lock
This PR adds `HoverCard` component to DLS.
=> Add hover card to DLS

configs/SecurityHeaders.js, package.json, src/components/FeedbackWidget/FeedbackWidget.module.scss, src/components/FeedbackWidget/FeedbackWidget.tsx, src/components/HomePage/HomePageWelcomeMessage.tsx, yarn.lock
TSIA. https://quran.upvoty.com until we alias feedback.quran.com
=> Replace feedback fish with Upvoty

src/components/AudioPlayer/AudioPlayer.tsx, src/components/HomePage/HomePageWelcomeMessage.module.scss, src/components/QuranReader/TranslationView/TranslationView.module.scss, src/components/Verse/VerseActions.tsx, src/components/chapters/ChapterBlock.module.scss, src/components/chapters/ChapterHeader/ChapterHeader.module.scss, src/components/chapters/ChapterHeader/index.tsx, src/components/chapters/ChapterIcon/ChapterIconContainer.module.scss, src/components/chapters/ChapterIcon/ChapterIconContainer.tsx, src/components/dls/Bismillah/Bismillah.module.scss, src/components/dls/Bismillah/Bismillah.tsx, src/components/dls/Button/Button.module.scss, src/styles/themes/_dark.scss, src/styles/themes/_light.scss
* Fix incorrect Rewind button tooltip 
* Change the welcome message to blue based on Aqeel's request
* Replace all borders to use a hairline color. This makes the contrast less strong on dark mode
* Disable ayah level audio playback until we fix the timestamping error from the backend
* Increase the bismillah and surah name font size
* Add a size prop for the bismillah and surah name components 
* Fix the secondary button text color changing on hover
=> Beta release candidate polish

src/components/Search/SearchResults/SearchResultItem.tsx, src/components/Verse/VerseText.tsx, src/components/Wrapper/Wrapper.tsx, src/components/dls/Button/Button.tsx, src/components/dls/HoverCard/HoverCard.module.scss, src/components/dls/HoverCard/HoverCard.stories.tsx, src/components/dls/HoverCard/index.tsx, src/components/dls/QuranWord/QuranWord.tsx, src/components/dls/Tooltip/Tooltip.stories.tsx, src/components/dls/Tooltip/index.tsx, src/utils/verse.ts
The PR reverts the changes made to `Tooltip` and `HoverCard` to make them work on mobile.
=> Revert Tooltip and Hover Card changes

src/components/Navbar/SettingsDrawer/TafsirSection.tsx
This PR sets the minimum required Tafsirs to 1 inside the Settings Drawer.
=> Set the minimum number of Tafsirs to 1

src/components/Navbar/SettingsDrawer/TafsirSection.tsx
=> add tafsir font scale to settings menu

src/components/FeedbackWidget/FeedbackWidget.tsx, src/components/HomePage/HomePageWelcomeMessage.tsx, src/components/Verse/AdvancedCopy/VerseAdvancedCopy.tsx, src/components/dls/Link/Link.tsx
=> Implement link dls

src/api.ts, src/components/QuranReader/TranslationView/TranslationText/TranslationText.module.scss, src/components/QuranReader/TranslationView/TranslationText/index.tsx, src/components/QuranReader/TranslationView/TranslationView.module.scss, src/components/QuranReader/TranslationView/index.tsx, src/utils/apiPaths.ts, types/APIResponses.ts, types/Footnote.ts
This PR adds footnotes support for translations.
| <img width="1440" alt="Screen Shot 2021-09-06 at 11 59 05" src="https://user-images.githubusercontent.com/15169499/132163162-61867108-5530-40b3-becb-84f0b4151fe1.png"> | <img width="1440" alt="Screen Shot 2021-09-06 at 11 58 57" src="https://user-images.githubusercontent.com/15169499/132163150-094e5577-68c1-4c08-bb78-346d4b93c530.png"> |
||<img width="1440" alt="Screen Shot 2021-09-06 at 11 59 17" src="https://user-images.githubusercontent.com/15169499/132163164-f2a5b0eb-deb1-4dea-baa3-bd43b60568e7.png">|
|<img width="275" alt="Screen Shot 2021-09-06 at 12 00 17" src="https://user-images.githubusercontent.com/15169499/132163167-e04a9b68-c1c2-464e-b781-d357dcab0c49.png">|<img width="276" alt="Screen …
=> show translation footnotes

package.json, src/components/dls/Separator/Separator.module.scss, src/components/dls/Separator/Separator.stories.module.scss, src/components/dls/Separator/Separator.stories.tsx, src/components/dls/Separator/Separator.tsx, yarn.lock
- Add separator dls
Need to discuss some approach about inline sytling
=> DLS: Separator

src/redux/slices/AudioPlayer/state.ts
Previously clicking this "Play" Button twice, will result in infinite loading.
this PR fixed the issue
=> fix: clicking play audio chapter, result in infinite loading

src/components/DeveloperUtility/TranslationsAdjustment.tsx, src/components/Navbar/SearchDrawer/SearchDrawer.tsx, src/components/Navbar/SettingsDrawer/TranslationSection.tsx, src/components/Search/LanguagesFilter.tsx, src/components/Search/SearchResults/SearchResultItem.tsx, src/components/Search/SearchResults/index.tsx, src/components/Search/TranslationsFilter.tsx, src/components/Verse/AdvancedCopy/VerseAdvancedCopy.tsx, src/pages/search.tsx, src/redux/slices/QuranReader/translations.ts, types/APIRequests.ts, types/APIResponses.ts, types/SearchVerseResult.ts
This PR adds support to language and translation inside search page and also handles showing the results when there are some navigation results but no verses in the response.
|<img width="1440" alt="Screen Shot 2021-09-06 at 19 33 55" src="https://user-images.githubusercontent.com/15169499/132218489-e5f1260a-ff94-474f-b291-f427f5c43088.png">|<img width="1440" alt="Screen Shot 2021-09-06 at 19 35 44" src="https://user-images.githubusercontent.com/15169499/132218525-a95e271c-971c-4c76-913c-d6cc6a570948.png">|
|<img width="384" alt="Screen Shot 2021-09-06 at 19 38 57" src="https://user-images.githubusercontent.com/15169499/132218866-48633514-ec8f-42a1-b2e8-9f0214fcdd56.png">|<img width="384" alt="Screen Shot 2021-09-06 at 19 39 02" …
=> Search page improvements

src/components/chapters/Info/Info.module.scss, src/components/chapters/Info/index.tsx
This PR adds a navigation back to Surah from the Surah info's page.
|<img width="275" alt="Screen Shot 2021-09-07 at 14 17 35" src="https://user-images.githubusercontent.com/15169499/132301388-d9939fa2-eb45-4378-b562-f6e7cb056c6e.png">|<img width="272" alt="Screen_Shot_2021-09-07_at_14 38 24" src="https://user-images.githubusercontent.com/15169499/132304552-7b86888d-14eb-452a-948f-ca1d6bab3d19.png">|
=> Add navigation back to Surah from info page

src/components/DeveloperUtility/DeveloperUtility.module.scss, src/components/DeveloperUtility/DeveloperUtility.tsx, src/components/Navbar/SettingsDrawer/Section.module.scss, src/components/Navbar/SettingsDrawer/Section.tsx, src/components/QuranReader/TranslationView/TranslationView.module.scss, src/components/QuranReader/TranslationView/index.tsx
TSIA
We don't use `<hr />` anywhere in our codebase actually. 
So far we're only using divider / separator in :
- setting's menu section
- between verse cell in translation view
- in dev utility
=> implement separator dls

src/components/Navbar/SettingsDrawer/TafsirSection.tsx, src/components/Navbar/SettingsDrawer/TranslationSection.tsx, src/components/Search/TranslationsFilter.tsx, src/utils/input.ts
This PR adds the language of the translation and the Tafsir selectors.
|<img width="256" alt="Screen Shot 2021-09-08 at 09 46 44" src="https://user-images.githubusercontent.com/15169499/132438455-c9cd5aa1-b5d8-4175-8ccf-f244e9e6960f.png">|<img width="258" alt="Screen Shot 2021-09-08 at 09 46 34" src="https://user-images.githubusercontent.com/15169499/132438451-f74bccad-623d-414b-9614-157d9b3f06a3.png">|
|<img width="259" alt="Screen Shot 2021-09-08 at 09 47 03" src="https://user-images.githubusercontent.com/15169499/132438462-933697f3-d343-4cd2-903c-da959cb6a847.png">|<img width="259" alt="Screen Shot 2021-09-08 at 09 46 55" src="https://user-images.githubusercontent.com/15169499/132438460-104db2c9-96c8-4f2d-8f6f-3fe970ae97ea.png">|
|<img width="320" …
=> Show translation and tafsir langauges

src/components/Verse/VerseActionsMenu.tsx, src/utils/verse.ts
=>  add "Go to Ayah" action in verseActionMenu

src/components/QuranReader/TranslationView/BookmarkIcon.tsx, src/components/QuranReader/TranslationView/TranslationView.module.scss, src/components/QuranReader/TranslationView/index.tsx, src/components/Verse/VerseActions.module.scss, src/components/Verse/VerseActions.tsx, src/components/Verse/VerseLink/index.tsx, src/components/dls/Button/Button.module.scss
Before
After
Design following the figma a bit. But we can revert back to old design
=> Move verse actions to top

src/components/AudioPlayer/AudioPlayer.module.scss, src/components/AudioPlayer/AudioPlayer.tsx, src/components/AudioPlayer/CloseButton.tsx, src/redux/slices/AudioPlayer/state.ts, src/redux/store.ts
=> feat: button to close audio player

src/utils/api.ts
Quick fix for detecting Mushaf type for the selected QuranFont, then fetch words for detect Mushaf. 
=> Musha text

src/components/Navbar/SettingsDrawer/ReadingExperienceSection.tsx, src/components/QuranReader/TranslationView/TranslationText/TranslationText.module.scss, src/styles/themes/_dark.scss
| ![2021-09-12 at 14 43 03](https://user-images.githubusercontent.com/11590314/132988001-8dd17feb-e9f8-4f1d-a9e0-bb1313bb17c3.png)| ![2021-09-12 at 14 43 25](https://user-images.githubusercontent.com/11590314/132988017-47aaef39-0a9a-436c-a6aa-1f7ede9dfd8b.png) |
=> Update dark mode background + Tooltip copy + Footnote marker padding

src/styles/theme.scss
=> Remove unused font tokens

src/components/Navbar/SearchDrawer/PreInput/SearchQuerySuggestion/SearchQuerySuggestion.module.scss, src/components/Navbar/SearchDrawer/PreInput/SearchQuerySuggestion/index.tsx, src/components/Navbar/SearchDrawer/SearchHistory/index.tsx, src/redux/slices/Search/search.ts
This PR adds the ability to remove a recent search query.
|<img width="384" alt="Screen Shot 2021-09-13 at 10 52 54" src="https://user-images.githubusercontent.com/15169499/133022092-8027ef07-fe40-4e31-a0ba-25712355fc2e.png">|<img width="384" alt="Screen Shot 2021-09-13 at 10 52 47" src="https://user-images.githubusercontent.com/15169499/133022083-78882727-2cc5-4cce-a881-a4b850e6162f.png">|
=> Add remove recent search query button

src/components/QuranReader/TranslationView/BookmarkIcon.tsx, src/components/Verse/VerseActionsMenu.tsx
=> Hot fix shallow Equal audit

src/components/QuranReader/QuranReader.module.scss, src/components/QuranReader/index.tsx, src/components/dls/Spinner/Spinner.tsx
This PR adds a spinner for the QuranReader.
|<img width="1436" alt="Screen Shot 2021-09-15 at 07 38 54" src="https://user-images.githubusercontent.com/15169499/133352007-a2dc2444-5869-4e8f-96b4-4ab40cd6afb5.png">|<img width="1440" alt="Screen Shot 2021-09-15 at 07 37 17" src="https://user-images.githubusercontent.com/15169499/133351990-4a59cbe2-2cc2-4b08-a251-33a58f788d32.png">|
|<img width="276" alt="Screen Shot 2021-09-15 at 07 38 32" src="https://user-images.githubusercontent.com/15169499/133352004-3ff3f909-a970-4742-8db6-b51955b4fdcb.png">|<img width="275" alt="Screen Shot 2021-09-15 at 07 38 00" src="https://user-images.githubusercontent.com/15169499/133352001-053da7b6-059a-48af-bdad-48432343a1fb.png">|
=> Add Spinner for QuranReader

src/components/AudioPlayer/PlayPauseButton.tsx
=> Mismatch Audio Modal: don't show on homepage

.storybook/preview.js
TSIA
https://quran.github.io/quran.com-frontend-next/storybook/theme-switcher/?path=/story/chapters-chapterblock--normal
here's the url for testing
=> Add theme switcher to storybook

src/components/dls/Modal/Modal.module.scss
This PR fixes issue with the modal when on Dark mode.
|<img width="452" alt="Screen Shot 2021-09-15 at 19 43 45" src="https://user-images.githubusercontent.com/15169499/133436057-db1c3819-537b-49b8-b6d4-1aea3a85dc86.png">|<img width="448" alt="Screen Shot 2021-09-15 at 19 43 21" src="https://user-images.githubusercontent.com/15169499/133436036-081a0fc3-d67d-44dd-bd75-39c24e452fcc.png">|
|<img width="452" alt="Screen Shot 2021-09-15 at 19 44 03" src="https://user-images.githubusercontent.com/15169499/133436063-c7eace36-6161-464c-b59c-cc2bbc26a2af.png">|<img width="452" alt="Screen Shot 2021-09-15 at 19 44 15" src="https://user-images.githubusercontent.com/15169499/133436071-a3839058-2950-44d0-bea3-527b8d445cf3.png">|
=> Fix dark mode advanced copy modal

src/styles/_breakpoints.scss
This allows us to modify media queries for smaller devices
=> Add smaller than breakpoints

public/data/chapters/en.json
TSIA
```
keep this data
// id 
// nameSimple -> used in chapter header
// nameArabic -> used in chapterblock
// translatedName -> used in chapterHeader
// verseCount -> used in pages/[chapterId], an other places
// pages -> used chapter info
// revelationPlace -> used in chapter info
```
=> reduce chapter json file size

src/utils/apiPaths.ts
=> Make api consistent with rest of apis. We've chapters/1 not chapter/1

.github/workflows/build-storybook.yml
Follow up PR on storybook deployment, very simple one.
- build master too, so it's always up to date
=>  Follow up PR on storybook deployment 

src/utils/api.ts
Fixes the QCF text not rendering correctly. 
We'll add proper support for Mushafs next week iA. 
| ![image](https://user-images.githubusercontent.com/11590314/133684021-9b4ca6f1-445b-4678-863d-e6796455dfac.png) | <img width="576" alt="2021-09-16 at 22 56 39@2x" src="https://user-images.githubusercontent.com/11590314/133684553-b5cafcbc-f14e-4514-8af2-6b5a6a06d779.png"> |
=> Update default Mushaf text

src/api.ts, src/components/QuranReader/api.ts, src/components/QuranReader/index.tsx, src/pages/[chapterId]/index.tsx, src/utils/api.ts, src/utils/apiPaths.ts, types/ApiRequests.ts
=> Refactor API utilities

.github/workflows/build-storybook.yml
fixing some branch without storybook changes not deployed
=> Patch storybook deployment

src/components/QuranReader/TranslationView/index.tsx
=> path highlighting UI

src/components/QuranReader/ReadingView/Line.tsx, src/components/Verse/VerseText.module.scss, src/components/Verse/VerseText.tsx
=> Ayah Highlighting UI

src/components/Navbar/SettingsDrawer/AudioSection.tsx, src/redux/slices/AudioPlayer/state.ts
changing reciter now will fetch the new audio file, and restart the audio (if it user is currently playing an audio)
=> fix bug: changing reciter doesn't update the audio file

src/components/Verse/AdvancedCopy/VerseAdvancedCopy.tsx
Go to next.quran.com and click "advanced copy", there's a client side error.
this PR fixed that issue
=> fix regression: clicking "advanced copy" gives "client error"

.github/workflows/build-storybook.yml
yet another storybook patch, fixed some deployment error. Not pulled before pushing
=> storybook patch

src/components/QuranReader/TranslationView/BookmarkIcon.tsx
on translation view, clicking bookmark icon. Will make remove the bookmark
=> Translation view : click bookmark icon to remove

src/components/QuranReader/ContextMenu.module.scss, src/components/QuranReader/ContextMenu.tsx, src/components/QuranReader/ReadingView/groupLinesByVerses.ts, src/components/QuranReader/TafsirView/index.tsx, src/components/QuranReader/TranslationView/TranslationViewCell.tsx, src/components/QuranReader/index.tsx, src/components/Verse/VerseText.tsx, src/components/chapters/ChapterHeader/index.tsx, src/redux/migrations.ts, src/redux/slices/QuranReader/readingTracker.ts, src/redux/store.ts, src/styles/theme.scss, src/utils/apiPaths.ts, src/utils/chapter.ts, src/utils/juz.ts, src/utils/verse.ts, types/Word.ts
This PR adds context menu to the Quran Reader that shows the current verse, page and Surah being read and also the progress of reading the Surah.
|<img width="1440" alt="Screen Shot 2021-09-22 at 13 47 44" src="https://user-images.githubusercontent.com/15169499/134297196-4a78176c-52f0-4199-8aff-4dc750091400.png">|<img width="1440" alt="Screen Shot 2021-09-22 at 13 45 56" src="https://user-images.githubusercontent.com/15169499/134297168-a1742d8c-64c6-425d-99e2-f7210e255825.png">|
||<img width="1440" alt="Screen Shot 2021-09-22 at 13 46 06" src="https://user-images.githubusercontent.com/15169499/134297185-673064a0-ae57-4cf8-80a8-06e8e50a0f68.png">|
||<img width="281" alt="Screen Shot 2021-09-22 at 13 47 01" …
=> Add Verse Context Menu

src/components/QuranReader/TranslationView/TranslationViewCell.tsx, src/components/QuranReader/TranslationView/index.tsx, src/redux/slices/QuranReader/highlightedLocation.ts
=> Perf: reduce re rendering in TranslationView component

src/components/HomePage/QuickLinks/QuickLink.tsx, src/components/HomePage/QuickLinks/QuickLinks.module.scss, src/components/HomePage/QuickLinks/index.tsx, src/components/Verse/VerseLink/index.tsx, src/components/Verses/RecentReadingSessions.module.scss, src/components/Verses/RecentReadingSessions.tsx, src/pages/index.tsx, src/redux/migrations.ts, src/redux/slices/QuranReader/readingTracker.ts, src/redux/store.ts, src/utils/navigation.ts, src/utils/verse.test.ts, src/utils/verse.ts
This PR adds ability to mark reading sessions and show them in the homepage.
=> Add latest reading sessions

package.json, src/components/dls/Slider/Slider.module.scss, src/components/dls/Slider/Slider.stories.tsx, src/components/dls/Slider/index.tsx, yarn.lock
This PR adds `Slider` component to QDC's DLS.
=> Add Slider component to dls

src/components/Navbar/SettingsDrawer/AudioSection.tsx, src/components/QuranReader/ReadingView/Line.tsx, src/components/QuranReader/TranslationView/TranslationViewCell.tsx, src/hooks/useScrollToElement.ts, src/redux/slices/AudioPlayer/state.ts, src/styles/reset.scss
Try deploy preview to see how it works
=> feat: auto scrolling

src/components/Navbar/NavigationDrawer/NavigationDrawer.module.scss, src/components/Navbar/SearchDrawer/SearchDrawer.module.scss, src/components/Navbar/SettingsDrawer/SettingsDrawer.module.scss
This improves the drawer animation feel: https://www.joshwcomeau.com/animation/css-transitions/
=> Add ease-in and ease-out transitions for the drawer

src/components/QuranReader/TranslationView/TranslationViewCell.tsx, src/components/Verse/PlayVerseAudioButton.tsx, src/redux/slices/AudioPlayer/state.ts, src/redux/slices/QuranReader/highlightedLocation.ts
Make the play button in TranslationViewCell render conditionally (play or pause). Based on highlighedLocation data
- first commit is simpler but without "loading support"
- second commit is with loading support but contains more changes
=> TranslationViewCell verse play/pause button

src/components/QuranReader/EndOfScrollingControls/ChapterControls.tsx, src/components/QuranReader/EndOfScrollingControls/EndOfScrollingButton.tsx, src/components/QuranReader/EndOfScrollingControls/EndOfScrollingControls.module.scss, src/components/QuranReader/EndOfScrollingControls/JuzControls.tsx, src/components/QuranReader/EndOfScrollingControls/PageControls.tsx, src/components/QuranReader/EndOfScrollingControls/TafsirControls.tsx, src/components/QuranReader/EndOfScrollingControls/VerseControls.tsx, src/components/QuranReader/EndOfScrollingControls/index.tsx, src/components/QuranReader/index.tsx, src/hooks/useScrollToTop.ts, src/utils/juz.ts, src/utils/navigation.ts, src/utils/page.ts, src/utils/verse.ts
This PR adds end of scrolling navigation controls to Page, Juz, Range of Ayahs, Tafsir of an Ayah and a Surah.  
| Before | After | Description |
| ------ | ------ | ------ |
|<img width="1440" alt="chapter - b" src="https://user-images.githubusercontent.com/15169499/134806939-8b5d7e87-e338-4d95-a5a8-bb716d08ee79.png">|<img width="1440" alt="chapter - a" src="https://user-images.githubusercontent.com/15169499/134806934-b5e5e208-c777-429f-bc52-9354a24287c4.png">|Surah|
|<img width="1440" alt="juz - b" src="https://user-images.githubusercontent.com/15169499/134806942-7b43b3a8-d5dd-45a2-9c71-07a1c1f5ca6a.png">|<img width="1440" alt="juz - a" src="https://user-images.githubusercontent.com/15169499/134806941-54338574-bd4a-49f5-8974-505eb1e81cf7.png">|Juz|
|<img width="1440" alt="page - b" …
=> Add QuranReader navigations

src/components/QuranReader/EndOfScrollingControls/TafsirControls.tsx, src/components/QuranReader/EndOfScrollingControls/index.tsx, src/components/QuranReader/Loader/Loader.module.scss, src/components/QuranReader/Loader/index.tsx, src/components/QuranReader/QuranReader.module.scss, src/components/QuranReader/api.ts, src/components/QuranReader/index.tsx, src/components/QuranReader/types.ts, src/components/chapters/ChapterHeader/index.tsx, src/components/chapters/Info/InfoPage.tsx, src/components/chapters/Info/index.tsx, src/pages/[chapterId]/[verseId]/index.tsx, src/pages/[chapterId]/index.tsx, src/pages/[chapterId]/tafsirs/[tafsirId].tsx, src/pages/chapter_info/[chapterId].tsx, src/pages/surah-info/[chapterId].tsx, src/pages/surah/[chapterId]/info.tsx, src/utils/navigation.ts, src/utils/validator.test.ts, src/utils/validator.ts, src/utils/verse.ts
This PR adds support to the live website's routes. The routes that were added/changed are as following:
|Route|Description|Sample URL|
| ------ | ------ | ------ |
|`/{surahId}:{ayahNumber}`| Accessing an Ayah's page|`/1:1`|
|`/surah-info/{surahId}`|Accessing a Surah's info page|`/surah-info/1`|
|`/chapter_info/{surahId}`|Accessing a Surah's info page|`/chapter_info/1`|
|`/surah/{surahId}/info`|Accessing a Surah's info page|`/surah/1/info`|
|`/{surahId}:{ayahNumber}/tafsirs/{tafsirId}`|Accessing a specific Tafsir of a specific Ayah|`/36:1/tafsirs/169`|
=> Support all routes

src/components/QuranReader/Loader/Loader.module.scss, src/components/QuranReader/Loader/index.tsx
This PR adds Load More button to the `QuranReader`.
|<img width="1440" alt="Screen Shot 2021-09-27 at 20 54 20" src="https://user-images.githubusercontent.com/15169499/134922665-d7ae65ab-c5b6-4efd-9d54-148dfc9c9d51.png">|<img width="1440" alt="Screen Shot 2021-09-27 at 20 55 16" src="https://user-images.githubusercontent.com/15169499/134922693-27af91bb-95de-4559-9f54-d1f5b7aaa9cf.png">|
=> Add load more button

src/components/chapters/Info/Info.module.scss, src/components/chapters/Info/index.tsx
This PR improves how the Surah information is displayed.
|![Desktop - Before](https://user-images.githubusercontent.com/15169499/135193517-d42d3af3-1972-49cf-884f-5d11242dc787.png)|![Desktop - After](https://user-images.githubusercontent.com/15169499/135193496-9a7b70b9-fe4b-44a6-8da2-f9a05c9ea96c.png)|
|![Mobile - Before](https://user-images.githubusercontent.com/15169499/135193519-9c92e70e-f907-486c-b6fb-29308b18e83b.png)|![Mobile-After](https://user-images.githubusercontent.com/15169499/135193520-79e098cd-a128-4936-a27f-fb48c24f3036.png)|
=> Impove Surah info page UI

src/components/Navbar/SettingsDrawer/AudioSection.tsx, types/Reciter.ts
This PR adds reciter's recitation style (Mujawwad/Murattal) to the Dropdown list inside the Settings Drawer. Also sorts the list of reciters alphabetically. 
|<img width="268" alt="Screen Shot 2021-09-29 at 13 34 57" src="https://user-images.githubusercontent.com/15169499/135216911-f3a77fb0-80e1-4058-b09b-a92d72e9988a.png">|<img width="263" alt="Screen Shot 2021-09-29 at 13 34 07" src="https://user-images.githubusercontent.com/15169499/135216903-2a6fd415-7c2d-47a2-87a8-723d865d0bf4.png">|
=> Add reciter style

src/components/QuranReader/index.tsx
|<img width="1440" alt="Screen Shot 2021-09-29 at 20 34 59" src="https://user-images.githubusercontent.com/15169499/135279808-9e224e37-cdfb-41b4-9cb3-2b4d9e611859.png">|<img width="1440" alt="Screen Shot 2021-09-29 at 20 34 52" src="https://user-images.githubusercontent.com/15169499/135279785-149246b1-6e39-4dae-a019-978397d78269.png">|
=> Only show QuranReader controls when we reach the end

src/components/AudioPlayer/RepeatAudioModal/RepeatSetting.module.scss, src/components/dls/Counter/Counter.module.scss
=> fix dark mode ui

src/components/dls/Forms/Input/Input.module.scss, src/components/dls/Forms/Input/Input.stories.tsx, src/components/dls/Forms/Input/index.tsx
This PR adds `Input` component to QDC's DLS.
=> Add Input to DLS

src/components/AudioPlayer/RepeatAudioModal/RepeatAudioModal.tsx
Persist the audio repeat settings across session
=> Persist audio repeat settings

src/api.ts, src/components/AudioPlayer/AudioPlayer.tsx, src/components/AudioPlayer/AudioRepeatManager/AudioRepeatManager.tsx, src/components/AudioPlayer/Buttons/CloseButton.tsx, src/components/AudioPlayer/Buttons/DownloadAudioButton.tsx, src/components/AudioPlayer/Buttons/PlayPauseButton.tsx, src/components/AudioPlayer/PlaybackControls.tsx, src/components/AudioPlayer/QuranReaderHighlightDispatcher.tsx, src/components/AudioPlayer/RepeatButton.tsx, src/components/AudioPlayer/hooks/useActiveVerseTiming.tsx, src/components/FeedbackWidget/FeedbackWidget.tsx, src/components/QuranReader/PlayChapterAudioButton.tsx, src/components/Verse/PlayVerseAudioButton.tsx, src/redux/slices/AudioPlayer/state.ts, src/utils/apiPaths.ts, types/ApiResponses.ts, types/AudioData.ts
=> rename audioFile -> audioData

package.json, src/components/AudioPlayer/RepeatAudioModal/RepeatSetting.module.scss, src/components/dls/PopoverMenu/PopoverMenu.module.scss, src/components/dls/PopoverMenu/PopoverMenu.stories.tsx, src/components/dls/PopoverMenu/PopoverMenu.tsx, yarn.lock
TSIA
When implemented on verse actions
=> add popover menu dls

src/redux/migrations.ts, src/redux/slices/AudioPlayer/state.ts
=> create redux persist migration for repeat feature

src/components/Navbar/SettingsDrawer/ThemeSection.tsx
=> remove sepia theme for now

src/pages/_error.module.scss, src/pages/_error.tsx
=> create custom error page

src/components/AudioPlayer/Buttons/CloseButton.tsx
=> close popover menu on click close audio player

src/components/dls/Forms/Combobox/Combobox.module.scss, src/components/dls/Forms/Combobox/ComboboxItem/ComboboxItem.module.scss, src/components/dls/Forms/Select/Select.module.scss, src/components/dls/PopoverMenu/PopoverMenu.module.scss
=> fix  a few dark mode ui regressions

public/icons/east.svg, src/components/CommandBar/CommandBarBody/CommandBarBody.module.scss, src/components/CommandBar/CommandBarBody/index.tsx, src/components/CommandBar/CommandBarTrigger/CommandBarTrigger.module.scss, src/components/CommandBar/CommandBarTrigger/index.tsx, src/components/CommandBar/CommandsList/CommandList.module.scss, src/components/CommandBar/CommandsList/index.tsx, src/components/CommandBar/PreInput.tsx, src/components/CommandBar/index.tsx, src/components/DataFetcher/index.tsx, src/components/GlobalKeyboardListeners.tsx, src/components/dls/KeyboardInput/KeyboardInput.module.scss, src/pages/_app.tsx, src/pages/index.tsx, src/redux/migrations.ts, src/redux/slices/commandBar.ts, src/redux/store.ts
This PR adds a global command bar that is accessible from any page. The command bar can be opened either by clicking `cmd+k` or by clicking on the trigger in the homepage. Currently it can be used to navigate to certain Juz, Page, Hizb, Surah or Verse.
=> Add command bar

src/components/AudioPlayer/Buttons/DownloadAudioButton.tsx, src/redux/slices/AudioPlayer/persistConfig.ts, src/redux/slices/AudioPlayer/state.ts
=> save download audio state to redux

src/redux/slices/AudioPlayer/state.ts
=> fix: playfrom verse 1 doesn't work

src/components/chapters/Info/InfoPage.tsx, src/pages/[chapterId]/[verseId]/index.tsx, src/pages/[chapterId]/[verseId]/tafsirs.tsx, src/pages/[chapterId]/index.tsx, src/pages/[chapterId]/tafsirs/[tafsirId].tsx, src/pages/_error.tsx, src/pages/juz/[juzId]/index.tsx, src/pages/page/[pageId].tsx
replace import 'next/error' with our own error component
=> use custom error page for page custom error

src/components/AudioPlayer/AudioPlayer.module.scss, src/components/AudioPlayer/AudioPlayer.tsx, src/components/Navbar/Navbar.module.scss, src/components/Navbar/Navbar.tsx, src/components/QuranReader/QuranReader.module.scss, src/components/chapters/Info/Info.module.scss, src/pages/index.module.scss, src/pages/search.module.scss
=> navbar and audioplayer empty placeholder

src/components/dls/Switch/Switch.module.scss, src/components/dls/Switch/Switch.stories.module.scss, src/components/dls/Switch/Switch.stories.tsx, src/components/dls/Switch/Switch.tsx
TSIA
It doesn't really look like the reference (vercel), mainly because of the sizing. (e.g we don't have 14px font size token)
API and design is derived from https://vercel.com/design/switch
=> Create Switch DLS

src/redux/migrations.ts, src/redux/slices/QuranReader/tafsirs.ts, src/redux/store.ts
This PR removes tafsir 171 as a default tafsir since it's no longer a tafsir but a translation.
=> Remove 171 as default Tafsir

.storybook/preview.js, package.json, src/components/dls/Toast/Toast.module.scss, src/components/dls/Toast/Toast.stories.tsx, src/components/dls/Toast/Toast.tsx, src/pages/_app.tsx, yarn.lock
- This is still rough, animation is not smooth yet
- I am evaluating if other library is a better fit for our usecase. e.g https://react-hot-toast.com/
- or porting https://github.com/geist-org/react/tree/master/components/use-toasts is better
Still exploring a bit
=> Create Toast DLS

public/icons/Q_simple.svg, src/components/dls/Footer/Footer.module.scss, src/components/dls/Footer/Footer.stories.tsx, src/components/dls/Footer/Footer.tsx
=> Create footer component

src/components/QuranReader/TranslationView/TranslationText/FootnoteText.module.scss, src/components/QuranReader/TranslationView/TranslationText/FootnoteText.tsx, src/components/QuranReader/TranslationView/TranslationText/TranslationText.module.scss, src/components/QuranReader/TranslationView/TranslationText/index.tsx
This PR adds a loading indicator when loading footnotes of translations.
=> Add loading indicator to footnotes

src/components/Search/PreInput/index.tsx, src/components/dls/Button/Button.module.scss
=> fix: popular searches regression

src/pages/index.tsx
=> add separator above footer

src/components/QuranReader/QuranReader.module.scss
=> fix spacing issue

src/components/Navbar/LanguageSelector.module.scss, src/components/Navbar/LanguageSelector.tsx, src/components/Navbar/NavbarBody/NavbarBody.module.scss, src/components/Navbar/NavbarBody/index.tsx, src/components/Navbar/NavigationDrawer/NavigationDrawer.tsx, src/components/dls/Forms/Select/Select.module.scss, src/components/dls/Forms/Select/index.tsx
This PR adds a language switcher to be able to switch between locales.
|Desktop|<img width="1440" alt="Screen Shot 2021-10-31 at 22 38 12" src="https://user-images.githubusercontent.com/15169499/139622728-16cb0539-b6fb-4c9e-963c-2b9a83f6f812.png"><img width="1440" alt="Screen Shot 2021-10-31 at 22 38 18" src="https://user-images.githubusercontent.com/15169499/139622736-d25142cc-ded7-4449-9478-a4858f109f36.png">|
|Mobile|![249892885_722665125359513_5156264699444268657_n](https://user-images.githubusercontent.com/15169499/139622799-75142c26-a17b-469d-8479-7b856fe2bf19.jpg)![248422092_393057292513738_2419000836065737928_n](https://user-images.githubusercontent.com/15169499/139622796-8bcf37bd-1c1b-4c73-bd4c-542f23287cc3.jpg)|
=> Add language switcher

src/components/AudioPlayer/AudioPlayerSlider.module.scss
=> fix audio player regression

src/components/QuranReader/QuranReaderView.tsx, src/components/QuranReader/ReadingView/Line.tsx, src/components/QuranReader/ReadingView/Page.tsx, src/components/QuranReader/ReadingView/index.tsx, src/components/QuranReader/TranslationView/TranslationViewCell.tsx, src/components/QuranReader/TranslationView/index.tsx, src/components/QuranReader/utils/memoization.ts
=> Fix QuranReader memoization issue

src/components/dls/QuranWord/TextWord.tsx
TSIA
| ![before](https://user-images.githubusercontent.com/701567/140255456-fd4edc4b-5eef-4985-81c2-0f61a2115052.png)| ![after](https://user-images.githubusercontent.com/701567/140255509-15403d38-344e-4724-8991-884340c41cff.png) |
=> use indopak font

src/components/DeveloperUtility/DeveloperUtility.tsx, src/components/HomePage/HomePageImage.module.scss, src/components/HomePage/HomePageImage.tsx, src/components/HomePage/PrayerTimes.module.scss, src/components/HomePage/PrayerTimes.tsx, src/pages/index.module.scss, src/pages/index.tsx
Intitial preview of prayer times feature
=> Prayer times

src/components/HomePage/PrayerTimes.tsx
=> fix: prayer times after isha

locales/en/home.json, src/components/HomePage/PrayerTimes.tsx
=> prayer times localization

src/components/QuranReader/TranslationView/TranslationViewCell.module.scss, src/components/QuranReader/TranslationView/TranslationViewCell.tsx
=> TranslationView: arabic & translations side by side

.storybook/main.js, .storybook/preview.js, package.json, yarn.lock
This PR fixes an issue related to using `useRouter` inside the components and another issue related to `next-translate` not showing the values of translation keys.
Closes #708 
|<img width="1440" alt="Screen Shot 2021-11-08 at 14 26 19" src="https://user-images.githubusercontent.com/15169499/140700772-8eb81a9f-d615-45f0-8a83-f6dde3360ef9.png">|<img width="1440" alt="Screen Shot 2021-11-08 at 14 26 24" src="https://user-images.githubusercontent.com/15169499/140700816-054129a1-aded-4a96-8489-0a12b111d8e1.png">|
=> Fix storybook useRouter and next-translate issues

src/components/AudioPlayer/Buttons/PlayPauseButton.tsx, src/components/Navbar/NavbarBody/index.tsx, src/components/Navbar/NavigationDrawer/NavigationDrawer.tsx, src/components/Navbar/NavigationDrawer/NavigationDrawerItem.tsx, src/components/QuranReader/PlayChapterAudioButton.tsx, src/components/QuranReader/TranslationView/TranslationViewCell.module.scss, src/components/Verse/PlayVerseAudioButton.tsx, src/components/dls/Button/Button.module.scss, src/components/dls/Button/Button.tsx, src/components/dls/IconContainer/IconContainer.module.scss, src/components/dls/IconContainer/IconContainer.tsx
Closes #709
|<img width="1440" alt="Screen Shot 2021-11-08 at 11 02 53" src="https://user-images.githubusercontent.com/15169499/140682726-c54711c5-ceab-44ec-88c9-24a1172d2f2c.png">|<img width="1440" alt="Screen Shot 2021-11-08 at 11 02 58" src="https://user-images.githubusercontent.com/15169499/140682729-1deb2f4b-98d9-4e8d-bb64-c21f5c452f57.png">|
|<img width="1440" alt="Screen Shot 2021-11-08 at 11 03 08" src="https://user-images.githubusercontent.com/15169499/140682731-ea0eabb9-f524-4c81-b383-4b3742f9552c.png">|<img width="1434" alt="Screen Shot 2021-11-08 at 11 03 13" src="https://user-images.githubusercontent.com/15169499/140682734-73eed0b8-37c0-444c-aa08-55900213a9d2.png">|
|<img width="313" alt="Screen Shot 2021-11-08 at 11 03 19" …
=> Update RTL icons

src/components/QuranReader/ContextMenu.module.scss, src/components/QuranReader/ContextMenu.tsx
Closes #711 
|<img width="1440" alt="Screen Shot 2021-11-08 at 11 24 15" src="https://user-images.githubusercontent.com/15169499/140684296-01ea0bbe-9bfe-401d-89d4-e53811cc5cfb.png">|<img width="1440" alt="Screen Shot 2021-11-08 at 11 24 25" src="https://user-images.githubusercontent.com/15169499/140684305-020c36d6-8426-4400-831f-060df33418ad.png">|
|<img width="265" alt="Screen Shot 2021-11-08 at 11 24 50" src="https://user-images.githubusercontent.com/15169499/140684311-b4bf91e9-f07e-4f20-84ba-89b9925dbbd2.png">|<img width="263" alt="Screen Shot 2021-11-08 at 11 24 45" src="https://user-images.githubusercontent.com/15169499/140684308-1dc798a2-1159-4f51-ae9f-7e36b4109300.png">|
|<img width="265" alt="Screen Shot 2021-11-08 at 11 25 16" …
=> Update ContextMenu UI

src/components/dls/QuranWord/QuranWord.tsx, src/components/dls/QuranWord/onClickQuranWord.ts, src/components/dls/QuranWord/onQuranWordClick.ts
When user click QuranWord, check if the audio is currently playing, if it is
- play the audio from that word's timestamp
- otherwise, play the 'word by word audio'
=> feat: play audio from word segment when user click QuranWord

locales/en/common.json, src/components/HomePage/PrayerTimes.tsx, src/components/Navbar/SettingsDrawer/AudioSection.tsx, src/components/Navbar/SettingsDrawer/PrayerTimesSection.tsx, src/components/Navbar/SettingsDrawer/SettingsBody.tsx, src/redux/slices/prayerTimes.ts, src/redux/store.ts, src/utils/apiPaths.ts, src/utils/input.ts
=> Add prayer times settings

locales/en/home.json, src/components/HomePage/PrayerTimes.tsx
=> Hijri date internationalization

src/utils/apiPaths.ts
=> feat: hijridate to use browser's local time

src/components/chapters/ChapterHeader/ChapterHeader.module.scss, src/components/chapters/ChapterHeader/index.tsx
=> remove Q icon in chapter header

src/components/CommandBar/CommandBarBody/index.tsx
=> Command bar: remove debounce

locales/en/common.json, src/components/CommandBar/CommandBar.module.scss, src/components/CommandBar/CommandBarBase/CommandBarBase.module.scss, src/components/CommandBar/CommandBarBase/CommandBarBase.tsx, src/components/CommandBar/CommandBarBody/CommandBarBody.module.scss, src/components/CommandBar/CommandBarBody/index.tsx, src/components/CommandBar/CommandsList/CommandControl.tsx, src/components/CommandBar/CommandsList/CommandList.module.scss, src/components/CommandBar/CommandsList/CommandPrefix/CommandPrefix.module.scss, src/components/CommandBar/CommandsList/index.tsx, src/components/CommandBar/index.tsx, src/styles/theme.scss, src/styles/themes/_dark.scss
=> command bar redesign 

src/components/CommandBar/CommandBarBase/CommandBarBase.module.scss
=> fix commandbar rtl

src/components/dls/KeyboardInput/KeyboardInput.module.scss
TSIA +  Follow ups for keyboard input css
=> keyboard input direction: stay ltr

src/components/Search/SearchResults/SearchResultItem.tsx, src/components/dls/QuranWord/QuranWord.tsx
=> fix sidebar search

locales/en/common.json, src/components/CommandBar/CommandBarTrigger/CommandBarTrigger.module.scss, src/components/CommandBar/CommandBarTrigger/index.tsx, src/components/TarteelVoiceSearch/Trigger.tsx, src/pages/index.module.scss, src/pages/index.tsx
Basic command bar trigger redesign.
=> commandbar trigger design

src/components/chapters/Info/InfoPage.tsx, src/pages/[chapterId]/[verseId]/index.tsx, src/pages/[chapterId]/[verseId]/tafsirs.tsx, src/pages/[chapterId]/index.tsx, src/pages/[chapterId]/tafsirs/[tafsirId].tsx
This PR uses transliterated names for Surahs instead of translated names.
| <img width="239" alt="Screen Shot 2021-11-15 at 15 31 42" src="https://user-images.githubusercontent.com/15169499/141748426-c697fe16-df88-4850-986d-2ff074aabef1.png">|<img width="241" alt="Screen Shot 2021-11-15 at 15 31 39" src="https://user-images.githubusercontent.com/15169499/141748419-3028f631-e89f-454c-88c0-e1d20d132019.png">|
=> Use Transliterated names for Surah title

src/components/QuranReader/index.tsx
=> handle Quran Reader empty verses

locales/en/common.json, src/components/Navbar/SettingsDrawer/PrayerTimesSection.tsx
Localize a few settings strings
- Madhab
- Calculation methods
=> Localize settings

locales/en/common.json, src/components/Navbar/SettingsDrawer/SearchSelectionBody.module.scss, src/components/Navbar/SettingsDrawer/SettingsDrawer.tsx, src/components/Navbar/SettingsDrawer/TafsirSection.module.scss, src/components/Navbar/SettingsDrawer/TafsirSection.tsx, src/components/Navbar/SettingsDrawer/TafsirSelectionBody.tsx, src/redux/slices/navbar.ts
=> Search tafsirs

locales/en/common.json, src/components/Navbar/SettingsDrawer/ReciterSelectionBody.module.scss, src/components/Navbar/SettingsDrawer/ReciterSelectionBody.tsx
=> Search reciter feature

src/redux/defaultSettings/locales/bn.ts, src/redux/defaultSettings/locales/id.ts, src/redux/defaultSettings/locales/ur.ts
=> Update locales default settings

src/components/Navbar/SettingsDrawer/ReadingExperienceSection.tsx, src/utils/locale.ts
🌐🌐🌐🌐🌐🌐🌐
🌐 German
🌐. Hindi
🌐 Persian
🌐 Russian
🌐 Tamil
🌐 Turkish
🌐. Ingush
=> 7 new languages for wbw translation 🥳🥳🥳🥳🥳🥳🥳

src/components/QuranReader/api.ts, src/utils/apiPaths.ts
=> Change word translation language query

src/components/QuranReader/TranslationView/TranslationViewCell.tsx, src/components/QuranReader/utils/memoization.ts
The translations font size change isn't reflecting while changing the font size from the settings drawer
=> Fixes #782 | translation font size change not reflecting

src/components/Navbar/Drawer/Drawer.module.scss, src/components/dls/PopoverMenu/PopoverMenu.module.scss, src/styles/themes/_dark.scss, src/styles/themes/_light.scss, src/styles/themes/_sepia.scss
=> add new color-background-elevated token

src/components/dls/Toast/Toast.module.scss, src/components/dls/Toast/Toast.stories.module.scss, src/components/dls/Toast/Toast.stories.tsx, src/components/dls/Toast/Toast.tsx
Added different statuses for toast.
=> Toast status

next.config.js
Add redirect routes to support legacy ayah range paths
```
1/2/3 => 1/2-3
1/2:3 => 1/2-3
1:2:3 => 1/2-3
1-2:3 => 1/2-3
```
=> add ayah range redirect rules

next.config.js
Fix for https://feedback.quran.com/b/bugs/opening-of-link-of-footnotes-be-like/
=> add missing redirect rule 1:2-3

src/components/Navbar/SettingsDrawer/ResetButton.tsx, src/components/dls/Toast/Toast.module.scss, src/components/dls/Toast/Toast.stories.tsx, src/components/dls/Toast/Toast.tsx
=> settings drawer : reset button trigger success toast

src/components/Navbar/SettingsDrawer/QuranFontSection.module.scss, src/components/Navbar/SettingsDrawer/QuranFontSection.tsx, src/components/Navbar/SettingsDrawer/VersePreview.module.scss, src/components/Navbar/SettingsDrawer/VersePreview.tsx, src/utils/sample-verse.json, src/utils/sampleVerse.ts, src/utils/verse.ts
=> add verse preview to settings drawer

locales/en/common.json, src/components/Navbar/SettingsDrawer/Section/Footer.module.scss, src/components/Navbar/SettingsDrawer/SettingsBody.tsx, src/components/Navbar/SettingsDrawer/ThemeSection.module.scss, src/components/Navbar/SettingsDrawer/ThemeSection.tsx, src/components/Navbar/SettingsDrawer/WordByWordSection.tsx, src/components/Navbar/SettingsDrawer/WordTooltipSection.tsx, src/components/dls/Toggle/Toggle.module.scss
- update toggle transition
- fix CLS in theme switcher icon
- reorder the settings placement
=> Settings drawer follow ups

src/styles/themes/_dark.scss
- Remove the whiteish color around the surface (dark theme)
| ![image](https://user-images.githubusercontent.com/12745166/143578381-a621b1ec-a8e5-4b02-97b4-660364be95ab.png) | ![image](https://user-images.githubusercontent.com/12745166/143578311-f1891d99-8527-475c-b25a-d2de7e14ad08.png)|
| ![image](https://user-images.githubusercontent.com/12745166/143578481-2843be1c-af92-45bb-8327-99fd13f01189.png)      | ![image](https://user-images.githubusercontent.com/12745166/143578510-cdeebda7-b052-4d54-abe4-b10796980b16.png) |
=> update shadow color on dark theme

src/components/Changelog/Text.tsx, src/components/CommandBar/CommandBarTrigger/CommandBarTrigger.module.scss, src/components/HomePage/HomePageHero.module.scss, src/components/Navbar/Drawer/Drawer.module.scss, src/components/Notion/Blocks/Blocks.module.scss, src/components/Notion/Blocks/index.tsx, src/components/Notion/Page/Page.module.scss, src/components/Notion/Page/index.tsx, src/components/dls/Toast/Toast.module.scss, src/pages/product-updates/[id].tsx, src/pages/product-updates/changelog.module.scss
=> Product Updates page: design update

src/redux/defaultSettings/defaultSettings.ts, src/redux/defaultSettings/locales/ar.ts, src/redux/defaultSettings/locales/bn.ts, src/redux/defaultSettings/locales/fa.ts, src/redux/defaultSettings/locales/fr.ts, src/redux/defaultSettings/locales/id.ts, src/redux/defaultSettings/locales/it.ts, src/redux/defaultSettings/locales/ms.ts, src/redux/defaultSettings/locales/nl.ts, src/redux/defaultSettings/locales/pt.ts, src/redux/defaultSettings/locales/ru.ts, src/redux/defaultSettings/locales/sq.ts, src/redux/defaultSettings/locales/th.ts, src/redux/defaultSettings/locales/tr.ts, src/redux/defaultSettings/locales/ur.ts, src/redux/defaultSettings/locales/zh.ts
This PR updates the default settings of Translations and Tafsirs based on the locale. 
Closes #843
=> Update default settings

src/components/Navbar/Navbar.module.scss, src/components/QuranReader/ContextMenu.module.scss, src/components/QuranReader/ContextMenu.tsx, src/components/dls/Forms/Select/Select.module.scss
This is just a quick for now,
We can probably merge the navbar + context menu in the future. But not sure yet, that requires a deeper thinking.
Known issues
- On dark theme, the `text-faded` is not contrast enough with with the `background-elevated` (see the hizb text).  I will take this issue out of the scope of this PR. As this issue is not specific to this PR. I will fix it in another PR.
=> design update: context menu

src/components/Navbar/SettingsDrawer/QuranFontSection.tsx
=> fix tajweed font discoverability

src/components/QuranReader/TranslationView/TranslationViewCell.module.scss
Closes #859 
|<img width="1440" alt="Screen Shot 2021-12-03 at 06 17 16" src="https://user-images.githubusercontent.com/15169499/144518594-56bcb5db-aa49-4d11-916a-b1cfde2d4582.png">|<img width="1440" alt="Screen Shot 2021-12-03 at 06 18 48" src="https://user-images.githubusercontent.com/15169499/144518601-dcd164a7-aa08-4a24-894d-dc37b7911bab.png">|
=> Fix Arabic Translation view

README.md
Fixed old non-resolving link in readme
Click and test
| ![image](https://user-images.githubusercontent.com/64008512/144938711-4106facc-76e6-4e5d-ad2e-38c9efe973f7.png) | ![image](https://user-images.githubusercontent.com/64008512/144938774-fd02bbb0-96ae-4660-8785-700e425a29ba.png)|
=> Fix old non-resolving link

locales/ar/common.json, locales/bn/common.json, locales/en/common.json, locales/fa/common.json, locales/fr/common.json, locales/id/common.json, locales/it/common.json, locales/ms/common.json, locales/nl/common.json, locales/pt/common.json, locales/ru/common.json, locales/sq/common.json, locales/th/common.json, locales/tr/common.json, locales/ur/common.json, locales/zh/common.json, src/components/AudioPlayer/Buttons/AudioPlaybackRateMenu.tsx
This PR adds localization to the playback speed menu.
|<img width="210" alt="Screen Shot 2021-12-07 at 20 27 02" src="https://user-images.githubusercontent.com/15169499/145037601-18dfa0f3-b106-4314-b58f-c4d92d3791a5.png">|<img width="211" alt="Screen Shot 2021-12-07 at 20 26 47" src="https://user-images.githubusercontent.com/15169499/145037589-7d0f227b-606a-4b63-b3e0-81b8e08489cc.png">|
=> Localize normal playback speed

src/components/QuranReader/SidebarNavigation/PageSelection.tsx, src/utils/page.ts
This PR changes the number of pages shown in the sidebar based on the Mushaf.
=> Change page number based on Mushaf

src/components/QuranReader/SidebarNavigation/SidebarNavigation.module.scss
Try it on mobile, previously transition was a bit weird. this PR fixed it.
Compare it with https://next.quran.com
=> fix: sidebar mobile transition on mobile

sitemap-generator.js, src/api.ts, src/components/QuranReader/SidebarNavigation/SidebarNavigation.tsx, src/components/QuranReader/SidebarNavigation/SurahList.tsx, src/components/QuranReader/SidebarNavigation/SurahSelection.tsx, src/components/QuranReader/SidebarNavigation/VerseList.tsx, src/components/QuranReader/index.tsx, src/components/Verse/AdvancedCopy/VerseAdvancedCopy.tsx, src/pages/[chapterId]/[verseId]/index.tsx, src/pages/[chapterId]/[verseId]/tafsirs.tsx, src/pages/[chapterId]/index.tsx, src/pages/chapter_info/[chapterId].tsx, src/pages/surah-info/[chapterId].tsx, src/pages/surah/[chapterId]/info.tsx, src/utils/apiPaths.ts
This PR adds the ability to navigate to a Surah through its slugs e.g. Surah Al Baqarah would be accessible via `/al-baqarah` or `/2`.
=> Add Surahs slugs to the url

public/data/chapters/ar.json, public/data/chapters/bn.json, public/data/chapters/en.json, public/data/chapters/fr.json, public/data/chapters/id.json, public/data/chapters/it.json, public/data/chapters/nl.json, public/data/chapters/ru.json, public/data/chapters/tr.json, public/data/chapters/ur.json, public/data/chapters/zh.json, scripts/format-chapter-data-json.js, src/components/QuranReader/EndOfScrollingControls/TafsirControls.tsx, src/components/Search/SearchResults/SearchResultItem.tsx, src/components/Verse/VerseLink/index.tsx, src/components/Verses/BookmarkedVersesList.tsx, src/components/chapters/Info/InfoPage.tsx, src/pages/[chapterId]/[verseId]/index.tsx, src/pages/[chapterId]/[verseId]/tafsirs.tsx, src/pages/[chapterId]/index.tsx, src/utils/navigation.ts, types/Chapter.ts
This PR adds [canonical URL](https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls#rel-canonical-link-method) to our routes for better SEO.
=> [SEO] Add canonical urls

src/components/QuranReader/ReadingView/Page.module.scss
=> fix: min chapter header

src/pages/[chapterId]/[verseId]/index.tsx, src/pages/[chapterId]/index.tsx, src/utils/apiPaths.ts
This PR adds the Ayah text without any Tashkeel as the `description` meta tag.
=> [SEO] Add verse text as meta description

src/components/HomePage/PrayerTimes/PrayerTimes.module.scss
=> fix: hijri date & prayer times UI

locales/en/common.json, src/components/Navbar/SettingsDrawer/AudioSection.tsx, src/components/Navbar/SettingsDrawer/RepeatSettings.module.scss, src/components/Navbar/SettingsDrawer/RepeatSettings.tsx, src/components/Navbar/SettingsDrawer/SettingsDrawer.tsx, src/components/dls/SelectionCard/SelectionCard.tsx, src/redux/slices/navbar.ts
=> add repeat settings cue in settings drawer

src/components/chapters/Info/InfoPage.tsx, src/pages/[chapterId]/index.tsx, src/pages/juz/[juzId]/index.tsx, src/pages/page/[pageId].tsx, src/utils/locale.ts, src/utils/seo.ts
This PR address multiple issue with Open Graph meta Tags.
=> [SEO] Update Open Graph tags

src/pages/[chapterId]/[verseId]/index.tsx, src/pages/[chapterId]/index.tsx, src/utils/apiPaths.ts, src/utils/seo.ts
This PR replaces `textUthmaniSimple` with `textImlaeiSimple` because `textUthmaniSimple` remove some letters from the words.
=> Replace textUthmaniSimple with textImlaeiSimple

src/components/HomePage/HomePageHero.module.scss, src/components/dls/SelectionCard/SelectionCard.module.scss, src/styles/themes/_dark.scss
Before
After
Before
After
Some references related to dark mode
- https://www.youtube.com/watch?v=9NDLR3COU7Y&t=3s
- https://blog.prototypr.io/how-to-design-a-dark-theme-for-your-android-app-3daeb264637
=> Update dark mode color

src/components/AudioPlayer/AudioPlayer.module.scss, src/components/AudioPlayer/AudioPlayerSlider.module.scss, src/components/Navbar/Navbar.module.scss, src/components/QuranReader/ContextMenu.module.scss, src/hooks/useScrollDirection.ts
Cannot provide screenshot.
you need to compare the experience directly on your phone
=> improve navbar, context & audio player menu scrolling experience

src/pages/[chapterId]/[verseId]/tafsirs.tsx, src/utils/string.test.ts, src/utils/string.ts
This PR adds description meta tags to the Tafsirs page of a certain verse e.g. `/al-fatihah/1/tafsirs`.
=> [SEO] Add verse's Tafsirs description meta tags

src/components/Navbar/NavbarBody/NavbarBody.module.scss
=> Replace start with flex-start for Navbar

src/components/Navbar/SearchDrawer/Footer/Footer.module.scss, src/components/Navbar/SearchDrawer/Footer/index.tsx
=> ui fix: tarteel attribution styling

src/components/QuranReader/TafsirView/TafsirView.module.scss
=> Tafsir view minor UI update

src/components/dls/Footer/Footer.module.scss, src/components/dls/Footer/Footer.tsx
=> Update footer logo

src/components/Navbar/SettingsDrawer/ReciterSelectionBody.tsx, src/components/Navbar/SettingsDrawer/TranslationSelectionBody.tsx, src/components/dls/Forms/Input/Input.module.scss
=> update input UI for reciter, translation, and tafsir selection

src/components/HomePage/HomePageHero.module.scss, src/components/HomePage/HomePageHero.tsx
- add link preload
- fallback to background color when the image is not loaded yet
=> Preload homepage image + add fallback color

src/components/Notion/Blocks/index.tsx, src/components/Notion/Page/index.tsx, src/components/chapters/Info/index.tsx, src/pages/about-us.tsx, src/pages/apps.tsx
This PR adds missing `alt` to images.
=> [SEO] Add missing Image alt prop

src/components/QuranReader/TranslationView/QuranReflectButton.tsx, src/components/QuranReader/TranslationView/TranslationViewCell.tsx, src/components/Verse/OverflowVerseActionsMenuBody.tsx, src/utils/navigation.ts
Add quran reflect in translationview cell
=> Add quran reflect button

src/components/AudioPlayer/Buttons/PlayPauseButton.tsx, src/components/QuranReader/SidebarNavigation/SidebarNavigation.tsx, src/components/QuranReader/SidebarNavigation/SurahList.tsx, src/components/QuranReader/SidebarNavigation/SurahSelection.tsx, src/components/QuranReader/SidebarNavigation/VerseList.tsx, src/components/QuranReader/index.tsx, src/hooks/useChapterId.ts
This PR fixes an exception when:
1. Navigating to `/page/300`
2. Navigating to `/36:1/tafsirs/169`
3. Navigating to `/2:255`
Even without any exceptions in the case of navigating to `/page/5` it shows the wrong selected Surah.
=> Fix VerseList issue

locales/en/common.json, src/components/Navbar/LanguageSelector.module.scss, src/components/Navbar/LanguageSelector.tsx, src/components/dls/Footer/Footer.module.scss, src/components/dls/Footer/Links.tsx
- Networks ⇒ Network
- localize the title
- import slug from `getAllChaptersData` instead of hardcoded
- Quran.com copyright not readable
- sitemap privacy can use the same color
- Tarteel ⇒ Tarteel.ai
- Other links ⇒ Popular links
- Add other popular surah
- langugage selector, add border + chevron
- The spacing under the quran.com logo isn't consistent with the spacing under the other titles
- make it 2 columns on mobile
=> Footer update

package.json, src/components/Navbar/Drawer/index.tsx, src/components/Navbar/LanguageSelector.tsx, src/components/Navbar/NavbarBody/index.tsx, src/components/Navbar/SettingsDrawer/AudioSection.tsx, src/components/Navbar/SettingsDrawer/PrayerTimesSection.tsx, src/components/Navbar/SettingsDrawer/QuranFontSection.tsx, src/components/Navbar/SettingsDrawer/ResetButton.tsx, src/components/Navbar/SettingsDrawer/SettingsDrawer.tsx, src/components/Navbar/SettingsDrawer/TafsirSection.tsx, src/components/Navbar/SettingsDrawer/TafsirSelectionBody.tsx, src/components/Navbar/SettingsDrawer/ThemeSection.tsx, src/components/Navbar/SettingsDrawer/TranslationSection.tsx, src/components/Navbar/SettingsDrawer/TranslationSelectionBody.tsx, src/components/Navbar/SettingsDrawer/WordByWordSection.tsx, src/components/Navbar/SettingsDrawer/WordTooltipSection.tsx, src/lib/firebase.ts, src/utils/eventLogger.ts, yarn.lock
This PR adds Firebase Analytics logging infrastructure.
=> [Logging] Add Firebase Analytics infrastructure

src/components/Navbar/SettingsDrawer/ReciterSelectionBody.tsx
=> sort reciter by name

locales/en/home.json, src/components/HomePage/HomePageWelcomeMessage.tsx
=> remove discord join link in homepage

src/styles/global.scss
=> fix: windows select dropdown style

src/components/CommandBar/CommandBarBody/index.tsx, src/components/CommandBar/CommandBarTrigger/index.tsx, src/components/Navbar/SearchDrawer/AdvancedSearchLink.tsx, src/components/Navbar/SearchDrawer/Footer/index.tsx, src/components/Navbar/SearchDrawer/Header/index.tsx, src/components/Navbar/SearchDrawer/SearchDrawer.tsx, src/components/Search/NavigationItem/index.tsx, src/components/Search/PreInput/index.tsx, src/components/Search/SearchBodyContainer.tsx, src/components/Search/SearchHistory/index.tsx, src/components/Search/SearchResults/SearchResultItem.tsx, src/components/Search/SearchResults/SearchResults.module.scss, src/components/Search/SearchResults/index.tsx, src/components/TarteelVoiceSearch/BodyContainer/SearchResults.tsx, src/components/TarteelVoiceSearch/Trigger.tsx, src/components/dls/Link/Link.tsx, src/hooks/useTarteelVoiceSearch.ts, src/pages/search.tsx
This PR adds logging to:
1. Command bar
2. Search drawer
3. Search page
=> [Logging] Search

locales/en/common.json, src/components/CommandBar/CommandBarBody/CommandBarBody.module.scss, src/components/TarteelVoiceSearch/BodyContainer/PartialResult/PartialResult.module.scss, src/components/TarteelVoiceSearch/BodyContainer/PartialResult/index.tsx, src/components/TarteelVoiceSearch/BodyContainer/index.tsx
fix #979 #978 
We discuss more about the wording iA. This PR fixed the visual hierarchy problem.
=> fix visual hierarchy in voice search

src/components/QuranReader/TranslationView/TranslationText/FootnoteText.module.scss, src/components/QuranReader/TranslationView/TranslationText/FootnoteText.tsx
=> update footnote design

src/components/dls/Modal/Content.module.scss, src/styles/themes/_dark.scss, src/styles/themes/_light.scss
My friend was suggesting this, for a better focus.
Before
After
Before
After
=> update backdrop color for a better focus

src/components/QuranReader/TafsirView/TafsirBody.tsx, src/utils/locale.ts
Use profer font for tafsir content, we've already defined fonts for each language. Let's use them.
=> use language specific font for tafsir content

src/components/QuranReader/TafsirView/LanguageAndTafsirSelection.tsx, src/components/QuranReader/TafsirView/TafsirView.module.scss
=> tafsir selection skeleton

src/components/QuranReader/TafsirView/TafsirBody.tsx, src/components/QuranReader/TafsirView/TafsirVerseAction.tsx
default path for tafsir is now  https://next.quran.com/2:3/tafsirs/169 instaed of https://next.quran.com/2/3/tafsirs?tafsirId=169 
Because we cannot read querystring `?tafsirId=169` in getStaticProps
=> use param instead of querystring for SSG

src/components/QuranReader/TafsirView/LanguageAndTafsirSelection.tsx, src/components/QuranReader/TafsirView/SurahAndAyahSelection.tsx, src/components/QuranReader/TafsirView/TafsirBody.tsx, src/utils/locale.ts
This PR adds localization to the TafsirView.
|<img width="872" alt="Screen Shot 2021-12-28 at 20 14 25" src="https://user-images.githubusercontent.com/15169499/147570225-239c0a45-5f97-49a6-aaae-3edbc654fe98.png">|<img width="875" alt="Screen Shot 2021-12-28 at 20 14 14" src="https://user-images.githubusercontent.com/15169499/147570217-c288ca6c-df5e-4a48-abd1-41ec152f8b11.png">|
|<img width="921" alt="Screen Shot 2021-12-28 at 20 14 27" src="https://user-images.githubusercontent.com/15169499/147570229-6c2d0dd6-71e4-4a91-9647-33bf31d3f5f4.png">|<img width="870" alt="Screen Shot 2021-12-28 at 20 14 39" src="https://user-images.githubusercontent.com/15169499/147570234-98f2bd29-369b-449f-bc46-db80d093bfc8.png">|
|<img width="910" alt="Screen Shot …
=> Localize TafsirView options

public/data/chapters/ar.json, public/data/chapters/bn.json, public/data/chapters/en.json, public/data/chapters/fa.json, public/data/chapters/ms.json, public/data/chapters/pt.json, public/data/chapters/ru.json, public/data/chapters/sq.json, public/data/chapters/th.json, public/data/chapters/ur.json, src/components/HomePage/QuickLinks/index.tsx
- Fix slugs of quick links 
- Fix surah slugs, all slugs are roman characters now
- Use Surah names instead of English translation if translated name of surah is missing for the language 
=> Surah slugs

src/pages/[chapterId]/[verseId]/tafsirs.module.scss
=> tafsirview: fix mobile padding

src/components/QuranReader/TafsirView/TafsirBody.tsx, src/components/QuranReader/TafsirView/TafsirVerseAction.tsx, src/components/dls/ContentModal/ContentModal.module.scss, src/components/dls/ContentModal/ContentModal.tsx, src/pages/[chapterId]/[verseId]/tafsirs.tsx, src/pages/[chapterId]/tafsirs/[tafsirId].tsx
=> sticky header mobile, contentModal

src/styles/themes/_light.scss
=> make secondary color lighter

src/styles/themes/_dark.scss
=> update highlight color on dark theme

src/components/Navbar/Drawer/Drawer.module.scss
=> fix tarteel attribution position

src/utils/locale.ts
This PR fixes an exception that gets thrown when switching to a Spanish translation.
=> Fix translation change issue

src/pages/[chapterId]/[verseId]/index.tsx, src/pages/[chapterId]/[verseId]/tafsirs.tsx
This PR updates the logic of validating invalid paths of verses which cause the app to throw and exception when navigating to the following urls:
- `/an-nas/123`
- `/22/115-116`
- `/1/55/tafsirs`
- `/98/load_verses?start=98%3A5&reading=true&font=v1&translations=131%2C20`
=> Fix invalid paths validation

public/icons/auto.svg, src/components/Navbar/SettingsDrawer/ThemeSection.tsx
=> update auto icon

src/components/Navbar/SettingsDrawer/RepeatSettings.module.scss
=> fix: repeat settings moved UI

src/components/Search/PreInput/index.tsx
Closes #997 
|<img width="387" alt="Screen Shot 2022-01-02 at 13 16 33" src="https://user-images.githubusercontent.com/15169499/147867899-051dbe6b-2d61-456d-b81b-ed2396adcfec.png">|<img width="384" alt="Screen Shot 2022-01-02 at 13 16 39" src="https://user-images.githubusercontent.com/15169499/147867900-c2c1ce91-2128-4ba6-99eb-88ad84386612.png">|
=> Localize search's Pre-Input screen

src/redux/Provider.tsx
How to test
1. Play an audio
2.  navigate to new page
the audio should be still playing
=> fix: audio player stopped when navigating to new page

src/components/Navbar/SettingsDrawer/TranslationSelectionBody.tsx
=> feat: sort translations

src/components/QuranReader/TranslationView/TranslatioViewCellSkeleton.tsx, src/components/QuranReader/TranslationView/TranslationViewSkeleton.module.scss, src/components/QuranReader/TranslationView/TranslationViewSkeleton.tsx, src/components/QuranReader/index.tsx, src/components/dls/Skeleton/Skeleton.module.scss, src/components/dls/Skeleton/Skeleton.tsx
=> Skeleton translation view cell

src/components/QuranReader/TafsirView/TafsirBody.tsx, src/components/QuranReader/TafsirView/TafsirEndOfScrollingActions.module.scss, src/components/QuranReader/TafsirView/TafsirEndOfScrollingActions.tsx, src/components/QuranReader/TafsirView/TafsirVerseAction.tsx, src/components/dls/ContentModal/ContentModal.tsx, src/pages/[chapterId]/[verseId]/tafsirs.tsx, src/pages/[chapterId]/tafsirs/[tafsirId].tsx, src/utils/navigation.ts
=> tafsir: add next and prev button

next-env.d.ts, package.json, src/components/QuranReader/TranslationView/index.tsx, src/components/Verse/OverflowVerseActionsMenu.tsx, yarn.lock
This PR adds windowing to the translation view.
=> [Windowing] Translation view windowing

locales/en/common.json, src/components/AudioPlayer/AudioRepeatManager/AudioRepeatManager.tsx, src/components/AudioPlayer/RepeatAudioModal/RepeatAudioModal.tsx, src/components/AudioPlayer/RepeatAudioModal/SelectRepetitionMode.tsx
=> Repeat settings: add option to repeat full surah

src/components/AudioPlayer/RepeatAudioModal/RepeatAudioModal.tsx, src/components/AudioPlayer/RepeatAudioModal/RepeatSetting.tsx
=> feat(repeat-settings): repeat ∞ after "3"

src/components/QuranReader/ReadingView/index.tsx, src/components/QuranReader/TranslationView/TranslationViewCell.module.scss, src/components/QuranReader/TranslationView/TranslationViewCell.tsx, src/components/QuranReader/TranslationView/index.tsx, src/components/Verse/VerseText.tsx
This PR adds chapter header component to the beginning of the virtualized list instead of outside of it.
=> [Windowing] Add Header to List

public/icons/auto.svg
| <img width="154" alt="image" src="https://user-images.githubusercontent.com/12745166/148635743-e8aefcdf-ec73-4c7f-a12a-2859f581da9b.png"> | <img width="285" alt="image" src="https://user-images.githubusercontent.com/12745166/148635732-9492b69c-2a9a-4c46-8e10-f6c6744aad6b.png"> |
=> fix: auto icon color

src/components/AudioPlayer/RepeatAudioModal/RepeatSetting.module.scss, src/components/AudioPlayer/RepeatAudioModal/SelectRepetitionMode.tsx, src/components/dls/Modal/_constants.scss
=> ui update:  repeat settings

src/components/Verses/BookmarkedVersesList.tsx
Using this format similar to this 😅
=> Add surah name to bookmarked section

src/components/Verses/BookmarkedVersesList.module.scss, src/components/Verses/BookmarkedVersesList.tsx
=> fix: bookmark mobile broken layout

.vscode/settings.json, locales/en/common.json, locales/en/radio.json, src/components/Navbar/NavigationDrawer/NavigationDrawerBody/index.tsx, src/components/dls/Footer/Links.tsx, src/pages/radio.tsx
=> Quran Radio side menu

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/FUNDING.yml, .github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/question.yml, .github/SECURITY.md, .github/SUPPORT.md, .github/semantic.yml, .gitignore
- Add issue template 
- Placeholder for adding contribution and code of conduct guides 
=> docs: add issue template

src/components/Navbar/SettingsDrawer/VersePreview.tsx, src/components/QuranReader/ReadingView/WordActionsMenu/WordActionsMenu.module.scss, src/components/QuranReader/ReadingView/WordActionsMenu/index.tsx, src/components/QuranReader/ReadingView/WordPopover/WordPopover.module.scss, src/components/QuranReader/ReadingView/WordPopover/index.tsx, src/components/QuranReader/ReadingView/groupLinesByVerses.ts, src/components/QuranReader/TafsirView/TafsirBody.tsx, src/components/QuranReader/TranslationView/TranslationViewCell.module.scss, src/components/Verse/OverflowVerseActionsMenu.tsx, src/components/Verse/OverflowVerseActionsMenuBody.module.scss, src/components/Verse/OverflowVerseActionsMenuBody.tsx, src/components/Verse/VerseText.tsx, src/components/dls/ClickableHoverCard/ClickableHoverCard.stories.tsx, src/components/dls/ClickableHoverCard/index.tsx, src/components/dls/Popover/index.tsx, src/components/dls/QuranWord/QuranWord.module.scss, src/components/dls/QuranWord/QuranWord.tsx, src/redux/slices/QuranReader/readingViewVerse.ts, src/redux/store.ts, src/utils/sample-verse.json, src/utils/verse.ts
This PR adds verse actions menu for the reading view.
=> Add reading view verse actions menu

src/components/QuranReader/SidebarNavigation/SidebarNavigation.module.scss, src/components/QuranReader/SidebarNavigation/SidebarNavigation.tsx, src/components/QuranReader/SidebarNavigation/SidebarSelectionSkeleton.module.scss, src/components/QuranReader/SidebarNavigation/SidebarSelectionSkeleton.tsx
resolves #896 
| ![image](https://user-images.githubusercontent.com/58295120/151029337-c6dcbcf2-1e3f-4d7a-aaf9-8169a6938bdb.png) | ![image](https://user-images.githubusercontent.com/58295120/151029393-4b168c44-8c42-4ecf-9298-2c9d0e5a3435.png) |
=> Add sidebar navigation skeleton

src/components/Navbar/SettingsDrawer/SearchSelectionBody.module.scss, src/components/Navbar/SettingsDrawer/TranslationSelectionBody.tsx
resolves #932 
| ![image](https://user-images.githubusercontent.com/58295120/151037965-738d0a74-00d2-472e-8b7b-5182f67d0742.png) | ![image](https://user-images.githubusercontent.com/58295120/151038039-79cad20f-1750-4ed0-b90b-00f974222b3e.png) |
=> use DLS checkbox instead of the default one

src/components/QuranReader/ReadingView/WordActionsMenu/index.tsx, src/components/QuranReader/ReadingView/WordPopover/index.tsx, src/components/QuranReader/TafsirView/TafsirVerseAction.tsx, src/components/QuranReader/TranslationView/QuranReflectButton.tsx, src/components/QuranReader/TranslationView/ShareVerseButton.tsx, src/components/Verse/OverflowVerseActionsMenu.tsx, src/components/Verse/OverflowVerseActionsMenuBody.tsx, src/components/Verse/PlayVerseAudioButton.tsx, src/components/Verse/VerseActionAdvancedCopy.tsx, src/components/dls/QuranWord/QuranWord.tsx
This PR adds logging to the ReadingView actions menu
=> Log ReadingView actions menu

i18n.json, locales/en/reciter.json, src/api.ts, src/components/Navbar/SettingsDrawer/ReciterSelectionBody.tsx, src/components/Reciter/QuranReciterListHero.module.scss, src/components/Reciter/QuranReciterListHero.tsx, src/components/Reciter/RecitersList.module.scss, src/components/Reciter/RecitersList.tsx, src/pages/reciters/index.tsx, src/pages/reciters/reciterPage.module.scss
=> Reciter list page

src/components/Navbar/SettingsDrawer/ReciterSelectionBody.module.scss, src/components/Navbar/SettingsDrawer/ReciterSelectionBody.tsx
=> reciter selection: remove default recitation style

src/components/Radio/CuratedStationList.tsx, src/components/Radio/ReciterStationList.tsx, src/components/dls/Card/Card.module.scss, src/components/dls/Card/Card.tsx
Clicking reciter name in reciter station list should navigate user to reciter page
=> Reciter station list -> reciter page navigation

src/pages/[chapterId]/[verseId]/index.tsx, src/utils/apiPaths.ts
=> fix: Ayah range page

src/components/Radio/ReciterStationList.tsx, src/pages/radio.tsx
=> ISR radio page

src/components/Verses/BookmarkedVersesList.module.scss
=> fix spacing between bookmark items

src/components/QuranReader/ReadingView/hooks/useScrollToVirtualizedVerse.ts, src/components/QuranReader/ReadingView/index.tsx, src/components/QuranReader/TranslationView/hooks/useScrollToVirtualizedVerse.ts
This PR makes it more precise to scroll to a verse in the virtualized list of verses/pages.
=> Update scroll to verse hook

.dockerignore, Dockerfile, next.config.js
Followed the instructions here: https://nextjs.org/docs/deployment#docker-image
Ran the docker container locally and ran on localhost as expected
=> Set-up docker

Dockerfile
=> Revert to node alpine

build.yml
=> Add notion env variables to build.yml

src/components/QuranReader/ReadingView/PageContainer.tsx, src/components/QuranReader/ReadingView/index.tsx, src/components/QuranReader/TranslationView/index.tsx, src/components/QuranReader/api.ts, src/pages/page/[pageId].tsx
This PR fixes the issue of missing verses for certain pages/juzs e.g. `/page/582`.
=> Update by_page API params

src/lib/firebase.ts, src/utils/eventLogger.ts
=> Disable firebase on non-prod environments

src/components/HomePage/HomePageHero.module.scss
=> Update hero image on sepia theme

src/components/Reciter/QuranReciterListHero.module.scss, src/pages/reciters/reciterPage.module.scss
=> adjust background color for sepia theme

src/components/QuranReader/TafsirView/TafsirBody.tsx
Visit https://next.quran.com/3:23/tafsirs/en-tafisr-ibn-kathir
and change the verse, it will not update the content. This PR is fixing that issue
=> fix: unable to switch verse number in tafsir ISR

src/components/QuranReader/TafsirView/TafsirBody.tsx, src/components/QuranReader/TafsirView/TafsirEndOfScrollingActions.tsx, src/utils/tafsir.ts
Previously clicking "next" and "prev" in tafsir view, will update the verse number to +1 or -1. But some tafsirs are for group of verses. So +1 and -1 is not enough
=> Tafsir group navigation

src/components/AudioPlayer/MediaSessionApiListeners.tsx
Previously we're only using placeholder. Now we update the title and artist/description according to current playing audio
=> Implement audio player media session

src/styles/global.scss
I am still not 100% sure why this thing happend and why removing this code fixed the issue. Need some input from @osamasayed 
- open normal next.quran.com with firefox
- compare it with the preview in this PR
=> fix: firefox direction alignment issue

src/components/QuranReader/PlayChapterAudioButton.tsx
Fix:
- when playing radio, and click "play audio", it remains in radio mode. This PR fixed the issue
- when the audio is playing, the audio player still says "Play Audio" not "pause audio". This PR implement the "Pause audio"
=> chapter header: update play audio mode

src/components/HomePage/PlayRadioButton.tsx, src/components/Radio/CuratedStationList.tsx, src/components/Reciter/ReciterInfo.tsx, src/components/dls/Card/Card.tsx
|<img width="1440" alt="Screen Shot 2022-02-07 at 19 17 28" src="https://user-images.githubusercontent.com/15169499/152787070-9236f65d-49f6-4732-828f-5d4fae85e261.png">|<img width="1440" alt="Screen Shot 2022-02-07 at 19 17 33" src="https://user-images.githubusercontent.com/15169499/152787088-2734b1e7-22a6-4c4f-bece-5941918b79c6.png">|
|<img width="394" alt="Screen Shot 2022-02-07 at 19 17 46" src="https://user-images.githubusercontent.com/15169499/152787093-c4317929-ab55-4f61-a51e-739d266ac50e.png">|<img width="390" alt="Screen Shot 2022-02-07 at 19 17 52" src="https://user-images.githubusercontent.com/15169499/152787100-c0316f95-0e16-46df-89d5-9323d2367cf8.png">|
=> Fix flipped RTL radio icon

release.yml
=> Invalidate AWS cache on release

release.yml
=> Add distribution id token

src/components/QuranReader/ReadingView/PageContainer.tsx
This PR fixes the issue where page 2 verses were showing 10 instead of 5.
|<img width="341" alt="Screen Shot 2022-02-08 at 11 30 03" src="https://user-images.githubusercontent.com/15169499/152918859-3e6f1b23-b16e-4e36-8224-185b99d306c3.png">|<img width="325" alt="Screen Shot 2022-02-08 at 11 29 33" src="https://user-images.githubusercontent.com/15169499/152918854-d7274452-b99f-4f31-bf21-45914211c5fa.png">|
=> Fix exceeding page verses

src/components/QuranReader/ReadingView/index.tsx
This PR adds the ability to navigate to the next/previous page by clicking the up/down keyboard keys.
=> Add ReadingView page navigation keyboard shortcuts

src/components/QuranReader/ReadingView/index.tsx, src/components/dls/Button/Button.tsx
This PR adds tooltips to the page navigation buttons of the Reading View.
=> Add tooltip to ReadingView page nav buttons

release.yml
=> run cache invalidation if waiting on ecs fails

src/components/QuranReader/ReadingView/index.tsx, src/components/dls/Button/Button.tsx, src/components/dls/KeyboardInput/KeyboardInput.module.scss, src/components/dls/KeyboardInput/index.tsx
|<img width="204" alt="Screen Shot 2022-02-08 at 22 05 15" src="https://user-images.githubusercontent.com/15169499/153014808-84ae67d1-ac9d-4857-aef5-1cb5a28593e1.png">|<img width="225" alt="Screen Shot 2022-02-08 at 22 06 32" src="https://user-images.githubusercontent.com/15169499/153014814-44829ed2-1ce1-4e72-b278-88549f969a3a.png">|
=> Add keyboard input to Reading view navigation buttons tooltip

src/components/QuranReader/ReadingView/PageNavigationButtons/PageNavigationButtons.module.scss, src/components/QuranReader/ReadingView/PageNavigationButtons/index.tsx, src/components/QuranReader/ReadingView/ReadingView.module.scss, src/components/QuranReader/ReadingView/index.tsx
This PR fixes ReadingView UI when the audio player is opened.
|<img width="1440" alt="Screen Shot 2022-02-11 at 22 12 38" src="https://user-images.githubusercontent.com/15169499/153617989-693e6aa0-c1e8-47d1-82fd-ca6c12f03196.png">|<img width="1440" alt="Screen Shot 2022-02-11 at 22 12 45" src="https://user-images.githubusercontent.com/15169499/153618007-6f7434a9-2fed-43fb-9f4f-2ff095f849d7.png">|
=> Fix ReadingView page navigation buttons when player is opened

src/components/QuranReader/ReadingView/Page.module.scss, src/components/QuranReader/ReadingView/PageContainer.tsx, src/components/QuranReader/ReadingView/PageFooter.module.scss, src/components/QuranReader/ReadingView/ReadingViewSkeleton.module.scss, src/components/QuranReader/ReadingView/ReadingViewSkeleton.tsx, src/components/QuranReader/ReadingView/index.tsx, src/styles/_constants.scss, src/styles/_utility.scss, src/utils/page.ts
This PR updates the skeleton dimensions of the Reading View to solve the layout shift issue when navigating between pages.
=> Update ReadingView Skeleton

src/api.ts, src/components/QuranReader/TranslationView/index.tsx, src/components/QuranReader/api.ts, src/pages/[chapterId]/[verseId]/index.tsx, src/pages/[chapterId]/index.tsx, src/pages/juz/[juzId]/index.tsx, src/pages/page/[pageId].tsx, types/ApiResponses.ts, types/MetaData.ts
This PR fixes missing verses due to initialData not having full page verses.
|<img width="483" alt="Screen Shot 2022-02-15 at 09 40 41" src="https://user-images.githubusercontent.com/15169499/153982385-687a1abb-8313-48be-8487-75c8ea68ba04.png">|<img width="562" alt="Screen Shot 2022-02-15 at 09 40 35" src="https://user-images.githubusercontent.com/15169499/153982372-1c975fbc-707f-44fe-8399-afbaddcfbfc9.png">|
=> Fix missing verses

next.config.js
Reverts quran/quran.com-frontend-next#1245
=> Revert "Disable PWA"

src/components/Verse/OverflowVerseActionsMenuBody.tsx, src/components/Verse/OverflowVerseActionsMenyBody.module.scss
|<img width="173" alt="Screen Shot 2022-02-16 at 07 36 32" src="https://user-images.githubusercontent.com/15169499/154173717-33e957a4-6c2b-42c2-a28b-e718baf61110.png">|<img width="179" alt="Screen Shot 2022-02-16 at 07 36 05" src="https://user-images.githubusercontent.com/15169499/154173709-4fa209a7-0d1d-4230-912c-26ccd3952cca.png">|
=> Remove Reflect and share buttons on mobile

src/components/QuranReader/ReadingView/WordActionsMenu/WordActionsMenu.module.scss
|<img width="203" alt="Screen Shot 2022-02-16 at 09 44 35" src="https://user-images.githubusercontent.com/15169499/154186428-fd77797e-eb0e-4664-9498-5f0c8133d8e1.png">|<img width="200" alt="Screen Shot 2022-02-16 at 09 44 48" src="https://user-images.githubusercontent.com/15169499/154186435-ec94427e-ef8e-4215-b448-1fe99a46bf2d.png">|
=> Update Speia color of verse actions menu

src/components/QuranReader/SidebarNavigation/ScrollableSelection.tsx, src/components/QuranReader/SidebarNavigation/SurahList.tsx, src/components/QuranReader/SidebarNavigation/VerseList.tsx
In Sidebar Navigation try
* verse navigation
* surah navigation
* page navigation
* juz navigation
How to test
* Open surah sidebar navigation, write a value in the inputbox. For example write `Verse` `33` and then press enter. 
* it should navigate you to verse 33 in the current chapter
=> Sidebar navigation: UX when pressing `Enter`

src/api.ts, src/components/QuranReader/TafsirView/LanguageAndTafsirSelection.tsx, src/components/QuranReader/TafsirView/TafsirBody.tsx, src/components/QuranReader/TafsirView/TafsirEndOfScrollingActions.tsx, src/components/QuranReader/TafsirView/TafsirVerseText/index.tsx, src/pages/[chapterId]/[verseId]/tafsirs.tsx, src/pages/[chapterId]/tafsirs/[tafsirId].tsx, src/utils/verse.ts, types/ApiResponses.ts
This PR fixes the issue of missing verse text when accessing a verse's Tafsir through the url e.g. https://beta.quran.com/2:10/tafsirs/en-tafisr-ibn-kathir and also the exception thrown when accessing some tafsir urls e.g. https://beta.quran.com/al-baqarah/10/tafsirs.
|<img width="681" alt="Screen Shot 2022-02-18 at 19 51 47" src="https://user-images.githubusercontent.com/15169499/154686428-035594ca-5d83-408c-a48a-8127a29ab7a4.png">|<img width="659" alt="Screen Shot 2022-02-18 at 19 51 51" src="https://user-images.githubusercontent.com/15169499/154686441-b0a17928-f8a9-45f2-b33b-7a78f20fa781.png">|
=> Fix Tafsir issues

src/components/QuranReader/SidebarNavigation/SidebarNavigation.module.scss
=> fix: sidebar styling stuff

src/components/QuranReader/ReadingView/hooks/useScrollToVirtualizedVerse.ts, src/components/QuranReader/TranslationView/TranslationPage/index.tsx, src/components/QuranReader/TranslationView/TranslationView.module.scss, src/components/QuranReader/TranslationView/TranslationViewCell.tsx, src/components/QuranReader/TranslationView/TranslationViewSkeleton.tsx, src/components/QuranReader/TranslationView/hooks/useScrollToVirtualizedVerse.ts, src/components/QuranReader/TranslationView/index.tsx, types/ScrollAlign.ts
This PR updates the architecture of the TranslationView which groups verses per a page and let each page handle its own fetching logic. This improves the experience by ensuring the verses will be verses the moment the page is visible.
=> Update Translation View fetching

src/components/QuranReader/ReadingView/WordActionsMenu/WordActionsMenu.module.scss, src/components/QuranReader/ReadingView/WordPopover/WordPopover.module.scss
=> fix: word actions color on sepia mode

src/styles/themes/_sepia.scss
=> fix: sepia color

src/components/QuranReader/TafsirView/TafsirView.module.scss
|<img width="635" alt="Screen Shot 2022-02-20 at 16 00 26" src="https://user-images.githubusercontent.com/15169499/154835572-d7cdee20-27fb-4545-9878-25a9ca6d13a3.png">|<img width="634" alt="Screen Shot 2022-02-20 at 16 00 34" src="https://user-images.githubusercontent.com/15169499/154835577-a9f5c849-ee0d-4ab0-aa28-c937357e963a.png">
=> Update Tafsir line height

src/components/QuranReader/ReadingView/TranslationsButton/index.tsx, src/components/QuranReader/ReadingView/TranslationsView/index.tsx, src/utils/apiPaths.ts, types/ApiResponses.ts
This PR fixes the exception thrown when opening the translations of a verse from the ReadingView.
=> Fix ReadingView translations exception

src/components/QuranReader/TafsirView/TafsirBody.tsx, src/components/QuranReader/TafsirView/TafsirText/TafsirText.module.scss, src/components/QuranReader/TafsirView/TafsirText/index.tsx, src/components/QuranReader/TafsirView/TafsirView.module.scss, src/components/dls/Counter/Counter.module.scss
This PR adds the ability to change the font size of the Tafsir content.
| ------ |
|<img width="864" alt="Screen Shot 2022-02-21 at 15 06 18" src="https://user-images.githubusercontent.com/15169499/154913860-be9d3da6-4b25-4815-bbd0-90424d07ea66.png">|
=> Change Tafsir's font size

src/components/QuranReader/ReadingView/PageContainer.tsx, src/components/QuranReader/ReadingView/index.tsx, src/components/QuranReader/TranslationView/TranslationPage/index.tsx, src/components/QuranReader/TranslationView/index.tsx, src/components/QuranReader/api.ts, src/pages/juz/[juzId]/index.tsx
This PR adds SSR support for Juz verses.
=> SSR juz verses

src/components/Reciter/ReciterInfo.module.scss, src/components/Reciter/ReciterInfo.tsx, src/pages/reciters/[reciterId]/index.tsx
This PR strips the biography of a reciter from HTML tags.
|<img width="1440" alt="Screen Shot 2022-02-22 at 18 56 35" src="https://user-images.githubusercontent.com/15169499/155128069-eb9c2e5d-ebdf-4b78-8db0-a61c8373d2a8.png">|<img width="1440" alt="Screen Shot 2022-02-22 at 18 56 30" src="https://user-images.githubusercontent.com/15169499/155128048-629f2f2c-16c7-488f-87ac-a51275d575e5.png">|
=> Strip reciter's bio HTML

src/components/QuranReader/ReadingView/WordActionsMenu/WordActionsMenu.module.scss
=> update word action background color

src/components/QuranReader/ReadingView/Page.module.scss
|<img width="262" alt="Screen Shot 2022-02-25 at 11 14 29" src="https://user-images.githubusercontent.com/15169499/155652679-d9d70c6c-139c-4502-9d1f-703d46803bd6.png">|<img width="267" alt="Screen Shot 2022-02-25 at 11 14 23" src="https://user-images.githubusercontent.com/15169499/155652667-345fa209-6eb9-4426-a201-e729bdca4fae.png">|
=> Fix mobile flipped direction of text

src/components/QuranReader/ReadingView/PageContainer.tsx, src/components/QuranReader/ReadingView/index.tsx, src/components/QuranReader/TranslationView/hooks/useScrollToVirtualizedVerse.ts, src/components/QuranReader/TranslationView/index.tsx, src/components/QuranReader/utils/page.ts
This PR fixes the issue of no navigating when Prev/Next navigation buttons are clicked in ReadingView.
=> Fix Next/Prev navigation

src/components/QuranReader/QuranReader.module.scss
=> fix: end of surah actions hidden

src/components/QuranReader/ReadingView/Page.tsx, src/components/QuranReader/hooks/useIsFontLoaded.ts, src/components/Verse/PlainVerseText/index.tsx, src/components/Verse/VerseText.tsx
This PR refactors the code by adding `useIsFontLoaded` hook.
=> Refactor isFontLoaded

src/components/QuranReader/TranslationView/TranslationViewCell.module.scss, src/components/dls/Button/Button.module.scss
=> translation view cell actions, no hover effect on mobile

src/hooks/useTarteelVoiceSearch.ts
This PR fixes the issue of un-released microphone on Websocket error.
=> Release Microphone on websocket error

locales/en/common.json, src/components/CommandBar/CommandBarBody/index.tsx, src/components/CommandBar/CommandsList/CommandPrefix/index.tsx, src/components/CommandBar/CommandsList/index.tsx, src/utils/navigation.ts, types/SearchNavigationResult.ts
This PR navigates the user to the search page when he searches in the command bar where there are more advanced search options and more detailed search results.
|<img width="642" alt="Screen Shot 2022-03-04 at 09 55 12" src="https://user-images.githubusercontent.com/15169499/156690410-308360cf-0969-495e-bad1-a65a428531e9.png">|<img width="643" alt="Screen Shot 2022-03-04 at 09 55 00" src="https://user-images.githubusercontent.com/15169499/156690404-7ca5ef13-8b7b-41a5-87c9-e9513d92f645.png">|
||![screencapture-localhost-3000-search-2022-03-04-09_47_27](https://user-images.githubusercontent.com/15169499/156690413-ade1e52b-e206-439d-89f4-8d1ce7cf8d51.png)|
=> Update command bar

public/icons/caret-back.svg, public/icons/caret-forward.svg
|<img width="371" alt="Screen Shot 2022-03-04 at 10 09 21" src="https://user-images.githubusercontent.com/15169499/156692060-cb677a1b-6769-4268-9d07-3280bf404a43.png">|<img width="375" alt="Screen Shot 2022-03-04 at 10 09 06" src="https://user-images.githubusercontent.com/15169499/156692056-3a638f87-82af-41b8-b006-21d2c9b6ecc0.png">|
=> Update pagination icons dark-mode color

src/components/Radio/CuratedStationList.tsx, src/components/dls/Card/Card.tsx
fixed this issue https://discord.com/channels/852441853386293268/852459860116373504/949112196078633071
clicking play/pause icon doesn't do anything
=> fix: radio card action icon not clickable

next.config.js
=> Re-enable service worker usage

locales/en/home.json, src/pages/index.tsx
=> Add new welcome message to the home page

src/components/QuranReader/ReadingView/PageNavigationButtons/PageNavigationButtons.module.scss
| ![image](https://user-images.githubusercontent.com/11590314/157128371-813fc902-56cd-4dd2-a128-a9a42697f62f.png) | ![image](https://user-images.githubusercontent.com/11590314/157128215-8ddee7d8-de3b-463d-858f-2fab3c91cb44.png) |
=> Hide reading mode navigation button container on mobile

src/components/QuranReader/ReadingView/WordPopover/index.tsx
This PR fixes the issue of the Reading View's Popover opening while scrolling.
=> Disable opening popover while scrolling

src/components/QuranReader/TranslationView/TranslatioViewCellSkeleton.tsx, src/components/QuranReader/TranslationView/TranslationText/TranslationText.module.scss, src/components/QuranReader/TranslationView/TranslationViewCell.module.scss, src/components/QuranReader/TranslationView/TranslationViewCell.tsx, src/components/QuranReader/TranslationView/TranslationViewSkeleton.module.scss, src/components/Verse/VerseLink/VerseLink.module.scss, src/components/Verse/VerseLink/index.tsx
Please note that the mobile version is not yet opimized
=> prorotype: translation view cell polish

src/components/QuranReader/ReadingView/Line.module.scss, src/components/QuranReader/ReadingView/Line.tsx, src/components/QuranReader/ReadingView/ReadingViewSkeleton.module.scss, src/components/QuranReader/ReadingView/ReadingViewSkeleton.tsx
This PR updates the word by word layout of the reading view.
|<img width="766" alt="Screen Shot 2022-03-12 at 18 09 19" src="https://user-images.githubusercontent.com/15169499/158015768-a06fcd7b-f3a1-4b9f-8fe3-a1fda1b9fe94.png">|<img width="870" alt="Screen Shot 2022-03-12 at 18 08 58" src="https://user-images.githubusercontent.com/15169499/158015758-2cf35e66-b786-4380-b401-9f643c455799.png">|
=> Update Word By Word Layout

src/components/QuranReader/ReadingView/TranslationsButton/TranslationsButton.module.scss, src/components/QuranReader/TranslationView/QuranReflectButton.tsx, src/components/QuranReader/TranslationView/ShareVerseButton.tsx, src/components/QuranReader/TranslationView/TranslationViewCell.module.scss, src/components/Verse/OverflowVerseActionsMenu.tsx, src/components/Verse/PlayVerseAudioButton.tsx
|<img width="176" alt="Screen Shot 2022-03-11 at 15 08 03" src="https://user-images.githubusercontent.com/15169499/157827859-08f52de6-076d-46c9-9d6d-a791f41481e3.png">|<img width="180" alt="Screen Shot 2022-03-11 at 15 07 56" src="https://user-images.githubusercontent.com/15169499/157827850-74c5b6e1-972f-45c3-a5b5-7d50c79b0487.png">|
=> [ReadingView] update translations icon

src/api.ts
=> Only show verified content for the reflections feature

src/api.ts, src/components/QuranReader/TranslationView/QuranReflectButton.tsx
=> Temporarily disable the QR inline feature

src/components/Reciter/ChaptersList.tsx, src/pages/reciters/[reciterId]/index.tsx
This PR localzies the list of Surahs for a specific reciter e.g. `ar/reciters/1`.
|<img width="1150" alt="Screen Shot 2022-03-15 at 09 00 54" src="https://user-images.githubusercontent.com/15169499/158291423-78170ec7-8067-44c8-9990-d74136727ed3.png">|<img width="1167" alt="Screen Shot 2022-03-15 at 09 00 47" src="https://user-images.githubusercontent.com/15169499/158291412-d1cfdf48-62ed-4879-82cd-505ba1e0244a.png">|
=> [SEO] Localize reciter chapters

src/components/Reciter/QuranReciterListHero.tsx, src/components/dls/Forms/Input/Input.module.scss, src/components/dls/Forms/Input/index.tsx
|<img width="872" alt="Screen Shot 2022-03-14 at 13 17 49" src="https://user-images.githubusercontent.com/15169499/158116116-1fcbf4f6-1954-4bdd-b43c-392f6bd14691.png">|<img width="885" alt="Screen Shot 2022-03-14 at 13 17 33" src="https://user-images.githubusercontent.com/15169499/158116101-fc985233-2571-4aed-a633-a8e99ac61b71.png">|
=> Fix reciters search on RTL

src/components/QuranReader/TranslationView/TranslationViewCell.module.scss
|<img width="1111" alt="Screen Shot 2022-03-15 at 09 58 14" src="https://user-images.githubusercontent.com/15169499/158297301-243f6aae-2744-44cb-bc3f-b29ce2e39384.png">|<img width="1122" alt="Screen Shot 2022-03-15 at 09 59 17" src="https://user-images.githubusercontent.com/15169499/158297306-89dc069e-980c-4c38-bf9e-b54c76717b43.png">|
=> [RTL] make translation view menu stick to the left

src/styles/fonts.scss
| ------ |
|<img width="382" alt="Screen Shot 2022-03-15 at 11 08 42" src="https://user-images.githubusercontent.com/15169499/158304728-f08fd943-6915-4324-8e2a-41a17d22efe8.png">|
=> Update Bengali font path

src/components/Reciter/ReciterInfo.module.scss
|<img width="1440" alt="Screen Shot 2022-03-14 at 11 36 44" src="https://user-images.githubusercontent.com/15169499/158107081-561d06fb-f49e-460f-9f57-0b32b92ff0d7.png">|<img width="1440" alt="Screen Shot 2022-03-14 at 11 36 50" src="https://user-images.githubusercontent.com/15169499/158107096-9855cdb7-7faa-4977-aca5-92c7f3625930.png">|
|<img width="1440" alt="Screen Shot 2022-03-14 at 11 38 11" src="https://user-images.githubusercontent.com/15169499/158107099-8de654eb-aba7-416c-bc50-1699b7fcb51f.png">|<img width="1440" alt="Screen Shot 2022-03-14 at 11 38 07" src="https://user-images.githubusercontent.com/15169499/158107097-f4b2e46a-2bcc-46c2-8a7e-a3f5dfffa8ca.png">|
=> Remove reciter's bio background

src/components/QuranReader/TranslationView/TranslationPage/index.tsx
on Incognito mode
* try opening this page `https://quran.com/surah-al-kahf?translations=206%2C20`, 
* ideally it should show saheeh international & Ruwwad Center. 
* But in this case it shows "Dr. Mustafa Khattab, The Clear Quran"
This PR fixed the issue
=> fix: translation param not working

src/pages/reciters/[reciterId]/[chapterId].tsx
|<img width="510" alt="Screen Shot 2022-03-16 at 14 20 51" src="https://user-images.githubusercontent.com/15169499/158537638-b0ea2a04-cf57-4434-be3d-1b1685865a2a.png">|<img width="518" alt="Screen Shot 2022-03-16 at 14 20 42" src="https://user-images.githubusercontent.com/15169499/158537631-1668daf7-98b6-4a7c-bfee-07278c396567.png">|
=> [RTL] disable flipping play button on Reciter's chapter page

src/components/dls/SelectionCard/SelectionCard.module.scss
|<img width="387" alt="Screen Shot 2022-03-18 at 11 35 54" src="https://user-images.githubusercontent.com/15169499/158938355-c0a55fb0-bcec-4d79-a4e0-ed8fbe0baf77.png">|<img width="386" alt="Screen Shot 2022-03-18 at 11 35 28" src="https://user-images.githubusercontent.com/15169499/158938350-71c7028a-0b3f-4e01-9ed5-82b73454e5fb.png">|
=> Update selection card on Sepia mode

src/components/QuranReader/ReflectionView/ReflectionItem.tsx, src/utils/verse.ts
|<img width="243" alt="Screen Shot 2022-03-18 at 11 25 45" src="https://user-images.githubusercontent.com/15169499/158937585-f8709cda-4690-4d70-b41c-bde14b599544.png">|<img width="280" alt="Screen Shot 2022-03-18 at 11 25 42" src="https://user-images.githubusercontent.com/15169499/158937578-15510dc0-7f32-40fd-b026-66964abad2d7.png">|
=> [QR] localize referring ayah/surah

src/components/Search/SearchResults/SearchResultItem.tsx, src/components/Verse/PlainVerseText/PlainVerseTextWord/index.tsx, src/components/Verse/PlainVerseText/index.tsx, src/components/Verse/VerseText.tsx, src/components/chapters/ChapterIcon/index.tsx
This PR disables allowing translating the verse text which either replaces or adds extra words or Glyphs.
|<img width="383" alt="Screen Shot 2022-03-19 at 19 15 37" src="https://user-images.githubusercontent.com/15169499/159121067-538bf7c7-3cec-488b-8136-94e160a36fe5.png">|<img width="386" alt="Screen Shot 2022-03-19 at 19 15 47" src="https://user-images.githubusercontent.com/15169499/159121072-c1fdaa76-3c9f-405c-844f-c5e3748e8f56.png">|
|<img width="1198" alt="Screen Shot 2022-03-19 at 19 15 56" src="https://user-images.githubusercontent.com/15169499/159121073-d245f76a-6192-41cb-80c3-2a7732f88acc.png">|<img width="1164" alt="Screen Shot 2022-03-19 at 19 16 13" src="https://user-images.githubusercontent.com/15169499/159121075-6721183f-b136-410d-b127-7 …
=> Disable translating Verse text

src/pages/search.tsx
This PR updates the query param from `query` to `q` in the url.
=> Update search query param

src/components/QuranReader/ReflectionView/ReflectionItem.tsx
=> QR integration: add url to author picture

src/components/AudioPlayer/RepeatButton.tsx
this is a fix for #1357
| ------ | ----- |
| ![image](https://user-images.githubusercontent.com/58295120/157064658-6a241cd8-5f52-4f26-9863-976bddce98fc.png) | ![image](https://user-images.githubusercontent.com/58295120/157064622-f789d2c8-b16d-4612-b641-f2dd3aa056fa.png) |
=> Localize repeat badge number

src/components/chapters/ChapterHeader/ChapterHeader.module.scss, src/components/chapters/ChapterHeader/index.tsx, src/components/chapters/ChapterIcon/ChapterIconContainer.module.scss, src/components/chapters/ChapterIcon/ChapterIconContainer.tsx
=> Chapter header

.vscode/settings.json, src/components/QuranReader/ReflectionView/ReflectionItem.module.scss, src/components/QuranReader/ReflectionView/ReflectionItem.tsx
=> Referenced ayah UI

src/components/AudioPlayer/RepeatAudioModal/RepeatAudioModal.tsx, src/components/AudioPlayer/RepeatAudioModal/SelectRepetitionMode.tsx
|<img width="488" alt="Screen Shot 2022-03-23 at 09 50 36" src="https://user-images.githubusercontent.com/15169499/159614605-9b8a4522-d79b-4d64-bb07-f1119f37991f.png">|<img width="492" alt="Screen Shot 2022-03-23 at 09 49 17" src="https://user-images.githubusercontent.com/15169499/159614579-3267a9e7-6d39-468e-bf45-fa1961e69691.png">|
|<img width="487" alt="Screen Shot 2022-03-23 at 09 50 30" src="https://user-images.githubusercontent.com/15169499/159614602-280cd2ac-1dad-4e10-b1d8-f80802c19980.png">|<img width="491" alt="Screen Shot 2022-03-23 at 09 49 21" src="https://user-images.githubusercontent.com/15169499/159614592-4d167353-56cd-4187-bf66-2604bfdfed43.png">|
|<img width="488" alt="Screen Shot 2022-03-23 at 09 50 43" …
=> Localize audio repeat modal

src/components/HomePage/QuickLinks/QuickLinks.module.scss
| ----- |
| <img width="719" alt="Screen Shot 2022-03-23 at 14 22 50" src="https://user-images.githubusercontent.com/15169499/159645336-2cc5d923-5445-430f-b56b-9ded511e9f46.png"> |
=> [Web Vitals] Fix quick links color contrast

src/components/Navbar/Logo/NavbarLogoWrapper.tsx
| ------ |
|<img width="811" alt="Screen Shot 2022-03-23 at 15 24 38" src="https://user-images.githubusercontent.com/15169499/159655901-1cb2cae8-ef03-4c91-987b-db059a0c22fc.png">|
=> [Web Vitals] Fix Logo link not indexable

src/components/dls/Button/Button.tsx
| ------ |
|<img width="532" alt="Screen Shot 2022-03-23 at 15 42 05" src="https://user-images.githubusercontent.com/15169499/159658455-db078363-6ae6-454d-810c-68592b0159bc.png">|
=> [Web Vitals] Fix non-indexable button links

locales/en/common.json, src/components/HomePage/HomePageMessage.tsx, src/components/Navbar/Drawer/DrawerCloseButton.tsx, src/components/Navbar/LanguageSelector.tsx, src/components/Navbar/NavbarBody/index.tsx, src/components/TarteelVoiceSearch/Trigger.tsx, src/components/dls/Button/Button.tsx
| ------ |
|<img width="590" alt="Screen Shot 2022-03-23 at 16 55 19" src="https://user-images.githubusercontent.com/15169499/159672995-c1c32199-d80b-4437-8bb6-7778307db13a.png">|
=> [Web Vitals] buttons accessible name

src/components/Navbar/Logo/NavbarLogoWrapper.tsx, src/components/dls/Link/Link.tsx
|------|
|<img width="711" alt="Screen Shot 2022-03-23 at 19 08 23" src="https://user-images.githubusercontent.com/15169499/159699783-38fc3e58-6fdd-4bd2-813a-f452aa0396d2.png">|
=> [Web Vitals] fix Logo doesn't have a discernible name

src/components/dls/Footer/Footer.module.scss, src/components/dls/Footer/Links.tsx
| ------ |
|<img width="738" alt="Screen Shot 2022-03-23 at 20 44 14" src="https://user-images.githubusercontent.com/15169499/159717600-f7b021d6-bd04-4d06-8eaa-5652f307e492.png">|
=> [Web Vitals] Improve homepage mobile friendliness

src/components/dls/Tabs/Tabs.tsx
| ------ |
|<img width="726" alt="Screen Shot 2022-03-23 at 20 31 43" src="https://user-images.githubusercontent.com/15169499/159711942-8acfa8f6-8415-465f-8d16-ee725614f639.png">|
=> [Web Vitals] fix tabindex value greater than 0

locales/en/common.json, src/components/QuranReader/PlayChapterAudioButton.tsx, src/components/QuranReader/SidebarNavigation/SidebarNavigation.tsx, src/components/QuranReader/TranslationView/QuranReflectButton.tsx, src/components/QuranReader/TranslationView/ShareVerseButton.tsx, src/components/Verse/OverflowVerseActionsMenu.tsx, src/components/Verse/PlayVerseAudioButton.tsx
| ------ |
|<img width="575" alt="Screen Shot 2022-03-24 at 13 42 09" src="https://user-images.githubusercontent.com/15169499/159863772-6db7fba8-aa0e-444c-9868-7b0e42f13183.png">|
=> [Web Vitals] Add Quran Reader buttons aria-label

src/pages/_app.tsx
| ------ |
|<img width="877" alt="Screen Shot 2022-03-24 at 12 56 40" src="https://user-images.githubusercontent.com/15169499/159852280-6e45af64-8df6-4024-b64f-90e7d18c24be.png">|
=> [PWA] Add apple-touch-icon

src/components/dls/Tabs/Tabs.tsx
| ------ |
|<img width="559" alt="Screen Shot 2022-03-24 at 12 35 26" src="https://user-images.githubusercontent.com/15169499/159850139-aee6b827-183c-48d3-8fc9-dc15d80de2a2.png">|
=> [Web Vitals] Add tablist role to tabs parent

src/components/TarteelVoiceSearch/BodyContainer/VoiceSearchBodyContainer.module.scss
|<img width="308" alt="Screen Shot 2022-03-24 at 20 29 28" src="https://user-images.githubusercontent.com/15169499/159927478-c439f0f0-6a40-45c9-b75c-063f142c10e1.png">|<img width="321" alt="Screen Shot 2022-03-24 at 20 29 15" src="https://user-images.githubusercontent.com/15169499/159927459-4c98b647-0d0a-4816-b147-4c969b48bb5e.png">|
=> Fix command bar's voice search layout on mobile

src/components/Fonts/FontPreLoader.tsx, src/components/QuranReader/index.tsx, src/styles/fonts.scss
| ------ |
|<img width="784" alt="Screen Shot 2022-03-24 at 21 07 11" src="https://user-images.githubusercontent.com/15169499/159942482-d99eaa5d-98a4-4c0d-8805-a5d6420feeca.png">|
|<img width="883" alt="Screen Shot 2022-03-24 at 21 21 20" src="https://user-images.githubusercontent.com/15169499/159942507-dbcf2ca9-3ed8-4372-8c70-ee59921fbacf.png">|
=> [Web Vitals] Fix invisible text while font loads

src/components/Navbar/NavigationDrawer/MobileApps.tsx, src/components/Radio/CuratedStationList.tsx, src/components/Reciter/RecitersList.tsx, src/pages/about-us.tsx
| ------ |
|<img width="888" alt="Screen Shot 2022-03-25 at 14 33 33" src="https://user-images.githubusercontent.com/15169499/160076238-0dc661ac-3464-47a9-90fe-e998caa05ec6.png">|
=> [Web Vitals] Add alt attribute for images

src/components/chapters/Info/Info.module.scss, src/components/chapters/Info/index.tsx
| ------ |
|<img width="780" alt="Screen Shot 2022-03-25 at 15 19 12" src="https://user-images.githubusercontent.com/15169499/160083139-c69843ea-2716-474a-ba7c-bf00961b2e76.png">|
=> [Web Vitals] Update update chapter info image ratio

src/pages/apps.tsx
| ------ |
|<img width="774" alt="Screen Shot 2022-03-25 at 15 12 54" src="https://user-images.githubusercontent.com/15169499/160081701-f6629be1-f25a-430a-801f-c682d8b9003f.png">|
=> [Web Vitals] Update apps image ratio

src/components/Radio/ReciterStationList.tsx
| ------ |
|<img width="699" alt="Screen Shot 2022-03-26 at 08 49 25" src="https://user-images.githubusercontent.com/15169499/160220197-020e254d-dd7b-46cf-95b3-c10c59ed32e5.png">|
=> [Web Vitals] Add radio reciters image alt

src/components/dls/Card/Card.tsx
| Screenshots | 
| ------ | 
|<img width="699" alt="Screen Shot 2022-03-26 at 08 48 57" src="https://user-images.githubusercontent.com/15169499/160220497-40536a73-773d-49b5-a1aa-9f9065c7aa04.png">|
=> [Accessibility] Add aria-label for radio play button

src/components/Search/PreInput/index.tsx
| ------ |
|<img width="704" alt="Screen Shot 2022-03-26 at 10 40 47" src="https://user-images.githubusercontent.com/15169499/160223489-b70970ea-18f5-44be-aeb3-fc5b025e13dd.png">|
=> [Web Vitals] Search page links not crawlable

src/components/Reciter/ChaptersList.tsx
| ------ | 
|<img width="628" alt="Screen Shot 2022-03-26 at 09 25 38" src="https://user-images.githubusercontent.com/15169499/160221935-45854fcf-4af1-4479-8f8d-03d942f5a32a.png">|
=> [Accessibility] Add aria-label for reciter buttons

src/styles/global.scss, src/utils/locale.ts
|![screencapture-next-quran-3-4-tafsirs-kurd-tafsir-rebar-2022-03-26-08_26_15](https://user-images.githubusercontent.com/15169499/160219320-d61bc954-fc32-4757-9697-27b31d006648.png)|![screencapture-localhost-3000-3-4-tafsirs-kurd-tafsir-rebar-2022-03-26-08_25_54](https://user-images.githubusercontent.com/15169499/160219316-186c0fc3-92d1-470a-9dbb-d1b92bb22e71.png)|
=> Add Kurdish Tafsir support

src/components/dls/QuranWord/onQuranWordClick.ts
| ------ |
|<img width="593" alt="Screen Shot 2022-03-30 at 09 46 04" src="https://user-images.githubusercontent.com/15169499/160741162-c7bfe132-7beb-4860-97ca-f03a0cddef8e.png">|
=> [Audio] update wbw audio file path

src/components/PageContainer/PageContainer.module.scss, src/components/PageContainer/index.tsx, src/components/dls/Footer/Footer.module.scss, src/pages/about-us.tsx, src/pages/apps.tsx, src/pages/contentPage.module.scss, src/pages/developers.tsx, src/pages/privacy.tsx, src/pages/product-updates/[id].tsx, src/pages/product-updates/changelog.module.scss, src/pages/product-updates/index.tsx, src/pages/support.tsx
|<img width="1440" alt="Screen Shot 2022-03-30 at 08 24 22" src="https://user-images.githubusercontent.com/15169499/160732296-5882f848-fbc9-4d68-9678-1718fa1817db.png">|<img width="1440" alt="Screen Shot 2022-03-30 at 08 24 27" src="https://user-images.githubusercontent.com/15169499/160732311-0c6c604d-f7d3-404a-b6c3-a56a92c53f53.png">|
=> Add unified page container

public/icons/divider-horizontal.svg
=> fix: checkbox dls indeterminate ui

src/components/Navbar/SearchDrawer/Header/Header.module.scss, src/components/Navbar/SearchDrawer/Header/index.tsx
=> fix: rtl search on ltr language

src/components/AudioPlayer/AudioPlayerBody/index.tsx, src/components/AudioPlayer/AudioRepeatManager/AudioRepeatManager.tsx, src/components/QuranReader/PlayChapterAudioButton.tsx
This PR fixes the exception when setting a repeating of a Surah then playing the audio of another Surah.
| ------ |
|<img width="992" alt="Screen Shot 2022-03-31 at 15 49 44" src="https://user-images.githubusercontent.com/15169499/161385092-40e1b3e5-de1c-47af-9b20-739645df53c2.png">|
=> [Audio] fix audio player exception when changing chapter while on repeat

locales/en/home.json
=> fix: welcome message title

package.json, src/components/QuranReader/ReflectionView/ReflectionBodyContainer/ReflectionBody/index.tsx, yarn.lock
This PR downgrades `swr` version to solve an issue with requests not going through which leads to changing font/translation not reflecting in the UI without refreshing the page.
=> Downgrade swr

src/components/AudioPlayer/AudioRepeatManager/AudioRepeatManager.tsx, src/components/AudioPlayer/Buttons/PlayPauseButton.tsx, src/components/AudioPlayer/EventTriggers.ts, src/components/AudioPlayer/MediaSessionApiListeners.tsx, src/components/QuranReader/PlayChapterAudioButton.tsx, src/components/Radio/CuratedStationList.tsx, src/components/Radio/ReciterStationList.tsx, src/components/dls/QuranWord/QuranWord.tsx, src/components/dls/QuranWord/onQuranWordClick.ts, src/redux/slices/AudioPlayer/state.ts
This PR persists the playback rate across the entire app so that when a user chooses a playback speed, plays a Surah and then plays another Surah, it applies the same playback speed to the new Surah.
=> [Audio] apply playback rate across audio player

src/styles/fonts.scss
|<img width="384" alt="Screen Shot 2022-04-04 at 9 13 55 PM" src="https://user-images.githubusercontent.com/15169499/161616243-aba442db-4839-45c4-9090-fc2ac9b7d73c.png">|<img width="383" alt="Screen Shot 2022-04-04 at 9 14 02 PM" src="https://user-images.githubusercontent.com/15169499/161616248-1a84f506-776c-4c72-ad2b-0f7b27212a71.png">|
|<img width="383" alt="Screen Shot 2022-04-04 at 9 14 41 PM" src="https://user-images.githubusercontent.com/15169499/161616255-21fc13e0-d1b5-4571-9524-f3fad10ceedd.png">|<img width="386" alt="Screen Shot 2022-04-04 at 9 14 47 PM" src="https://user-images.githubusercontent.com/15169499/161616258-dda4c1e6-8f91-4480-94ea-8bdc6ac0222a.png">|
|<img width="1114" alt="Screen Shot 2022-04-04 at 9 15 51 PM" …
=> Fix latin characters not showing correctly in Urdu

src/components/QuranReader/TranslationView/TranslationViewCell.module.scss, src/components/QuranReader/TranslationView/TranslationViewCell.tsx
=> translationview cell: update play action button position

src/components/AudioPlayer/Buttons/PlayPauseButton.tsx
This PR fixes issue when clicking "Start Over" button after having setup repeat settings of another Surah.
| ------ |
|<img width="974" alt="Screen Shot 2022-04-06 at 6 34 30 PM" src="https://user-images.githubusercontent.com/15169499/162032437-2b5638e2-c755-42b5-8f5d-1ec2bf818020.png">|
=> [Audio] Fix repeat start over issue

src/components/Navbar/LanguageSelector.tsx, src/components/dls/Footer/BottomSection.tsx, src/components/dls/PopoverMenu/PopoverMenu.tsx
|<img width="1297" alt="Screen Shot 2022-04-06 at 7 36 50 PM" src="https://user-images.githubusercontent.com/15169499/162046443-29df5502-5aee-483b-abc8-18714334a1c2.png">|<img width="1440" alt="Screen Shot 2022-04-06 at 7 36 17 PM" src="https://user-images.githubusercontent.com/15169499/162046426-951db507-1a6a-4f15-ad42-4ecbdbb8bb26.png">|
=> Update footer language selector position

src/redux/slices/AudioPlayer/state.ts
This PR fixes the issue of exception thrown due to [`Infinite` being persisted as `null`](https://github.com/rt2zz/redux-persist/issues/290) when the user chooses to repeat infinitely, then refreshes the page then clicks on the repeat settings icon on the audio player.
1. Open `/114`
2. Click play chapter
3. Click on the Repeat Settings button
4. Set the play range to infinite
5. Click Start Playing
6. Refresh the page
8. Click on the Repeat Settings button
9. Repeat Settings Modal should open without exceptions
=> [Audio] Fix infinite repeat throwing exception

src/components/AudioPlayer/AudioRepeatManager/AudioRepeatManager.tsx
| ------ | 
|<img width="548" alt="Screen Shot 2022-04-13 at 5 31 11 PM" src="https://user-images.githubusercontent.com/15169499/163217012-b5e8ce1d-45af-4b02-ad9c-9157def5af26.png">|
=> [Audio] Fix read timestampFrom of null

src/components/Verse/PlainVerseText/PlainVerseTextWord/PlainVerseTextWord.module.scss
=> reflections:  add spacing between verse word

.github/workflows/playwright.yml, src/components/QuranReader/SidebarNavigation/SidebarNavigation.tsx
This PR fixes an issue where more events of the navigation side-bar closing are being reported than they should be.
=> [Logging] Fix sidebar navigation logging

src/components/Reciter/QuranReciterListHero.module.scss, src/components/Reciter/QuranReciterListHero.tsx, src/components/dls/Forms/Input/index.tsx
=> Fix reciter search UI

src/pages/login.module.scss
=> login page: fix button width issue

locales/en/profile.json, src/components/Profile/DeleteAccountButton.module.scss, src/components/Profile/DeleteAccountButton.tsx, src/components/dls/Button/Button.module.scss, src/components/dls/Modal/Content.module.scss, src/pages/profile.tsx
=> Delete account dialog

src/pages/profile.tsx, src/utils/auth/constants.ts, types/UserProfile.ts
Google
Facebook
Email (no profile picture)
=> add photo url

locales/en/login.json, src/components/Login/LoginContainer.tsx, src/components/Login/ResendEmailSection.tsx, src/components/Login/login.module.scss
=> feat(magic-link): resend email

src/components/Profile/DeleteAccountButton.tsx, src/pages/profile.module.scss, src/pages/profile.tsx
add loading skeleton for profile. I am not 100% certain about this skeleton actually
I have a thought that it might be better to not use skeleton here, as it's one the main content here, and fast.
It's not like quran reader or content that got loaded onclick / on interaction.
but I need to do research first.
=> profile page skeleton

src/components/AudioPlayer/Buttons/AudioPlaybackRateMenu.tsx, src/components/AudioPlayer/Buttons/SelectReciterMenu.tsx, src/components/AudioPlayer/RepeatAudioModal/RepeatAudioModal.tsx, src/components/Navbar/LanguageSelector.tsx, src/components/Navbar/SettingsDrawer/AudioSection.tsx, src/components/Navbar/SettingsDrawer/QuranFontSection.tsx, src/components/Navbar/SettingsDrawer/ReciterSelectionBody.tsx, src/components/Navbar/SettingsDrawer/ThemeSection.tsx, src/components/Navbar/SettingsDrawer/TranslationSection.tsx, src/components/Navbar/SettingsDrawer/TranslationSelectionBody.tsx, src/components/Navbar/SettingsDrawer/WordByWordSection.tsx, src/components/Navbar/SettingsDrawer/WordTooltipSection.tsx, src/components/QuranReader/ReadingPreferenceSwitcher.tsx, src/components/QuranReader/TafsirView/TafsirBody.tsx, src/components/QuranReader/TafsirView/TafsirText/index.tsx, src/hooks/usePersistPreferenceGroup.ts, src/redux/Provider.tsx, src/utils/auth/api.ts, src/utils/auth/preferencesMapper.ts
This PR updates the individual changed preference instead of the entire group.
=> Update individual preference

.storybook/preview.js
=> fix: storybook preview container

src/components/Login/login.module.scss
=> fix: awaiting confirmation ui

src/components/QuranReader/TafsirView/TafsirBody.tsx
This PR fixes the issue where the language selection list cannot be changed.
=> Fix Tafsir not changing language

src/components/Login/SocialLogin.tsx
|<img width="397" alt="Screen Shot 2022-08-06 at 9 58 30 AM" src="https://user-images.githubusercontent.com/15169499/183230882-82b9519d-dd99-48ce-be37-bef886a196e7.png">|<img width="384" alt="Screen Shot 2022-08-06 at 9 58 33 AM" src="https://user-images.githubusercontent.com/15169499/183230889-b199ffc2-f0f7-42fb-8417-63a19f2460ca.png">|
=> Fix Social login RTL icons

src/components/Login/CompleteSignupForm.tsx, src/components/Login/EmailVerificationForm.tsx, src/components/Login/LoginContainer.tsx, src/components/Login/SocialLogin.tsx, src/components/Login/WelcomeMessageModalBody.tsx, src/components/Navbar/NavbarBody/ProfileAvatarButton.tsx, src/components/Profile/DeleteAccountButton.tsx, src/pages/profile.tsx, src/utils/eventLogger.ts, types/auth/AuthType.ts
This PR logs auth-related user interactions.
=> Log auth-related user interactions

src/components/Search/SearchResults/SearchResults.module.scss, src/components/Search/SearchResults/index.tsx
=> fix: search page styling issue

README.md
Add backticks for quoting markdown to be unified with the rest of the document.
=> add markdown to be unified

src/components/DonatePopup/DonatePopup.tsx, src/components/ThirdPartyScripts/ThirdPartyScripts.tsx
This PR lazy-loads giving loop scripts using Next.js's [`lazyOnload`](https://nextjs.org/docs/basic-features/script#lazyonload) Script strategy.
|<img width="1042" alt="Screen Shot 2022-08-25 at 5 39 30 PM" src="https://user-images.githubusercontent.com/15169499/186643932-8dde8634-dd11-4deb-bc5b-96e7c894b6f4.png">|<img width="1288" alt="Screen Shot 2022-08-25 at 5 39 41 PM" src="https://user-images.githubusercontent.com/15169499/186643953-d12e8e8c-2449-4286-9987-8b1f172b88db.png">|
=> Lazy load gl script

src/components/Radio/ReciterStationList.tsx
=> add link to reciter on radio

src/components/dls/Modal/Modal.stories.tsx, src/components/dls/PopoverMenu/PopoverMenu.stories.tsx
=> Fix `PopoverMenu` & `Modal` stories

locales/en/quran-reader.json, src/components/Collection/SaveToCollectionModal/SaveToCollectionModal.module.scss, src/components/Collection/SaveToCollectionModal/SaveToCollectionModal.stories.tsx, src/components/Collection/SaveToCollectionModal/SaveToCollectionModal.tsx
=> UI: save to collection modal

package.json, src/components/dls/Collapsible/Collapsible.module.scss, src/components/dls/Collapsible/Collapsible.stories.tsx, src/components/dls/Collapsible/Collapsible.tsx, yarn.lock
=> new DLS: Collapsible

locales/en/profile.json, src/components/Collection/RenameCollectionModal/RenameCollectionModal.module.scss, src/components/Collection/RenameCollectionModal/RenameCollectionModal.stories.tsx, src/components/Collection/RenameCollectionModal/RenameCollectionModal.tsx, src/components/FormBuilder/FormBuilder.tsx, src/components/FormBuilder/FormBuilderTypes.ts
=> UI: RenameCollectionModal

locales/en/collection.json, src/components/Collection/CollectionDetail/CollectionDetail.module.scss, src/components/Collection/CollectionDetail/CollectionDetail.tsx, src/components/Collection/CollectionDetail/CollectionDetaill.stories.tsx
Wait untiil PR #1768 merged before merging this PR
=> UI  collection detail component

.eslintignore, .eslintrc.json, src/components/AudioPlayer/Buttons/PlayPauseButton.tsx, src/components/AudioPlayer/hooks/useActiveVerseTiming.tsx, src/components/AudioPlayer/hooks/useMemoizedHighlightedWordLocation.ts, src/components/Navbar/SettingsDrawer/SettingsDrawer.tsx, src/components/Navbar/SettingsDrawer/TafsirSection.tsx, src/components/Navbar/SettingsDrawer/TranslationSection.tsx, src/components/Navbar/SettingsDrawer/VersePreview.tsx, src/components/QuranReader/PlayChapterAudioButton.tsx, src/components/QuranReader/ReadingView/index.tsx, src/components/QuranReader/SidebarNavigation/VerseList.tsx, src/components/QuranReader/TranslationView/TranslationPage/index.tsx, src/components/Radio/ReciterStationList.tsx, src/components/Search/Filters/TranslationGroup.tsx, src/components/Verse/PlayVerseAudioButton.tsx, src/components/dls/SurahPreview/SurahPreview.tsx, src/pages/search.tsx, src/utils/page.ts, src/xstate/actors/audioPlayer/audioPlayerMachine.ts
Apply https://github.com/quran/quran.com-frontend-next/pull/1774#discussion_r960634717
=> Eslint: force curly braces in if statements

src/pages/search.tsx
This is a fix for #1773
| ![Before](https://user-images.githubusercontent.com/15169499/187202075-31a35b20-790c-4b56-a153-8b531745aafe.png) | ![After.gif](https://user-images.githubusercontent.com/58295120/187268560-5f25da3b-23df-4d00-a226-fdace6aba15d.gif) |
=> Fix search pagination

src/components/Navbar/NavbarBody/ProfileAvatarButton.tsx, src/components/dls/Button/Button.tsx, src/components/dls/Link/Link.tsx
|<img width="778" alt="Screen Shot 2022-09-11 at 5 42 16 PM" src="https://user-images.githubusercontent.com/15169499/189523883-3f2ec072-be58-4d7c-bc11-b6c62cf3bd55.png">||
|<img width="779" alt="Screen Shot 2022-09-11 at 5 54 18 PM" src="https://user-images.githubusercontent.com/15169499/189523908-e808204d-ac89-4976-8e7d-cb7b62e9bf99.png">||
=> Fix login button accessibility issue

next.config.js
This PR adds [production source maps](https://nextjs.org/docs/advanced-features/source-maps).
=> Add production source maps

src/components/Verse/PlayVerseAudioButton.tsx, src/xstate/actors/audioPlayer/audioPlayerMachine.ts
=> feat: click play ayah should always start from the verse

locales/en/quran-reader.json, src/components/QuranReader/PlayChapterAudioButton.tsx, src/components/QuranReader/QueryParamMessage/index.tsx, src/hooks/useGetQueryParamOrReduxValue.ts, src/hooks/useGetQueryParamOrXstateValue.ts
https://share.descript.com/view/94RQlxLKM78
=> Fix-bugs-related-to-query-params

src/components/QuranReader/TranslationView/TranslationViewCell.tsx, src/hooks/useScrollToElement.ts
https://feedback.quran.com/feature-requests/p/display-from-start-of-the-verse-while-playing-audio
=> when verse changed, scroll the to the top of the verse cell instead of to the center

locales/en/quran-reader.json, src/components/Collection/SaveToCollectionModal/SaveToCollectionModal.tsx, src/components/FormBuilder/FormBuilder.tsx, src/components/Verse/SaveToCollectionAction.tsx
- add loading 
- add toast on add new collection and on on collection
=> improve add to collection ux

src/components/Navbar/NavbarBody/ProfileAvatarButton.tsx
We have an env variable that is currently set to 100%. Remove the logic now as we no longer are experimenting with auth
=> Remove conditional profile button showing logic

src/pages/[chapterId]/[verseId]/index.tsx, src/redux/defaultSettings/locales/ar.ts, src/utils/plainTranslationText.ts
=>   Uses verse translation as the og description

src/components/dls/Card/Card.tsx
اَلسَّلَامُ عَلَيْكُمْ
Changed the `<img>` tag to the Next.js `<Image>` for better performance 
Tested it locally on seems to work OK,
also visited the pages where the change should be, looks all good there too 
(looks identical, so just pasted the diff in the code 😁)
in `src/components/dls/Card/Card.tsx`:
```diff
import classNames from 'classnames';
import useTranslation from 'next-translate/useTranslation';
+ import Image from 'next/image';
.
.
.
-        {imgSrc && <img alt={imgAlt} className={styles.img} src={imgSrc} />}
+       {imgSrc && <Image alt={imgAlt} className={styles.img} src={imgSrc} layout="fill" />}
```
=> chore: changed img tag to Next/Image tag

locales/en/home.json, src/components/Verses/BookmarkedVersesList.module.scss, src/components/Verses/BookmarkedVersesList.tsx, src/components/Verses/BookmarksAndCollectionsSection.tsx, src/pages/profile.module.scss, src/pages/profile.tsx, src/utils/auth/apiPaths.ts
The API had a limit of returning 10 bookmarks, but if a user had more bookmarks, there was no intuitive way to view all their bookmarks. 
Added a small button to let users view all their bookmarks by navigating to the collections tab. 
Also did a nit change by adding more spacing on the profile page
=> Add a view all bookmarks button when a user reaches the api limit

src/styles/_theme.scss, src/styles/theme.scss
=> Make sepia the default for light mode auto

src/components/QuranReader/RevelationOrderNavigationNotice.tsx, src/components/chapters/RevelationOrderView.tsx, src/components/dls/SurahPreview/SurahPreviewRow.tsx, src/redux/slices/revelationOrder.ts
This PR adds persisting revelation mode reading preference.
=> Persist revelation mode preference

src/components/chapters/Info/index.tsx, src/components/dls/Card/Card.tsx, src/pages/about-us.tsx, src/pages/apps.module.scss, src/pages/apps.tsx
Next v13 introduces [an update](https://nextjs.org/docs/upgrading#image-component) in the `<Image />` component. This PR uses the new API.
=> Update image component

src/components/dls/KeyboardInput/MetaShortcut.tsx, src/components/dls/KeyboardInput/index.tsx
Reverts quran/quran.com-frontend-next#1877
=> Revert "load shortcut on client only"

src/components/chapters/Info/index.tsx, src/components/dls/Card/Card.tsx, src/pages/about-us.tsx, src/pages/apps.module.scss, src/pages/apps.tsx
Reverts quran/quran.com-frontend-next#1876
=> Revert "Update image component"

src/components/chapters/Info/InfoPage.tsx, src/lib/og.ts, src/pages/[chapterId]/[verseId]/index.tsx, src/pages/[chapterId]/index.tsx, src/pages/[chapterId]/reflections.tsx, src/pages/[chapterId]/tafsirs/[tafsirId].tsx, src/utils/seo.ts
🎉 [New OG images](https://github.com/quran/next-open-graph) are out. 
This PR:
- Uses the new images for chapters and verses.
- Uses a new default image for all other pages.
=> New OG images

src/components/dls/Toggle/Toggle.module.scss
| ![image](https://user-images.githubusercontent.com/58295120/213983045-2bd1e784-ce3e-4cb4-a6c9-c9697fa42f30.png) | ![image](https://user-images.githubusercontent.com/58295120/213983146-4c385682-f9fd-4905-b520-e9d71775e978.png) |
=> Fix sepia toggle colors

src/components/Verses/RecentReadingSessions.tsx, src/components/Verses/RecentReadingSessionsSkeleton.module.scss, src/components/Verses/RecentReadingSessionsSkeleton.tsx
=> Add recently read skeleton

src/components/QuranReader/TafsirView/TafsirView.module.scss, src/components/dls/QuranWord/TextWord.module.scss, src/components/dls/QuranWord/TextWord.tsx, src/styles/fonts.scss
I have raised an issue ticket that describes the error behaviour in https://github.com/quran/quran.com-frontend-next/issues/1910
This has minimal effect and corrects an error.
| 
| 
|
=> fixes bug related to Arabic text in Tafsir View

src/components/Navbar/Navbar.module.scss, src/components/QuranReader/ContextMenu.module.scss, src/components/Verses/RecentReadingSessionsSkeleton.tsx, src/pages/index.module.scss, src/pages/search.module.scss
Navbar was not being hidden when you scroll. This is because of the donation banner. This PR adds the banner's height to the `translate` CSS property in the hiddenNav class
=> Fix donation banner

src/components/Collection/CollectionDetailContainer/CollectionDetailContainer.tsx, src/components/chapters/Info/InfoPage.tsx, src/pages/[chapterId]/[verseId]/index.tsx, src/pages/[chapterId]/[verseId]/tafsirs.tsx, src/pages/[chapterId]/index.tsx, src/pages/[chapterId]/reflections.tsx, src/pages/[chapterId]/tafsirs/[tafsirId].tsx, src/pages/collections/[collectionId]/index.tsx, src/pages/collections/all/index.tsx, src/pages/hizb/[hizbId]/index.tsx, src/pages/index.tsx, src/pages/juz/[juzId]/index.tsx, src/pages/page/[pageId].tsx, src/pages/profile.tsx, src/pages/radio.tsx, src/pages/reciters/[reciterId]/[chapterId].tsx, src/pages/reciters/[reciterId]/index.tsx, src/pages/reciters/index.tsx, src/pages/rub/[rubId]/index.tsx, src/pages/search.tsx
This PR removes useless `DataContext.Provider` from all pages.
=> Remove useless DataContext.Provider

src/utils/tests/array/areArraysEqual.test.ts, src/utils/tests/array/mergeTwoArraysUniquely.test.ts, src/utils/tests/array/numbersToStringsArray.test.ts, src/utils/tests/array/removeItemFromArray.test.ts, src/utils/tests/array/stringsToNumbersArray.test.ts
These are some tests for the first function in array util functions this is just a draft, when maintainers approve of it and discuss it further will be applied to all functions of the file
=> add tests for array util functions

src/components/Navbar/SettingsDrawer/WordByWordSection.tsx, src/components/Verse/PlainVerseText/PlainVerseTextWord/PlainVerseTextWord.module.scss, src/components/Verse/PlainVerseText/PlainVerseTextWord/index.tsx, src/components/Verse/VerseText.module.scss, src/components/dls/InlineWordByWord/InlineWordByWord.module.scss, src/components/dls/InlineWordByWord/index.tsx, src/components/dls/QuranWord/QuranWord.module.scss, src/components/dls/QuranWord/QuranWord.tsx, src/redux/defaultSettings/defaultSettings.ts, src/redux/slices/QuranReader/styles.ts, src/redux/types/QuranReaderStyles.ts
- We received some [feedback](https://feedback.quran.com/feature-requests/p/font-size-for-word-by-word-translation) regarding having the ability to change the font size of the word-by-word translation/transliteration.
- We will have 6 different font sizes.
|<img width="386" alt="Screen Shot 2023-04-30 at 1 05 59 AM" src="https://user-images.githubusercontent.com/15169499/235325961-847de23d-0348-497d-a499-4f157a8ab754.png">|<img width="385" alt="Screen Shot 2023-04-30 at 1 07 00 AM" src="https://user-images.githubusercontent.com/15169499/235325993-db1eb74b-8582-4705-86ad-e4fb43473733.png">|
|<img width="1039" alt="Screen Shot 2023-04-30 at 1 10 12 AM" src="https://user-images.githubusercontent.com/15169499/235326103-0b4a90df-f622-4fcd-94e8-4ffa7fc8db81 …
=> Add ability to change wbw font size

src/utils/auth/constants.ts, src/utils/auth/login.ts, types/AppEnv.ts
This PR adds a suffix to auth cookies to allow concurrent logins across multiple environments.
=> Suffix auth cookies

src/components/ReadingGoalPage/ReadingGoalWeekPreviewTab.tsx, src/components/ReadingGoalPage/ReadingGoalWeekPreviewTabSkeleton.tsx, src/utils/auth/api.ts
This PR uses the `DataFetcher` component in the `ReadingGoalWeekPreviewTab` and refactors the skeleton into its own component.
=> use DataFetcher in `ReadingGoalWeekPreviewTab`

src/components/HomePage/ReadingStreak/index.tsx
This PR shows this widget to all users, even if they're not logged in:
=> [Official release] Show QGJ onboarding to all users

src/components/QuranReader/ReflectionView/ReflectionBodyContainer/index.tsx, src/utils/auth/api.ts, src/utils/auth/apiPaths.ts
This PR calls reflection views API when the user if logged-in.
=> Call reflection views API

src/components/PageContainer/PageContainer.module.scss, src/pages/about-the-quran/index.tsx, src/pages/contentPage.module.scss
| <img width="1722" alt="Screenshot 2023-09-29 at 13 47 17" src="https://github.com/quran/quran.com-frontend-next/assets/15169499/84a3525f-35da-49a8-9713-05ba374b91a9"> |<img width="1565" alt="Screenshot 2023-09-29 at 13 47 45" src="https://github.com/quran/quran.com-frontend-next/assets/15169499/3672101e-080d-42be-97de-91d7d14450da"> |
=> Update about the Quran styling

src/components/TarteelVoiceSearch/BodyContainer/PartialResult/index.tsx, src/components/TarteelVoiceSearch/BodyContainer/index.tsx, src/hooks/useTarteelVoiceSearch.ts
This PR is a fix for #2056 where now the search begins when the user clicks on the microphone button.
=> Stop voice recording on click

src/api.ts, src/components/Navbar/SearchDrawer/SearchDrawer.tsx, src/components/Navbar/SettingsDrawer/ReciterSelectionBody.tsx, src/components/Navbar/SettingsDrawer/TafsirSelectionBody.tsx, src/components/Navbar/SettingsDrawer/TranslationSelectionBody.tsx, src/components/QuranReader/SidebarNavigation/ScrollableSelection.tsx, src/components/QuranReader/SidebarNavigation/SurahList.tsx, src/components/QuranReader/SidebarNavigation/VerseList.tsx, src/components/Search/NavigationItem/index.tsx, src/components/Search/SearchResults/SearchResultItem.tsx, src/components/Search/SearchResults/index.tsx, src/components/TarteelVoiceSearch/BodyContainer/SearchResults.tsx, src/hooks/useTarteelVoiceSearch.ts, src/pages/reciters/[reciterId]/index.tsx, src/pages/search.tsx, src/utils/apiPaths.ts, src/utils/eventLogger.ts, src/utils/navigation.ts, src/utils/search.ts, types/ApiResponses.ts, types/Search/SearchRequestParams.ts, types/Search/SearchResponse.ts, types/Search/SearchService.ts, types/Search/SearchVerseItem.ts
This deployment contains:
1. #2068
=> Prod deployment

i18n.json, locales/en/quranic-calendar.json, package.json, quranic-calendar.json, src/components/Notes/NotesPage/Tabs/MyPublicReflectionsTab/index.tsx, src/components/QuranReader/ReflectionView/ReflectionBodyContainer/index.tsx, src/components/QuranReflect/ReflectionText/ReflectionText.module.scss, src/components/QuranReflect/ReflectionText/index.tsx, src/components/QuranicCalendar/JoinQuranicCalendarButton/index.tsx, src/components/QuranicCalendar/QuranicCalendarHero/index.tsx, src/components/QuranicCalendar/QuranicCalendarMonth/QuranicCalendarMonth.module.scss, src/components/QuranicCalendar/QuranicCalendarMonth/index.tsx, src/components/QuranicCalendar/QuranicCalendarWeek/QuranicCalendarWeek.module.scss, src/components/QuranicCalendar/QuranicCalendarWeek/index.tsx, src/components/QuranicCalendar/types/QuranicCalendarMonthData.ts, src/components/QuranicCalendar/types/QuranicCalendarWeekData.ts, src/components/Verse/VerseText.tsx, src/pages/quranic-calendar.tsx, src/utils/auth/api.ts, src/utils/auth/apiPaths.ts, src/utils/auth/qf/api.ts, src/utils/auth/qf/apiPaths.ts, src/utils/hijri-date.ts, src/utils/navigation.ts, yarn.lock
This PR adds Quranic Calendar.
=> Quranic calendar

src/components/Banner/Banner.tsx, src/components/Course/Buttons/NavbarButton/index.tsx, src/components/Navbar/Navbar.module.scss, src/components/Navbar/Navbar.tsx, src/components/PageContainer/PageContainer.module.scss, src/components/QuranReader/SidebarNavigation/SidebarNavigation.module.scss, src/pages/index.module.scss
Reverts quran/quran.com-frontend-next#2144
=> Revert "Add post-Ramadan learning plan button"

locales/en/common.json, src/components/DonatePopup/DonatePopup.tsx, src/components/HomePage/HomePageMessage.tsx, src/components/HomePage/HomePageWelcomeMessage.tsx, src/components/Navbar/Navbar.module.scss, src/components/Navbar/Navbar.tsx, src/components/PageContainer/PageContainer.module.scss, src/components/QuranReader/SidebarNavigation/SidebarNavigation.module.scss, src/pages/_app.tsx, src/pages/index.module.scss, src/pages/index.tsx, src/redux/migrations.ts, src/redux/store.ts
Fixes #QF-543
This PR adds donation campaign for Dhul Hijjah
=> Dhul Hijjah donation campaign

src/components/Navbar/SettingsDrawer/WordByWordSection.tsx, src/utils/locale.ts
Fixes #QF-661
Add `Uzbek` language and a fallback language to unlisted languages.
The added language is now showing on the list, and an API name added as fallback name in english if the language doesn't exist on our static list.
=> add Uzbek language and fallback to unlisted locales

src/redux/Provider.tsx
=> QF-821 Only render app when Redux persist is bootstrapped

i18n.json, locales/en/terms-and-conditions.json, src/pages/terms-and-conditions.tsx
=> Create terms and conditions page

src/components/ThirdPartyScripts/MicrosoftClarityScript.tsx, src/components/ThirdPartyScripts/ThirdPartyScripts.tsx
=> Add Microsoft Clarity script

locales/en/learn.json, src/components/Course/CourseDetails/Tabs/MainDetails/DetailSection/EditorsDetails/index.tsx, src/components/Course/CourseDetails/index.tsx, types/auth/Course.ts
Fixes #QF-985
Add Learning Plan Editors
=> QF-985 Add multiple learning plan editors

data/chapters/fr.json, data/chapters/id.json, data/chapters/ms.json
=> Update localized Surah names

src/components/MediaMaker/Settings/TranslationSetting.tsx, src/components/Navbar/SettingsDrawer/TranslationSelectionBody.tsx, src/utils/filter-translations.ts
=> Fix duplicated translations languge name

data/chapters/ur.json, src/utils/locale.ts
=> Update Urdu Surah names

src/utils/chapter.ts
Fixes #QF-1065
This PR adds localization support of Surah names for Malay.
=> QF-1065 Add MS locale support

src/components/QuranReader/SidebarNavigation/SidebarNavigation.module.scss, src/utils/page.ts
Fixes #QF-981
This PR fixes showing all the Mushaf pages when Tajweed Mushaf is selected and the necessary UI modifications.
I have tested the navbar on the `page` tab on Chrome with all UI variations.
=> fix pages sidebar for the tajweed mushaf

src/pages/login.tsx
Fixes #QF-982
This PR fixed issue when guest user plays audio then clicks on the profile icon.
=> QF-982 allow user to play audio on login page

src/components/MarkdownEditor/MarkdownEditor.module.scss
Fixes #QF-1112, #QF-1111.
This PR fixes the styling of embedded iframes in learning plans.
=> QF-1112, QF-1111 update embedded iframe styling

package.json, src/api.ts, src/pages/media/index.tsx, src/pages/search.tsx, src/utils/api.ts, src/utils/apiPaths.ts, src/utils/url.ts
Fixes #[QF-1118](https://quranfoundation.atlassian.net/browse/QF-1118)
This PR resolves the build time issues injected due to proxy and API gateway 
[QF-1118]: https://quranfoundation.atlassian.net/browse/QF-1118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: added env in package.json to use it on build time

src/components/MediaMaker/Settings/TranslationSectionSetting.tsx, src/utils/auth/signature.ts
=> Fix: reoslves undefined and patch requests issue

locales/en/learn.json, src/components/Course/CourseDetails/index.tsx
=> QF-1214 change editors to contributors

src/components/MarkdownEditor/MarkdownEditor.module.scss
=> Set maximum width for iframes

src/utils/auth/signature.ts
Fixes #[QF-1299](https://quranfoundation.atlassian.net/browse/QF-1299)
The PR fixes the issue when a request with delete method is made with payload the signature was not generated correctly.
Ticket Summary: When a user deselects the added collection for a specific ayah a UI error is shown as the attached video below 
[QF-1299]: https://quranfoundation.atlassian.net/browse/QF-1299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: signature generation for Delete method with payload

src/components/Verse/PlainVerseText/index.tsx
Fixes #QF-1061
Fixes the arabic ayah text on the collection page, when settings set to tajweed mushaf dark mode.
Tested on chrome.
| <img width="1440" alt="Screenshot 2024-12-11 at 10 03 13 PM" src="https://github.com/user-attachments/assets/a63449c5-d5f4-4b98-8987-b672f1a7e21f" /> | <img width="1438" alt="Screenshot 2024-12-11 at 10 03 59 PM" src="https://github.com/user-attachments/assets/7ff7d3da-e14a-441d-851f-82773740c57a" /> |
=> fix the ayah text on collection page

src/components/dls/QuranWord/QuranWord.tsx, src/redux/migrations.ts, src/redux/store.ts
Fixes #QF-1426
This PR:
1. Enables word-by-word for all users.
2. Enables word-by-word for reading view.
=> QF-1426 wbw

next-sitemap.js
Fixes 
site map generation with tafsirs, reciters and courses after api
=> fix: site map generation

src/pages/developers.tsx
Fixes [#QF-1453](https://quranfoundation.atlassian.net/browse/QF-1453)
=> QF-1453 Update API docs link

locales/en/login.json, src/pages/login.tsx, src/utils/auth/api.ts, types/AuthError.ts
Fixes #[QF-1397]
This PR introduces handling of banned user when a user is logged in and try to perform the next action after getting banned.
NOTE: Need to add translation for BannedUserError in login-error translations.
[QF-1397]: https://quranfoundation.atlassian.net/browse/QF-1397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: resolves ban user action to show message and logout

src/components/Navbar/SearchDrawer/SearchDrawer.tsx, src/components/Search/CommandBar/ExpandedSearchInputSection/index.tsx, src/utils/search.ts, types/Search/SearchRequestParams.ts
=> Limit quick search results to 10

src/components/QuestionAndAnswer/QuestionHeader/index.tsx, src/components/QuestionAndAnswer/QuestionsList/index.tsx, src/pages/questions/[questionId].tsx
=> Use question body instead of summary

src/components/QuranReader/TranslationView/TranslationViewCell.tsx
=> Fix memoization of TranslationViewCell

src/components/QuestionAndAnswer/Answer/index.tsx, src/components/QuestionAndAnswer/QuestionsBodyContainer/QuestionsBody/index.tsx, src/components/Verse/GroupedVerseAndTranslation.module.scss, src/components/Verse/GroupedVerseAndTranslation.tsx, src/components/Verse/VerseAndTranslation.tsx, src/hooks/useVerseAndTranslation.ts
=> Group Ayah/Translation of Q&A

src/components/QuestionAndAnswer/QuestionsModal/QuestionsModal.module.scss, src/components/QuestionAndAnswer/QuestionsModal/index.tsx, src/components/dls/ContentModal/ContentModal.module.scss, src/components/dls/ContentModal/ContentModal.tsx
=> Q&A UI updates

data/chapters/es.json
=> Update Spanish Surah names

locales/sw/learn.json
=> Update Swahili locale

src/redux/defaultSettings/locales/es.ts
=> Set Sheikh Isa Garcia's translations as default Spanish translation

data/chapters/sw.json
=> Add Swahili Surah names

src/components/Search/SearchInput/index.tsx, src/redux/slices/voiceSearch.ts
=> Close voice search when clicking outside

src/pages/ramadan-activities/index.tsx
=> Update Ramadan Activities page

src/components/Fundraising/FundraisingBanner.tsx
=> Update donation links in the burger menu

src/pages/questions/[questionId].tsx
=> Update questions page title

src/components/MediaMaker/Settings/AudioTab.tsx
Allow the user to select any verse in the verse from dropdown, and show the error message if the user tried to select a verse to before the selected verse from.
=> allow random select in verse from

src/utils/url.ts
=> allow http in development

src/components/QuestionAndAnswer/Answer/AnswerBody/index.tsx
=> Add markdown support for Q&A

src/components/MediaMaker/RenderControls/index.tsx, src/components/MediaMaker/Settings/VideoSettings.tsx, src/hooks/useAddQueryParamsToUrlSkipFirstRender.ts, src/hooks/useGetQueryParamOrReduxValue.ts, src/pages/index.module.scss, src/pages/media/index.tsx, src/utils/auth/apiPaths.ts, src/utils/media/utils.test.ts, src/utils/queryParamValidator.test.ts, types/Media/GenerateMediaFileRequest.ts
- fix copy link button
- fix preview mode
- fix query params overwriting
- add auto play, mute, and hide settings on preview mode enabled
Closes: QF-1974 and QF-2028
=> QF-1974 - Video Generator

src/components/HomePage/ReadingSection/ChapterCard/index.tsx, src/components/QuranReader/SidebarNavigation/SurahList.tsx, src/components/Verses/RecentReadingSessionsSkeleton.tsx, src/components/dls/SurahPreview/SurahPreviewBlock.tsx, src/components/dls/SurahPreview/SurahPreviewRow.tsx
Stop auto-translating Surah names.
Closes #QF-2081
=> Don't translate Surah names

src/components/Navbar/LanguageSelector.module.scss, src/components/Navbar/LanguageSelector.tsx
=> Scrollable language selector

src/components/HomePage/ReadingSection/ChapterCard/index.tsx
=> Clickable begin reading card

src/components/Course/LessonView/index.tsx, src/components/PageContainer/PageContainer.module.scss, src/components/PageContainer/index.tsx
=> Lesson plans container

src/components/QuestionAndAnswer/Answer/AnswerBody/AnswerBody.module.scss, src/pages/questions/questions.module.scss
=> Update Answers UI

src/components/QuranReader/EndOfScrollingControls/index.tsx
=> Move donner box below end of scrolling controls

src/pages/[chapterId]/answers/[questionId].tsx
=> Update answer metadata

src/components/HomePage/LearningPlansSection/LearningPlansSection.module.scss
=> Homepage learning plans horizontal scoll

src/components/QuranReader/ReadingView/CopyButton/CopyButton.module.scss, src/components/QuranReader/ReadingView/CopyButton/index.tsx, src/components/QuranReader/ReadingView/WordActionsMenu/WordActionsMenu.module.scss, src/components/QuranReader/ReadingView/WordActionsMenu/index.tsx, src/components/QuranReader/TranslationView/TranslationViewCell.tsx, src/components/Verse/OverflowVerseActionsMenuBody/ShareVerseActionsMenu/index.tsx
Closes #2120
- remove the copy menu item and add a copy button on the top level menus
=> remove the copy menu item and add a copy button on the top level menus

src/components/MediaMaker/RenderControls/index.tsx, src/hooks/auth/media/useGenerateMediaFile.ts, src/utils/device-detector.ts, types/auth/Response.ts
Closes #QF-2121 #QF-2123
- QF-2121 generate link button showing in chrome ios
- QF-2123 exceeding download images limit showing the wrong error
=> video generator QF-2121 QF-2123

locales/en/common.json, src/components/Navbar/NavigationDrawer/CommunitySection.tsx
Closes #QF-2130
- update community section in the developers page
=> update community section

src/components/MediaMaker/RenderControls/index.tsx
Closes #QF-2121
Fix chrome on ios
=> fix generate button - chrome on ios

locales/en/common.json, src/pages/_app.tsx
=> Reenable donation popup

src/components/QuranReader/ReadingView/WordActionsMenu/index.tsx
Closes #QF-2121
Change the copy button place in reading mode.
=> change the copy button place in reading mode

locales/en/common.json
=> Update fundraising text

locales/en/quran-reader.json, src/pages/[chapterId]/answers/[questionId].tsx
but ow we use the question and the summary of the answer
=> updated page title and meta desc, previously they were generic

src/components/QuranReader/ReadingView/WordActionsMenu/index.tsx, src/components/QuranReader/TranslationView/TranslationViewCell.tsx
Closes #QF-2121
- change the copy button place in the translation view
=> QF 2121 change copy button place

locales/en/common.json, src/components/QuranReader/ReadingView/CopyButton/index.tsx
Closes #QF-2121
- show toast message on verse copy
=> show toast message on verse copy

src/components/QuranReader/TranslationView/TranslationViewCell.tsx
Closes: #QF-2121
Remove extra copy button
=> QF-2121 remove extra button

src/components/Verse/VerseAndTranslation.tsx, src/utils/eventLogger.ts
=> Add userId to logger

src/utils/hijri-date.test.ts, src/utils/hijri-date.ts
=> Fix week number

src/pages/[chapterId]/answers/index.tsx
=> Update meta description of answers page

src/components/HomePage/ReadingSection/index.tsx, src/hooks/auth/useGetRecentlyReadVerseKeys.ts, src/redux/slices/session.ts
Fixes [#QF-2305](https://quranfoundation.atlassian.net/browse/QF-2305)
=> Qf 2305 mismatch of last read

src/xstate/actors/audioPlayer/audioPlayerMachine.ts, src/xstate/actors/audioPlayer/audioPlayerMachineHelper.ts
Fix an issue when audio highlighting is on:
```
TypeError: undefined is not an object (evaluating 'e.verseKey')
at getActiveAyahNumber(./src/xstate/actors/audioPlayer/audioPlayerMachineHelper.ts:79:27)
at audioPlayerMachine.actions.setElapsedTime(./src/xstate/actors/audioPlayer/audioPlayerMachine.ts:889:30)
```
=> Fix undefined is not an object (evaluating 'e.verseKey')

src/components/Search/CommandBar/CommandsList/index.tsx, src/components/Search/SearchResults/index.tsx
Fixes [#QF-2603](https://quranfoundation.atlassian.net/browse/QF-2603)
=> Qf 2603 show more results

src/components/QuestionAndAnswer/QuestionHeader/QuestionHeader.module.scss, src/components/QuestionAndAnswer/QuestionHeader/index.tsx
Fixes [#QF-2582](https://quranfoundation.atlassian.net/browse/QF-2582)
=> Remove question themes

src/components/Search/SearchInput/index.tsx
=> dropdown search does not appear agin when clicking esc

src/components/Course/CourseDetails/CourseDetails.module.scss, src/components/Course/CourseDetails/index.tsx
=> Fix stretched learning plans images

src/components/GlobalScrollListener.tsx, src/components/Navbar/Drawer/index.tsx, src/components/Navbar/Navbar.tsx, src/components/QuranReader/ContextMenu/components/MobileReadingTabs.tsx, src/components/QuranReader/ContextMenu/components/PageBookmarkAction.tsx, src/components/QuranReader/ContextMenu/components/PageInfo.tsx, src/components/QuranReader/ContextMenu/hooks/useContextMenuState.ts, src/components/QuranReader/ContextMenu/index.tsx, src/components/QuranReader/ReadingPreferenceSwitcher/index.tsx, src/components/QuranReader/SidebarNavigation/PageSelection.tsx, src/components/QuranReader/SidebarNavigation/ScrollableSelection.tsx, src/components/QuranReader/SidebarNavigation/SidebarNavigationSelections.tsx, src/components/QuranReader/SidebarNavigation/SurahList.tsx, src/components/QuranReader/SidebarNavigation/SurahSelection.tsx, src/components/chapters/ChapterHeader/ChapterHeader.module.scss, src/hooks/useDebounceNavbarVisibility.ts, src/hooks/useScrollRestoration.ts, src/redux/slices/navbar.ts, types/NavigationItemType.ts
Closes: [QF-2757](https://quranfoundation.atlassian.net/browse/QF-2757), [QF-2759](https://quranfoundation.atlassian.net/browse/QF-2759), [QF-2760](https://quranfoundation.atlassian.net/browse/QF-2760),  [QF-2761](https://quranfoundation.atlassian.net/browse/QF-2761), and [QF-2764](https://quranfoundation.atlassian.net/browse/QF-2764)
- feat: conditionally show bookmark action in page info component based on navbar visibility
- fix: implement debounced navbar visibility and cleanup event listeners
- refactor: extract navbar visibility debouncing into shared hook
- feat: conditionally render navbar based on scroll position
- fix: prevent navbar flickering during reading preference tab switches
- feat: add navigation item type tracking and update last read verse on navigation
[QF-2757]: …
=> surah bar fixes

src/components/QuranReader/ReadingView/ShareQuranModal.tsx
Closes: [QF-2871](https://quranfoundation.atlassian.net/browse/QF-2871)
[QF-2871]: https://quranfoundation.atlassian.net/browse/QF-2871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: update share URL path by removing surah prefix

src/components/QuranReader/ContextMenu/components/PageInfo.tsx, src/components/QuranReader/ContextMenu/hooks/useContextMenuState.ts, src/components/QuranReader/ContextMenu/index.tsx, src/redux/migrations.ts, src/redux/store.ts
[QF-2876](https://quranfoundation.atlassian.net/browse/QF-2876)
[QF-2876]: https://quranfoundation.atlassian.net/browse/QF-2876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> QF 2876 fix page bookmarks when language is arabic

src/pages/login.tsx
Closes: [QF-2855](https://quranfoundation.atlassian.net/browse/QF-2855)
[QF-2855]: https://quranfoundation.atlassian.net/browse/QF-2855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add static props to fetch chapter data on login page

locales/en/quran-reader.json, src/components/QuranReader/LearningPlanBanner/LearningPlanBanner.module.scss, src/components/QuranReader/LearningPlanBanner/index.tsx
Fixes [QF-3499](https://quranfoundation.atlassian.net/browse/QF-3499?atlOrigin=eyJpIjoiNzZkYTY0NjU4NjM5NDViMzk4ODZiMDU4Y2IyM2M4YzgiLCJwIjoiaiJ9)
[QF-3499]: https://quranfoundation.atlassian.net/browse/QF-3499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update localization strings and improve Learning Plan Banner styles

src/components/QuranReader/ReflectionView/ReflectionItem/index.tsx, src/utils/quranReflect/navigation.ts, types/QuranReflect/Room.ts
Closes [#QF-3505](https://quranfoundation.atlassian.net/browse/QF-3505)
=> Fix room's url
